<?php if(LOGGEDIN){ ?>
<ul class="stn-menu stn-menu-style red">

    <li class="hasSubNav hasArrow">
        <a href="javascript:"><span class="icon_friend_not"><?php echo $this->totalCount ?></span></a>
        <ul>
            <li><a href="/friendsnotification/index/index/id/<?php echo USERID ?>">Friend Request <?php echo $this->friendsCount ?></a></li>
            <li><a href="/profile/index/messages/id/<?php echo USERID ?>">Messages <?php echo $this->messagesCount ?></a></li>
            <li><a href="/friendsnotification/index/email-my-profile/<?php echo USERID ?>">Email My Profile</a></li>
            <li><a href="/friendsnotification/index/email-referrals/<?php echo USERID ?>">Email Referrals</a></li>
            <li><a href="http://mail.exploretalent.com/src/login.php">Check Email</a></li>
        </ul>
    </li>
    <li class="hasSubNav hasArrow">
        <a href="javascript:"><span class="icon_message_not"><?php echo $this->totalViews ?></span></a>
        <ul>
            <li><a href="/friends/index/view/id/<?php echo USERID ?>">My Friends</a></li>
            <li><a href="/fans/index/view/id/<?php echo USERID ?>">My Likes/Fans</a></li>
            <li><a href="/friends/index/get-more-friends/id/<?php echo USERID ?>">Get more Friends</a></li>
            <li><a href="/online">Members Online</a></li>
            <li><a href="/activityfeed">People Activity</a></li>
            <li><a href="/join/index/now">Who just joined ET</a></li>
            <li><a href="/testimonials">Testimonials</a></li>
            <li><a href="/profile/viewed/<?php echo USERID ?>">Profiles I Viewed <?php echo $this->dataViewed ?></a></li>
            <li><a href="/profile/views/<?php echo USERID ?>">Viewed My Profile <?php echo $this->dataViews ?></a></li>
        </ul>
    </li>
    <li class="hasSubNav hasArrow">
        <a href="javascript:"><span class="icon_more_not"><?php echo $this->listCount ?></span></a>
        <ul>
            <li><a href="/search/acting">Auditions & Jobs</a></li>
            <li><a href="/notifications/index/myjobs/id/<?php echo USERID ?>">My Saved jobs <?php echo $this->fetcsSaved ?></a></li>
            <li><a href="/notifications/index/submissions/id/<?php echo USERID ?>">My Submissions <?php echo $this->submissions ?></a></li>
            <li><a href="/notifications/index/submission-calendar/<?php echo USERID ?>">Submission Calendar</a></li>
            <li><a href="/notifications/index/castings-jobs-preferences/id/<?php echo USERID ?>">Casting/Job Preferences</a></li>
            <li><a href="/about/how-to-get-votes">How to get Points/Votes</a></li>
            <li><a href="/about/industry">Industry Terms</a></li>
            <li><a href="/auditions/index/industry">Industry Resources</a></li>
        </ul>
    </li>

</ul>
<?php } ?>