<div class="subscription_content">
    <span class="hspan"></span><h1>Select your subscription</h1>

    <p >

    </p>
    <span class="sub_p"></span>
</div>
<div style="clear: both"></div>
<br>
<div>
    <table class="subscription_table border_small">

        <thead>
            <tr>
                <th></th>
                <th>
                    <div class="subs_title">Free Membership</div>
                    <div class="subs_price_old"></div>
                    <div class="subs_price_new"></div>
                    <!-- <a href="<?php echo SECURE_DOMAIN; ?>/orders"><img src="/graphics/upgrade_blue.png" /></a>  -->
                </th>
                <th class="subs_width_mid">
                    <div class="subs_title">Pro Membership</div>
                    <div class="subs_price_old">29.95/ month</div>
                    <div class="subs_price_new">16.33/ month</div>
                    <a href="<?php echo STAFF_DOMAIN; ?>/join_5_3.php"><img src="<?php echo CDN_JS_CSS; ?>/graphics/upgrade_green.png" /></a>
                </th>
                <th>
                    <div class="subs_title">Pro + Featured Membership</div>
                    <div class="subs_price_old">49.95/ month</div>
                    <div class="subs_price_new">22.50/ month</div>
                    <a href="<?php echo STAFF_DOMAIN; ?>/join_5_ft_1.php"><img src="<?php echo CDN_JS_CSS; ?>/graphics/upgrade_blue.png" /></a>

                </th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <th class="subs_aling">Create and Edit a Profile</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Find and Make Friends</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">View Auditions Current Listings</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Participate in Contests</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Community Buzz</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">24 Hour Chat</th>
                <th class="subs_width"><span class="subs_check"></span></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Submit to Auditions</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">100 Free Business Cards ($60.00 Value)</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Contact with Casting Directors</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Become a Featured Contestant</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Casting Directors Find You First</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Live Phone Support</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Personalized Promotion Package</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Access to Talent Professionals</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"><span class="subs_check"></span></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Maximum Exposure</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Profile Featured on ExploreTalent Home Page for Casting Directors to see</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Profile Shows up on Top of Talent Search Results</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Profile inserted into the Rate Talent game</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Profile featured on Casting Directors' homepages</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
            <tr>
                <th class="subs_aling">Your Submitted Videos show up on top of Member Videos page</th>
                <th class="subs_width"></th>
                <th class="subs_width_mid"></th>
                <th class="subs_width"><span class="subs_check"></span></th>
            </tr>
        </tbody>

        <tfoot>
            <tr> <?php
                       //var_dump($_SESSION['Zend_Auth']);
            	 ?>
                <th></th>
                <th><a href="<?php echo SECURE_DOMAIN; ?>/orders/index/index/id/<?php echo USERID; ?>"></a></th>
                <th class="subs_width_mid">
                    <a href="<?php echo STAFF_DOMAIN; ?>/join_5_3.php"><img src="<?php echo CDN_JS_CSS; ?>/graphics/upgrade_green.png" /></a>
                    <div class="subs_recomanded"></div>
                </th>
                <th><a href="<?php echo STAFF_DOMAIN; ?>/join_5_ft_1.php"><img src="<?php echo CDN_JS_CSS; ?>/graphics/upgrade_blue.png" /></a></th>
            </tr>
        </tfoot>

    </table>
</div>