<table class="job-table">
    <tr>
        <td class="job-title-name c1">Title</td>
        <td class="job-title-loc c1">Location</td>
        <td class="job-title-type c1">Type</td>
        <td class="job-title-type c1">Submit By</td>
    </tr>
    <?php $i = 0; foreach ($this->acting as $audition) { ?>
    <?php $class = $i % 2 == 0 ? 'first_row' : 'second_row'; ?>
    <tr class="<?php echo $class;?>">
        <td class="list-1">
            <a href="<?php echo $this->url(
                array(
                    'category' => Application_Model_Seo::normalizeKeywords($audition->getCat()->value,'-'),
                    'title' => Application_Model_Seo::normalizeKeywords($audition->getName(),'-'),
                    'location' => Application_Model_Seo::normalizeKeywords($audition->getLocation(),'-'),
                    'location_id' => Application_Model_Seo::normalizeKeywords($audition->getZip(),'-'),
                    'casting_id' => Application_Model_Seo::normalizeKeywords($audition->getCastingId(),'-')
                ),'audition_detail'
            );?>" >
                <?php echo ucwords (strtolower (str_replace ("***", "", $audition->getName ()))); ?>
            </a>
        </td>
        <td><span class="job-list-span2"><?php echo $audition->getLocation (); ?></span></td>
        <td><span class="job-list-span3"><?php echo $audition->getProjectType (); ?></span></td>
        <td><span class="job-list-span3"><?php echo $audition->getAsap(); ?></span></td>
    </tr>
    <?php $i++;
}?>
</table>
<a href="<?php echo $this->url(array(),'acting_route');?>"><div class="more_auditions"></div></a>