<div class="social_right">
	<?php echo $this->partial('partials/pagename.phtml', array( 'info' => $this->info, 'auth'=>$this->auth)); ?>
	<?php echo $this->partial('partials/images.phtml',
        array(
             'title'=>'Dance Image Gallery',
             'action'=>'dance',
             'allimages'=>$this->allimages,
             'userid'=>$this->userid,
             'talentname'=>$this->talentname,
             'action_name'=>$this->action_name
        )); ?>
</div>