<div class="social_right ">
    <div class='profile_links_image'>
        <h1>Links to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h1>
        <ul>
            <li><p>Take the next step in promoting yourself.</p></li>
            <li><p>Post the link to your ExploreTalent.com profile on other websites!</p></li>
            <li><p>Just pick the type of link you want from the below ones.</p></li>
            <li><p>Copy the code and paste it into the other website.</p></li>
        </ul>
    </div>
    <br>
    <br>
    <br>
    <div class='profile_links'>
        <h2>Example Link #1 to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h2>
        <img src="http://www.exploretalent.com/images/links/banner-03.gif">
        <div>
            <p>
                <span class='profile_link_code'>Example Link #1 - The Code:</span>
                <span>Copy and paste the code below</span>
            </p>
            <textarea onclick='this.select()'>&lt;a href="<?php echo Application_Model_Seo::getProfileCanonicalLink($this->info->getTalentlogin()); ?>" target="_blank"&gt;&lt;img src="http://www.exploretalent.com/images/links/banner-03.gif" width="160" height="60" alt="View My Explore Talent Profile - Find Auditions for Modeling and Acting"&gt;&lt;/a&gt;</textarea>
        </div>
    </div>
    <div class='profile_links'>
        <h2>Example Link #2 to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h2>
        <img src="http://www.exploretalent.com/images/links/banner-04.gif">
        <div>
            <p>
                <span class='profile_link_code'>Example Link #2 - The Code:</span>
                <span>Copy and paste the code below</span>
            </p>
            <textarea onclick='this.select()'>&lt;a href="<?php echo Application_Model_Seo::getProfileCanonicalLink($this->info->getTalentlogin()); ?>" target="_blank"&gt;&lt;img src="http://www.exploretalent.com/images/links/banner-03.gif" width="160" height="60" alt="View My Explore Talent Profile - Find Auditions for Modeling and Acting"&gt;&lt;/a&gt;</textarea>
        </div>
    </div>
    <div class='profile_links'>
        <h2>Example Link #3 to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h2>
        <img src="http://www.exploretalent.com/images/links/banner-01.gif">
        <div>
            <p>
                <span class='profile_link_code'>Example Link #3 - The Code:</span>
                <span>Copy and paste the code below</span>
            </p>
            <textarea onclick='this.select()'>&lt;a href="<?php echo Application_Model_Seo::getProfileCanonicalLink($this->info->getTalentlogin()); ?>" target="_blank"&gt;&lt;img src="http://www.exploretalent.com/images/links/banner-03.gif" width="160" height="60" alt="View My Explore Talent Profile - Find Auditions for Modeling and Acting"&gt;&lt;/a&gt;</textarea>
        </div>
    </div>
    <div class='profile_links'>
        <h2>Example Link #4 to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h2>
        <img src="http://www.exploretalent.com/images/links/banner-02.gif">
        <div>
            <p>
                <span class='profile_link_code'>Example Link #4 - The Code:</span>
                <span>Copy and paste the code below</span>
            </p>
            <textarea onclick='this.select()'>&lt;a href="<?php echo Application_Model_Seo::getProfileCanonicalLink($this->info->getTalentlogin()); ?>" target="_blank"&gt;&lt;img src="http://www.exploretalent.com/images/links/banner-03.gif" width="160" height="60" alt="View My Explore Talent Profile - Find Auditions for Modeling and Acting"&gt;&lt;/a&gt;</textarea>
        </div>
    </div>
    <div class='profile_links'>
        <h2>Example Link #4 to <?php echo $this->info->getFname() . ' ' . $this->info->getLname();?>'s Profile</h2>
        <a href="http://www.exploretalent.com/">View My ExploreTalent Profile</a>
        <div>
            <p>
                <span class='profile_link_code'>Example Link #5 - The Code:</span>
                <span>Copy and paste the code below</span>
            </p>
            <textarea onclick='this.select()'>&lt;a href="<?php echo Application_Model_Seo::getProfileCanonicalLink($this->info->getTalentlogin()); ?>" target="_blank"&gt;&lt;img src="http://www.exploretalent.com/images/links/banner-03.gif" width="160" height="60" alt="View My Explore Talent Profile - Find Auditions for Modeling and Acting"&gt;&lt;/a&gt;</textarea>
        </div>
    </div>
</div>
