<h1>Find an audition  in your area</h1>
      <div>
          <table width="655" border=0>
              <tr>
              <td><div align="center"><a href='http://www.auditions-auditions.com'>Casting</a></div></td>
              <td><div align="center"><a href='http://www.exploretalent.com/top-talent/'>Browse our top talents</a></div></td>
              <td><div align="center"><a href='http://www.exploretalent.com/top-talent/jessica-wynne.html'>Jessica Wynne</a></div></td>
              <td><div align="center"><a href='http://www.exploretalent.com/exploretalent.htm'>ExploreTalent Information</a><br></div></td>
              </tr>
              <tr>
                  <td><div align="center"><a href='http://www.auditionsmovie.com'>Baby Modeling</a></div></td>
                  <td><div align="center"><a href='http://www.auditions.com'>Audition</a></div></td>
                  <td><div align="center"><a href='http://www.explore-talent.net'>Explore
                      Talent</a></div></td>
                  <td><div align="center"><a href='http://www.modeling-modeling.com'>Modeling</a></div></td>
              </tr>
              <tr>
                  <td><div align="center"><a href='http://www.auditionsmovie.com'>Auditions</a></div></td>
                  <td><div align="center"><a href='http://www.auditions-auditions.com'>Modeling
                      Agencies</a></div></td>
                  <td><div align="center"><a href='http://www.actingacting.com'>Acting</a></div></td>
                  <td><div align="center"><a href='http://forum.exploretalent.com/sd/acting.html'>Acting</a>&nbsp;</div></td>
              </tr>
          </table>
      </div>
<div>
    <p>
        At
        ExploreTalent, you will find many auditions in different areas of talent
        from all over the internet in one place. Our unique features make us the
        most comprehensive audition resource site on the internet. We provide
        our own casting calls, auditions, casting, open calls, casting calls and
        virtual casting area. For the 1st time ever casting directors and production
        companies can cast an entire project from start to finish with the click
        of a mouse. Now actors, musicians, models, dancers and other talent have
        auditions to search for rght at their fingertips. All the information
        is absolutely FREE!
    </p>
    <p>
        <a href="/join/flash">Join ExploreTalent for free</a> to find the latest talent information.
    </p>
</div>
