<h1>Explore Talent</h1>
<div class="border_small">
    <table width="655" border=0>
        <tr>
        <td>
            <div align="center"><a href='http://www.exploretalent.com/join.php'>Join for Free</a></div>
        </td>
        <td>
            <div align="center"><a href='http://www.exploretalent.com/top-talent/'>Browse our top talents</a></div>
        </td>
        <td>
            <div align="center"><a href='http://www.exploretalent.com/top-talent/jessica-wynne.html'>Jessica Wynne</a></div>
        </td>
        <td>
            <div align="center"><a href='http://www.exploretalent.com/exploretalent.htm'>ExploreTalent Information</a><br>
            </div>
        </td>
        </tr>
        <tr>
            <td>
                <div align="center"><a href='http://www.castingaudition.com'>Casting</a></div>
            </td>
            <td>
                <div align="center"><a href='http://www.castingaudition.com'>Casting Calls</a></div>
            </td>
            <td>
                <div align="center"><a href='http://www.auditionsmovie.com'>Casting Auditions</a></div>
            </td>
            <td>
                <div align="center"><a href='http://forum.exploretalent.com/forum'>Our Forum</a></div>
            </td>
        </tr>
        <tr>
            <td>
                <div align="center"><a href='http://www.modeling.net'>Model</a></div>
            </td>
            <td>
                <div align="center"><a href='http://www.modeling.net'>How to become
                    a model</a></div>
            </td>
            <td>
                <div align="center"><a href='http://www.auditions.com'>Auditions</a></div>
            </td>
            <td>
                <div align="center"><a href='http://www.myactingagent.com'>Acting</a></div>
            </td>
        </tr>
    </table>

    <p>At
        ExploreTalent, you will find acting modeling, casting calls, open calls
        information resources and much more. At Explore Talent we also have resources
        on acting schools, acting coaches and acting auditions from all over the
        internet in one place. Our unique features make us the most comprehensive
        acting tips, acting resources. Explore Talent provides our own casting
        calls, auditions, casting, open calls, casting calls and virtual casting
        areas. For the 1st time ever casting directors and production companies
        can cast an entire project from start to finish with the click of a mouse.
        Now actors, musicians, models, dancers and other talent have acting tips,
        acting resources like acting schools, acting coaches and acting auditions
        right at their fingertips. All the information is absolutely FREE! </p>

    <p>Many
        Casting Agents are auditioning shows, movies and commercials everyday.
        They need actors from all over the country and with Explore Talent and
        it's resources for acting tips, acting resources like acting schools,
        acting coaches and acting auditions casting agents lists you can get started
        working faster.</p>

    <p>Take

        control of your career at ExploreTalent and find your next acting tips,

        acting resources like acting schools, acting coaches and acting auditions

        from all over the Internet today. Our team of in-house researchers are

        constantly looking for new acting tips, acting resources like acting schools,

        acting coaches and acting auditions, producers and casting directors on

        a daily basis.</p>

    <p><a href="/join/flash">Join
        ExploreTalent for free</a> to find the acting tips, acting resources like
        acting schools, acting coaches and acting auditions you need. Explore
        Talent that you have today!</p>

</div>