<h1>Find Extras roles in your area!</h1>

<div class="border_small">
    <p>At ExploreTalent, you will find many Extras jobs in movies , films, commercials,
        all in one place. Our unique features make us the most comprehensive Extras
        resource for movies, films, and commercials site on the Internet. We provide
        our own casting calls, auditions, casting, open calls, casting calls and
        virtual casting area. For the 1st time ever casting directors and production
        companies can cast an entire project from start to finish with the click
        of a mouse. Now Extras work information is rite at your fingertips. All
        the information is absolutely FREE! </p>

    <p><a href="/join/flash">Join
        ExploreTalent for free</a> to find the Movie Extras, Extra work, movie
        extra, film extras, commercial extras roles you need.
    </p>
</div>
