<h1><a href="/modeling-acting.html">Model Search! click here...</a></h1>
<div class="border_small">
    <p>Explore Talent is having a
        Model Search. You can be the next model sporting the news lines up and
        down the runway! Just take a look at our model search resources. They
        help you go in the direction you want and that is only up! Be a model
        search star!
    </p>

    <p><a href="/join/flash">Join
        ExploreTalent for free</a>
    </p>
</div>
