<h1>Find Model Jobs
    in your area!</h1>

<div class="border_small">
    <p>When
        going on model auditions, your portfolio and resume most likely got you
        in the door. If you have a modeling agent, that agency will put together
        your portfolio and promote you to companies looking for new faces for
        their product. Depending on the product being sold, different jobs will
        require different looks. When creating your portfolio, try to include
        pictures that showcase the different looks you might have. Never be too
        bold if you can pull it off. The more options you may be able to display
        as a model, the better chance you have of booking a job. Most models have
        a look or genre they are most confident with, so stay true to what you
        think your best look or style is. </p>

    <p>Take
        control of your career at ExploreTalent and find your next Model jobs.
        We have tons of resource for your every need. Start your career and become
        a model today!!!</p>

    <p><a href="/join/flash">Join
        ExploreTalent for free</a></p>
</div>