<h1>Modeling Auditions find acting and Modeling Auditions Click here</h1>
<div class="border_small">
    <table>
        <tr>
            <td>
                ExploreTalent.com can help you find:<br>
                <ul>
                    <li><a href="http://casting-call.us">Casting</a></li>
                    <li>- <a href="http://castingaudition.com">Auditions</a></li>
                    <li>- Open Calls</li>
                    <li>- Acting Roles</li>
                    <li>- Casting Calls</li>
                    <li>- Modeling jobs</li>
                    <li>- Acting Jobs</li>
                    <li>- Exposure</li>
                    <li>- Agent<br> <a href="/why_join.php">More features</a></li>
                </ul>
                <b> It's FREE! No Credit Card needed </b>
            </td>
        </tr>
    </table>
    <br>
    <br>

    <h2><a href="http://exploretalent.com/forum" target="_parent">Check
        out the new Actors' &amp; Models' Forum</a></h2>

    <h3>Jump start your modeling or acting career! <a href="/join/flash">Sign Up to Explore Talent for FREE
        NOW!:</a></h3>

    <p>Thousands
        of talented members started their careers at ExploreTalent.
        Here Actors and Models are submitted for current Modeling
        Auditions, Acting Auditions, &amp; Casting calls through
        our &quot;Auditions Submissions Service&quot;. The World's
        Biggest Modeling &amp; Acting Website, with over 600,000
        models and actors, ExploreTalent.com is the most visited
        site by Talent Agencies, Managers, Casting Directors
        &amp; Industry professionals. You will find an extensive
        selection of modeling auditions, acting auditions and
        much much more. Free personal website, domain, portfolio,
        photo gallery with full support, Talent Forum &amp;
        more. <a href="/join/flash"><br>
            Act now! Create your free website</a> &nbsp;(no
        credit card needed)</p>

    <p>ExploreTalent
        matches Talent with current Casting Calls & Auditions! Checkout ExploreTalent Actors & Models
        - Click here to see our models and actors</p>

    <h3>The Internet's
        largest Modeling Auditions and Acting Auditions Resource Site.</h3>

    <p align="justify">with more than 20,000 modeling
        agents, acting agents, casting directors, modeling &amp; acting
        coaches, modeling photographers, theatrical auditions, modeling
        auditions, acting auditions &amp; more - updated daily, as well
        as over 300,000 registered models &amp; actors <a href="http://exploretalent.com">at Explore Talent.</a>
        If you are interested in promoting your modeling or acting career
        this is the place to start. We submit Compcards for Modeling Auditions
        and casting calls, acting auditions and castings and other theatrical
        auditions.</p>

    <p align="justify"><a href="/join/flash">Register
        for free</a> and take advantage of your free modeling / acting
        webpage with bio, gallery &amp; more. Recieve a monthly newsletter
        at your personal ExploreTalent email with tips on how to activiely
        promote your modeling / acting career. <a href="http://exploretalent.com/forum"
                                                  target="_parent"><em>Discuss
            Acting &amp; Modeling in our new Talent Forum</em></a>!</p>

    <p><a href="/join/flash">Sign
        up now</a> to Get your face, voice and name in front of more
        modeling and acting industry professionals than any other site on
        the Web. - <a href="/join/flash">Start your modeling
            and acting career now!</a></p>


    <p>A word from ExploreTalent: In order to find paid
        acting and modeling jobs, actors and models will need to have the necessary
        tools. ExploreTalent offers acting &amp; modeling assistance by providing
        you with an online modeling portfolio or an online actors webpage, both
        provide you with a personal webpage, bio section, photo gallery for your
        modeling or acting headshots, compard or examples of your previous work.
        These are invaluable to models seeking paid modeling jobs and actors seeking
        paid acting jobs. You should have a modeling card (comp or zed) to get
        casting calls and actors need headshots for acting auditions. This is
        the way of the modeling and acting industries. Once you have your comp
        or zed card ExploreTalent can submit it to acting auditions and casting
        calls, modeling autitions and casting calls and other theatrical auditions
        and casting calls. Join for free and take advantage of the specific benefits
        for both actors and models. Acting &amp; Modeling are exciting and profitable
        ventures, best of luck!</p>


    <p>&copy; ExploreTalent All rights reserved. <a
            href="http://exploretalent.com/modeling-links.html" target="_parent">Links</a>
    </p>

    <p>Modeling Auditions <a href="http://www.myactingagent.com">Acting Jobs</a>
        <a href="http://www.casting-call.us">Casting Calls</a></p>

</div>