<h1>Find open auditions
    in your area!</h1>

<div class="border_small">
    <p><strong>Explore
        Talent is having auditions in your area for many genres including modeling,
        acting, acting in films, movies, and other great opportunities! Take a
        look at your resources and see how easy it is to get your career on the
        right track or for you new comers, get your career started today!</p>

    <p><a href="/join/flash">Join
        ExploreTalent for free</a> to find the latest casting, fresh audition,
        acting audition, movie audition, Open Auditions, first time audition,
        open calls, casting calls & castings.</p>
</div>