<h1>Search For Agencies, Castings Directors, Photographers, Studios and other Industry-related Resources</h1>
<div class="border_small">
    <table border="0" cellspacing="1" cellpadding="1">
        <tr bgcolor="#eeeeee">
            <td>Agencies</td>
            <td>2092</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=0&state=">View the list</a></td>
        </tr>
        <tr>
            <td>Casting Directors</td>
            <td>1110</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=1&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Photographers</td>
            <td>3915</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=2&state=">View the list</a></td>
        </tr>
        <tr>
            <td>Reality TV Shows</td>
            <td>51</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=3&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Studios</td>
            <td>910</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=4&state=">View the list</a></td>
        </tr>
        <tr>
            <td>Print Shops</td>
            <td>383</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=5&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Talent Managers</td>
            <td>225</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=6&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Acting Coaches</td>
            <td>62</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=7&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Modeling Schools</td>
            <td>17</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=8&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Acting Schools</td>
            <td>319</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=9&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Make-up Artists</td>
            <td>154</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=10&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Theaters</td>
            <td>312</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=11&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Organizations</td>
            <td>65</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=12&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Dance</td>
            <td>483</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=13&state=">View the list</a></td>
        </tr>
        <tr bgcolor="#eeeeee">
            <td>Links</td>
            <td>90</td>
            <td><a href="http://exploretalent.com/resources.php?action=1&res_type=14&state=">View the list</a></td>
        </tr>
    </table>

    <p> Add your information to our resources - EASY and FREE!</p>

    <p>Just send us an email to <a
            href="mailto:resources@exploretalent.com">resources@exploretalent.com</a></p>

    <p>Please include your contact
        information and the category.<br>Casting Directors - Save yourself time lining up proper candidates
        for your castings, <a href="http://exploretalent.com/join_cd.php">post your casting for FREE</a> <br>
        Talent Agents - Interested
        in representing our talent? - <a href="mailto:agents@exploretalent.com">Email us</a> your info and the talent
        you
        are
        interested in.
    </p>
</div>