<h1><a href="http://exploretalent.com/modeling-acting.html">Find Theatre Auditions - click here...</a></h1>
<div class="border_small">
    <p>You also find many
        resources for Theatre
        Auditions, Broadway, los angeles , small theatre, open auditions and playhouse
        auditions in our resources section.</p>

    <p>ExploreTalent
        submits Comp Cards and Zed Cards to many types of auditions but including
        Theater
        Auditions, Broadway theatre Auditions, los angeles theatre auditions,
        small theatre auditions, open theatre auditions and playhouse theatre
        auditions.</p>

    <p><a href="/join/flash">Join ExploreTalent for free</a>
    </p>
</div>