<h1>Find tryouts in your area!</h1>
<div class="border_small">
    <p>Many
        Casting Agents are auditioning shows, movies and commercials everyday.
        They need actors from all over the Country and with ExploreTalent’s resources
        for fresh audition, acting audition, movie audition, tryouts, modeling
        tryouts, open tryouts and acting audition casting agents lists you can
        get working faster.</p>

    <p><a href="/join/flash">Join ExploreTalent for free</a> to find the latest casting, fresh audition,
        acting audition, movie audition, tryouts, first time audition, open calls,
        casting calls & castings.
    </p>
</div>
