<?php echo $this->partial('partials/editimages.phtml', array(
    'title' => 'Acting & Modeling',
    'form'=>$this->form,
    'imagepath'=>$this->imagepath,
    'formImageSecond'=>$this->formImageSecond,
    'deleteimage'=>$this->deleteimage,
    'crop'=>'cropped_image_acting',
    'userid'=>$this->userid,
    'addgallery'=>$this->addgallery,
    'gallery'=>$this->gallery,
    'add_result'=>$this->add_result,
    'action_name'=>$this->action_name
));