<div class="social_right">
	<?php echo $this->partial('partials/pagename.phtml', array( 'info' => $this->info, 'auth'=>$this->auth)); ?>
    <?php echo $this->partial('partials/video.phtml',
        array(
             'title' => 'Acting & Modeling Videos',
             'videos'=>$this->videos,
             'userid'=>$this->userid,
             'action_name'=>$this->action_name
        )); ?>
</div>