<div class="social_right">
	<?php echo $this->partial('partials/pagename.phtml', array( 'info' => $this->info, 'auth'=>$this->auth)); ?>
    <?php echo $this->partial('partials/audio.phtml',
        array(
             'title' => 'Musician Audio',
             'audio'=>$this->audio,
             'userid'=>$this->userid,
             'talentname'=>$this->talentname,
             'action_name'=>$this->action_name
        )); ?>
</div>
