<?php
	$tf1 = $this->info->getTalentInfo1(); $talentInfo2 = $this->info->getTalentInfo2();
	$tm = (!empty($this->musicinfo)) ? $this->musicinfo[0] : $this->musicinfo;
?>
<?php echo $this->partial('partials/pagename.phtml', array( 'info' => $this->info, 'auth'=>$this->auth)); ?>
<?php if($tf1->getSex() != null && $tf1->getSex() != ''){$gender = $tf1->getSex();} ?>

<div class="social_right">

    <div>
        Age <?php echo $tf1->getTalentnum()->age; ?>,
	    <?php echo $gender; ?>,
        from <?php echo $talentInfo2 != null ? $talentInfo2->getCity1() : 'n/a'; ?>
    </div>
    <br>
    <div class="list_carousel border_tiny">
        <ul id="foo0"><div class="loading_ajax"><img src="<?php echo CDN_JS_CSS; ?>/graphics/loading.gif" alt="Loading"/>Loading...</div></ul>
        <div style="clear:both;"></div>
    </div>

    <h2>Musician Profile</h2>

    <?php echo $this->partial('partials/top_menu.phtml', array('profile'=>'static','a'=>'act','b'=>'','c'=>'','d'=>'','e'=>'','id'=>$this->info->getTalentnum(),'type'=>'musician')); ?>

	<div class="profile_details border_small">
        <div class="home_advice_green">General Info
            <?php if(LOGGEDIN && (USERID == $this->notme)){  ?>
                <a class="profile_details_edit" href="/profile/acting/edit/id/<?php echo $this->info->getTalentnum(); ?>" title="Edit Acting & Modeling Info">
                    <span class="edit_profiles"></span>
                </a>
                <?php } ?>
        </div>
		<table>
			<tr>
				<td>
					<span class="span_acting">Type</span>
					<span class="span_acting_second"><?php echo isset($tm) ? $tm->musictype2.', '.$tm->musictype3 : 'n/a';?></span>
				</td>
				<td>
					<span class="span_acting">Band Type</span>
					<span class="span_acting_second"><?php echo $tm->bandtype!=null ? $tm->bandtype : 'n/a';?></span>
				</td>
			</tr>
			<tr>
				<td>
					<span class="span_acting">Genre(s)</span>
					<span class="span_acting_second"><?php echo isset($tm) ? $tm->genre.', '.$tm->genre2.', '.$tm->genre3.', '.$tm->genre4 : 'n/a'; ?></span>
				</td>
				<td>
					<span class="span_acting">Years Experience</span>
					<span class="span_acting_second"><?php echo $tm->years_experience != null ? $tm->years_experience : 'n/a'; ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<span class="span_acting">Number of Gigs</span>
					<span class="span_acting_second"><?php echo $tm->number_of_gigs != null ? $tm->number_of_gigs : 'none'; ?></span>
				</td>
				<td>
					<span class="span_acting">Instruments</span>
					<span class="span_acting_second"><?php echo $tm->music_instruments!= null ? $tm->music_instruments : 'none'; ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<span class="span_acting">Band Name</span>
					<span class="span_acting_second"><?php echo $tm->band_name != null ? $tm->band_name : 'n/a'; ?></span>
				</td>
				<td>
					<span class="span_acting">Management</span>
					<span class="span_acting_second"><?php echo $tm->management != null ? $tm->management : 'n/a'; ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<span class="span_acting">Studio Musician</span>
					<span class="span_acting_second"><?php echo $tm->studio_musician != null ? $tm->studio_musician : 'n/a'; ?></span>
				</td>
				<td>
					<span class="span_acting">Record Label</span>
					<span class="span_acting_second"><?php echo $tm->record_label != null ? $tm->record_label : 'n/a'; ?></span>
				</td>
			</tr>
			<tr>
				<td>
					<span class="span_acting">Label Type</span>
					<span class="span_acting_second"><?php echo $tm->label_type != null ? $tm->label_type : 'n/a'; ?></span>
				</td>
				<td></td>
			</tr>
		</table>
	</div>

	<div class="border_small">
		<div class="home_advice_green">Musician Information</div>
		<p><?php echo isset($tm) ? $tm->des_1 : 'n/a'; ?></p>
	</div>
	<div class="border_small">
		<div class="home_advice_green">Influences</div>
		<p><?php echo isset($tm) ? $tm->major_influence : 'n/a'; ?></p>
	</div>

	<div class="border_small">
		<div class="home_advice_green">About Me</div>
		<p><?php echo $this->about; ?></p>
	</div>
		<div style="clear:both"></div>
	<div class="border_small">
        <div class="home_advice_green">Short Resume</div>
		<p><?php echo $this->resume; ?></p>
	</div>

</div>
<div id="general_talentnum" class="<?php echo $this->info->getTalentnum(); ?>"></div>