<div class="page_container border_small">
	<?php echo $this->messages; ?>
	<h2>LOGIN HERE</h2>
	<?php echo $this->form; ?>

	<div style="clear:both"></div>
	<br><br>
	<h2>ExploreTalent Media Kit</h2>
	<div class="media_kit">
		<a href="/about/media-kit" target="_blank"><img src="<?php echo CDN_JS_CSS; ?>/graphics/mediakit_pdf.png" /></a>
		<h3>PDF</h3>
		<p>This Download is a PDF file which can be viewed with Adobe Reader. Adobe Reader is known as the go to program for viewing PDF files and is available absolutely free. To download Adobe Reader please visit:
			<a href="http://get.adobe.com/reader" rel="nofollow" target="_blank" title="Download Adobe Reader">http://get.adobe.com/reader</a>
		</p>
	</div>
	<div style="clear:both;"></div>
</div>