<div class="footer_content">
	<div class="celebrity_advice">
		<ul class="success_ul box_shadow">
			<li class="under_success"><div class="success_title_celeb">Celebrity Advice</div></li>
			<li class="under_success"><a href="/industry/celebrities-exclusive-interviews"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice01.jpg" width="97" height="62" alt="Matt Damon Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/industry/celebrities-exclusive-interviews"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice02.jpg" width="97" height="62" alt="Piers Morgan Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/industry/celebrities-exclusive-interviews"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice03.jpg" width="97" height="62" alt="Akon Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/industry/celebrities-exclusive-interviews"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice04.jpg" width="97" height="62" alt="Joan Rivers Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/media/video/urban"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice05.jpg" width="97" height="62" alt="Ray-J Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/media/video/urban"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice06.jpg" width="97" height="62" alt="Snoop Bogg Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/media/video/urban"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice07.jpg" width="97" height="62" alt="Raymond Celebrity Advice"/></a></li>
			<li class="under_success"><a href="/industry/celebrities-exclusive-interviews"><img src="<?php echo CDN_JS_CSS; ?>/graphics/celebrityadvice08.jpg" width="97" height="62" alt="Dave Grohl Celebrity Advice"/></a></li>
		</ul>
	</div>
	<div class="footer_top">
		<div class="footer_div footer_one">
			<div class="footer_title"><span>Auditions &amp; Jobs</span></div>
            <div><a href="<?php echo $this->url(array(),'acting_route');?>"><span>Acting Auditions</span></a></div>
            <div><a href="<?php echo $this->url(array(),'modeling_route');?>"><span>Modeling Auditions</span></a></div>
            <div><a href="<?php echo $this->url(array(),'dance_route');?>"><span>Dance Auditions</span></a></div>
            <div><a href="<?php echo $this->url(array(),'music_route');?>"><span>Music Jobs</span></a></div>
            <div><a href="<?php echo $this->url(array(),'crew_route');?>"><span>Crew Jobs</span></a></div>
		</div>
		<div class="footer_div footer_three">
			<div class="footer_title"><span>Videos</span></div>
			<div><a href="/media/video/testimonials/"><span>Video Testimonials</span></a></div>
			<div><a href="/media/video/search"><span>More Videos</span></a></div>
			<div><a href="/media/hiphop-interviews"><span>Urban Artist Advice</span></a></div>
			<div><a href="/media/video/acting"><span>Acting Workshop</span></a></div>
			<div><a href="/media/video/urban"><span>Celebrity Videos</span></a></div>
			<div><a href="/media/video/search"><span>Member Video Search</span></a></div>
		</div>
		<div class="footer_div footer_five">
			<div class="footer_title"><span>Find Talent</span></div>
			<div><a href="/talents/index/models"><span>Search Models and Actors</span></a></div>
			<div><a href="/talents/index/musicians"><span>Search Musicians</span></a></div>
			<div><a href="/talents/index/featured"><span>Featured Talents</span></a></div>
			<div><a href="/talents/index/models"><span>Featured Contestants</span></a></div>
			<div><a href="/media/video/search"><span>Video Search</span></a></div>
		</div>
		<div class="footer_div footer_two">
			<div class="footer_title"><span>About Explore Talent</span></div>
			<div><a href="/about"><span>About Us</span></a></div>
			<div><a href="/about/faq"><span>FAQ</span></a></div>
			<div><a href="/affiliates"><span>Affiliates</span></a></div>
			<div><a href="/about/advertise"><span>Advertising with Us</span></a></div>
			<div><a href="/testimonials"><span>Testimonials</span></a></div>
		</div>
	</div>
</div>

<div style="clear: both;"></div>

<div class="footer_bottom_container">
	<div class="footer_bottom">
		<div class="footer_div_bottom">
			<div><a href="/about"><span>About ExploreTalent.com</span></a></div>
			<div><a href="/"><span>Home</span></a></div>
			<div><a href="/about/privacy"><span>Privacy Policy</span></a></div>
            <div><a href="<?php echo $this->url(array(),'acting_route');?>"><span>Acting Auditions</span></a></div>
			<div><a href="/about/disclaimer"><span>Terms of Use</span></a></div>
			<div><a href="/about/advertise"><span>Advertise</span></a></div>
			<div><a href="/about/advertise"><span>Become an Affiliate</span></a></div>
			<div><a href="/about/faq"><span>Contact Us</span></a></div>
			<div><a href="/about/disclaimer"><span>Disclaimer</span></a></div>
			<div><a href="/about/sitemap"><span>Site Map</span></a></div>
		</div><div style="clear: both;"></div>
	</div>
</div>
<div style="clear: both;"></div>

<div class="footer_text">
    <div>
	    <p>
	    <a href="/testimonials/awards">Success Story?</a> ExploreTalent is not an employment agent or modeling agency &amp; does not procure, get, promise employment, jobs or booking. <a href="/about/faq">Customer Service</a> (800) 598-7500
		Make ExploreTalent your home page Explore Talent only provides internet exposure, resources & tools for you to match your talent with Auditions & Casting. <a href="/about/agreement">User Agreement</a>
		</p>
			<br>
		<p>
		*All trademarks shown on this page are the property of their respective owners. Nothing here is meant to imply endorsement by or affiliation with the brands named. Brand names are
		used for the purposes of showing potential casting opportunities and reflecting brands that have/had <a href="http://exploretalent.com/articles?cat=17">Acting Auditions</a> and <a href="http://exploretalent.com/articles?cat=3">Modeling Auditions</a> or <a href="http://exploretalent.com/articles?cat=20">Dance Auditions</a> , <a href="http://exploretalent.com/articles?cat=6">Acting Jobs</a> and <a href="http://exploretalent.com/articles?cat=3">Music Jobs</a> posted on our site.
		</p>
			<br>
		<p>
		ExploreTalent.com is the worldwide leader in acting Modeling Auditions. We are offering thousands of casting calls and Auditions. Get more Casting, auditions resources and Talent Agents
		than all other sites combined. Spending hours and not finding the Acting Jobs & Modeling Jobs you need? Find Reality TV Shows Casting Calls the modeling auditions Acting Auditions,
		modeling jobs, acting jobs, all in one place. Stop spending hours searching for casting & auditions. Submit yourself to casting calls, auditions - Get a call when Casting directors wants you.
		Check us out on
		YouTube: <a href="http://www.youtube.com/user/ExploreTalent/" target="_blank">Explore Talent</a>;
		MySpace: <a href="http://www.myspace.com/exploretalent" target="_blank">Explore Talent</a>;
		FaceBook: <a href="https://www.facebook.com/ExploreTalent" target="_blank">Explore Talent</a>;
		Twitter: <a href="http://twitter.com/exploretalent" target="_blank">Explore Talent</a>;
		CrunchBase: <a href="https://www.facebook.com/castingcall" target="_blank">Explore Talent</a>;
		Blip.TV:<a href="http://blip.tv/exploretalent" target="_blank">Explore Talent</a>;
		CrunchBase: <a href="http://www.crunchbase.com/company/explore-talent" target="_blank">Explore Talent</a>.
		</p>
			<br>
<br>Top Profiles:
        <div class="top_profiles">
         <a href="/profile/social/social-info/id/3592263">Houston Ries |&nbsp;</a>
         <a href="/profile/social/social-info/id/4646752">Lisa Palermo |&nbsp;</a>
         <a href="/profile/social/social-info/id/5756982">Kevin Ashton |&nbsp;</a>
         <a href="/profile/social/social-info/id/6497759">Ryan Fagliarone |&nbsp;</a>
         <a href="/profile/social/social-info/id/2276232">Alicia Alligood |&nbsp;</a>
         <a href="/profile/social/social-info/id/1348872">Ariel Tweto |&nbsp;</a>
         <a href="/profile/social/social-info/id/6330928">Rhiannon Harp |&nbsp;</a>
         <a href="/profile/social/social-info/id/4597769">Makenzy Glover |&nbsp;</a>
         <a href="/profile/social/social-info/id/6418821">Becca Markle |&nbsp;</a>
         <a href="/profile/social/social-info/id/2508145">Courtney Stodden</a>
      </div>
      <div style="clear: both;"></div>
    </div>
</div>
<div style="clear: both;"></div>
<div class="footer_bottom_bottom">
	<div class="copyrignt">
		<p>&copy;  Copyright ExploreTalent.com  &reg;</p>
	</div>
	<div class="footlinks">
        	<ul>
            	<li><a href="https://www.verisign.com" target="_blank"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/verlfy_.gif" width="104" height="56" alt="VeriSign Truted" /></a></li>
                <li class="fotmar">
                	<a href="https://sealserver.trustkeeper.net/compliance/cert.php?code=w6o8pBlmFNOh4gUHKIFEuqnRHPZ9qj&amp;style=normal&amp;size=105x54&amp;language=en" target="_blank">
                		<img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/seal_image.png" width="78" height="40" alt="Trust Wave"/>
                	</a>
                </li>
                <li class="fotmar">
                	<a href="https://sealserver.trustkeeper.net/compliance/cert.php?code=w6o8pBlmFNOh4gUHKIFEuqnRHPZ9qj&amp;style=normal&amp;size=105x54&amp;language=en" target="_blank">
						<img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/cyber_source.jpg" width="97" height="40" alt="cyber source trusted" />
					</a>
                </li>
                <li class="fotmar"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/american_exp.jpg" alt="American Express" width="98" height="40" /></li>
                <li class="fotmar"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/master_card.jpg" alt="Master Card" width="85" height="40" /></li>
                <li class="fotmar"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/visa.jpg" alt="Visa" width="85" height="40" /></li>
                <li class="fotmar"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/paypal.jpg" alt="Paypal" width="108" height="40" /></li>
                <li class="fotmar"><a href="http://gmpg.org/xfn" target="_blank"><img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/xfn-btn.gif" width="80" height="15" alt="XFN Friendly" /></a></li>
                <li class="fotmar">
                	<a href="http://www.bbb.org/southern-nevada/business-reviews/talent-listing-service/explore-talent-in-las-vegas-nv-75944#bbblogo" target="_blank">
						<img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/cbbb-badge-horz.png" alt="Explore Talent, Talent Listing Service, Las Vegas, NV" width="125" height="42">
					</a>
                </li>
                <li class="fotmar">
                	<a href="http://www.bbb.org/southern-nevada/business-reviews/talent-listing-service/explore-talent-in-las-vegas-nv-75944#bbblogo" target="_blank">
						<img src="<?php echo CDN_JS_CSS; ?>/graphics/logos/cbbb-accred-a-plus.png" alt="Explore Talent, Talent Listing Service, Las Vegas, NV" width="42" height="42">
					</a>
                </li>
            </ul>
        </div>
</div>
<div style="clear: both;"></div>
<?php echo $this->partial('banner_ads.phtml'); ?>
<div class="not_ifications">
	<div id="notification_sent"         class="customNotify">Recomandation sent successfully!</div>
	<div id="job_saved"                 class="customNotify">Job Saved</div>
	<div id="notification_sent_error"   class="customNotify">There was an error! we will fix this asap.</div>
	<div id="interest_saved"            class="customNotify">Notification sent successfully</div>
	<div id="email_sent"                class="customNotify">Email sent successfully</div>
	<div id="field_removed"             class="customNotify">Field Removed</div>
	<div id="field_saved"               class="customNotify">Edit was successful!</div>
	<div id="messagedeleted"            class="customNotify">Message deleted successfully!</div>
	<div id="messageempty"              class="customNotify">Message is empty!</div>
	<div id="friendme"                  class="customNotify">Become Friend message sent!</div>
	<div id="fanme"                     class="customNotify">Become Fan message sent!</div>
	<div id="profileviews_removed"      class="customNotify">Notification Removed</div>
	<div id="addsuccess"                class="customNotify">Friend added successful.</div>
	<div id="denysuccess"               class="customNotify">Friend deny was successful.</div>
	<div id="compliment_sent"           class="customNotify">Compliment sent successfully!</div>
	<div id="vote_sent"                 class="customNotify">Vote sent successfully!</div>
	<div id="compliment_error"          class="customNotify">Already voted.</div>
	<div id="resend_email_notification" class="customNotify">Email Send Successfully</div>
	<div id="change_email_notification" class="customNotify">Email Changed Successfully</div>
</div>