<div class="profile_content border_small resources_title">Get Paid for Promoting Explore Talent</div>
<div class="resources_content border_small">
    <p>Explore Talent, the web's number one source for acting auditions, modeling
        auditions, and talent has become a part of the Commission Junction network.
        You can join Explore Talent's overwhelming success by partnering up with
        us as one of our valued affiliates. Once you sign up by clicking here,
        you can immediately begin earning cash.</p>
    <br>
    <p>We offer an awesome base commission rate of 15% and up to 18% for our
        top performers and $.50 per lead, and possibly more for top lead generators.</p>
    <br>
    <p>You wont find another advertiser in the CJ Network like Explore Talent.
        We have no rivals! We are the premier service for acting and modeling auditions
        serving aspiring stars all throughout the US.</p>
    <br>
    <p>It's simple and easy, just click on our link and apply to our program.
        Once you are accepted into our program setting up your site to begin earning
        commissions is simple. With your affiliate account, you will have access
        to self-generated links already containing your unique ID. Simply copy
        & paste the code for the link into your site's code and you are ready to
        sell.</p>
    <br>
    <p>We will also provide you with a monthly email detailing hot products,
        upcoming promotions, &amp; selling tips. Our affiliate team is dedicated to
        you and your performance.</p>
    <br>
    <a href="https://signup.cj.com/member/brandedPublisherSignUp.do?air_refmerchantid=1903378">Start Earning CASH TODAY</a>
    <br>
</div>