<div class="profile_content border_small resources_title">How To Use Your Casting Calendar</div>

<div class="resources_content border_small">
<p>Your casting calendar is one of the most effective tools on your ExploreTalent
    website. With your calendar, you can keep up-to-date on all the auditions
    ExploreTalent has submitted you for. This is also how you will learn about
    open call auditions, and self-response notifications - two very valuable
    submission notices for furthering your career. These types of notices will
    be clearly marked at the top of each submission. If no address, phone number,
    or instructions for response are provided, then you need do nothing. The
    casting director or photographer will call us when they wish to see you.</p>
</div>
<div class="resources_content border_small">
    <h4>How To Use Your Casting Calendar</h4>
    <p>Your casting calendar is one of the most effective tools on your ExploreTalent
        website. With your calendar, you can keep up-to-date on all the auditions
        ExploreTalent has submitted you for. This is also how you will learn about
        open call auditions, and self-response notifications - two very valuable
        submission notices for furthering your career. These types of notices will
        be clearly marked at the top of each submission. If no address, phone number,
        or instructions for response are provided, then you need do nothing. The
        casting director or photographer will call us when they wish to see you.</p>
    <h4>Accessing Your Calendar</h4>
    <p>After logging on to your personal webpage, type in your login and your
        password. This will take you directly to your calendar.</p>
    <h4>Reading Your Calendar</h4>
    <p>On a date that you were submitted for an audition you will see the word
        "Submission." This is to let you know that your image, either hard-copy
        or electronic, was submitted to a casting director for consideration. Click
        on the word "Submission" and you will get all the project information available.
        You'll get the name and type of project, union status, rate, and all roles
        that are being cast. If available, you'll also get audition dates, shoot
        dates, location, and production company information. There are three different
        types of auditions you will find on your calendar:</p>
    <p>Request Audition: Your image is submitted to a casting director for consideration.
        If they are interested in calling you in for an audition, they will contact
        us - requesting you - and we will contact you.</p>
    <p>Self-Response Notification: When you click on "Submission" you will get
        information about a project in the casting process. In this case you will
        receive an email or phone number to contact the casting office directly,
        should you be interested in the project. This will be clearly stated on
        the casting notice.</p>
    <p>Open Call: In this case, an address and time will be provided. You may
        participate in the audition merely by showing up at the appropriate place
        and time.</p>
    <h4>Updating Your Casting Categories</h4>
    <p>Click on the words "
        <?php if(LOGGEDIN){?>
        <a href="/notifications/index/castings-jobs-preferences/id/145198">Start Here</a>
        <?php } else{ ?>
        <a href="/join/flash">Start Here</a>
        <?php } ?>
        ." This will take you to a screen where you may choose all the different
        types of submissions you qualify for. When you do this, keep in mind factors
        such as union status - if you are not in Aftra or the Screen Actors Guild,
        do not click on union categories. An explanation of each category is available.
        Also, make sure that your three market cities are accurate. These are the
        areas in which submissions will be made for you.</p>
    <h4>View matched Roles</h4>
    <p>This is where you can see all the projects with a role that matched your
        criteria. If you were not submitted, it is because a piece of specific
        information was not found in your profile to link you to the project. In
        this case, review your talent information and fill in any missing information.</p>
    <p>You should get in the habit of viewing your casting calendar at least
        once a day. This will keep you up-to-date and make sure you do not miss
        any opportunities that require you to take a pro-active approach. Stay
        informed! Get Motivated! Be Successful!</p>
    </div>
    <div class="resources_content border_small">
        <h4>General FAQ'S Answered</h4>
        <p>Q) Why am I not provided with the contact information when I am looking
            up castings under view all castings? A) Pro Members: All notices that apply
            to your model information found on your Explore Talent web site are found
            in your casting calendar. If there is no contact information provided you
            would need to wait for the casting director to request for you personally
            and all necessary information will then be provided. A) Non Pro Members:
            View all castings can be viewed by all, contact information (if any) will
            be found on the personal casting calendar of our Pro Package members. Please
            call 800.598.7500 to discuss the benefits of the Pro Package membership!</p>
        <p>Q) Why does the address and phone number have "black x's" on the submissions
            on my calendar? Shouldn't I have that contact information? A) This information
            does not reflect where the audition will take place. This information is
            where the casting notice came from and does not apply to talent.</p>
        <p>Q) How do I know if you are really submitting me for roles? A) Each time
            our team of in-house booking and submissions reps submit you (a Pro Package
            member) to a casting, you'll appear, automatically, on the casting calendar,
            allowing you to constantly monitor our performance in real-time. To become
            a Pro Package member please call 800.598.7500.</p>
        <p>Q) How come when I go to the site I cannot view my proof sheets? A) There
            could be many reasons why you cannot view your proof sheets, please call
            Customer Service at 800.598.7500, as every situation is unique.</p>
        <p>Q) How come I have not received my business cards? A) Pro Members: There
            could be many reasons why you cannot view your business cards, please call
            Customer Service at 800.598.7500, as every situation is unique. A) Non
            Pro Members: This is a benefit with service, when a talent becomes a Pro
            Package member.</p>
        <p>Q) I thought I only signed up for one-month/3 months/6 months.... A) Services
            provided by Explore Talent, which includes the exposure to casting directors
            via submissions, are recurring and uninterrupted for the talents benefit
            unless otherwise notified. Meaning a cancellation request prior to the
            service renewal date.</p>
        <p>Q) How come I have not been called for auditions? A) A casting director's
            decision regarding who is called for auditions is their decision and their
            decision only. Please make sure your images are current and your profile
            is up to date.</p>
        <p>Q) Why can't I change my name or phone number or email? A) Primary contact
            information can only be changed by Customer Service which safeguards against
            accidental deletion. This information is how our Booking department reaches
            you for any audition.</p>
        <p>Q) How do I use the calendar? A) Pro Members: Each time our team of in-house
            booking and submissions reps submit you to a casting, it will appear, automatically,
            on the casting calendar, allowing you to constantly monitor our performance
            in real-time. The days that are marked "Submission" are the days that you
            were submitted for castings by us. If clicked on you can access the actual
            casting notice! A) Non Pro Members: Your casting calendar reflects each
            casting notice that your model information matches as a pre-selection.
            In order to be submitted for the notice you must be a Pro Package member.</p>
        <p>Q) What are the different types of submissions? A) 1. Digital submission
            is an online submission done by emailing your online profile. 2. Self-Response
            Notification submissions are when the casting director's contact information
            is provided to all matched talents. This is the opportunity to make the
            decision whether or not to be submitted to this particular casting. 3.
            Open call is an audition for matched talent!! Date, time and location are
            provided in the casting notice for Pro Package members.</p>
        <p>Q) How long before I get my first job? A) This question cannot be answered....
            work cannot be promised or guaranteed.</p>
        <p>Q) Why wasn't I submitted to this casting? A) If there is a casting found
            that matches all criteria and is not found on the calendar of a Pro Package
            member please call Customer Service right away for each notice is time
            sensitive.</p>
        <p>Q) Why don't I have any submissions on my calendar? A) There could be
            many reasons such as missing important information; please call Customer
            Service at 800.598.7500, as every situation is unique.</p>
        <p>Q) Why do I get e-mails/ calls saying I have a free account? I am a Pro
            Member. A) In most cases there is a double account, please call Customer
            Service to avoid any further contact as a free member.</p>
    </div>
    <div class="resources_content border_small">
        <h4>Pro-Package Submissions FAQ's Answered</h4>
        <p>THE DIFFERENT TYPES OF SUBMISISONS FOUND ON A PRO'S CALENDAR ARE:</p>
        <p>1) Digital submission is an online submission done by emailing your online
            profile. 2) Self-Response Notification submissions are when the casting
            director's contact information is provided to all matched talents. You
            will need to make the decision whether or not to submit yourself to this
            particular casting. 3) Open call is an audition for matched talent!! Date,
            time and location are provided in the casting notice for Pro Package members.</p>
        <p>Q: Why can't I submit myself to the castings I find in the View All Castings
            or Auditions? A: All notices that match the given model information will
            be found on your personal casting calendar, thanks to Explore's booking
            department! If a casting is found that is not on your personal casting
            calendar (and the submissions deadline has not passed) call customer service
            right away for each notice is time sensitive.</p>
        <p>Q: Why I haven't received any e-mails from Explore Talent notifying me
            of the submissions you are doing for me? A: The castings to which Explore
            Talent's Booking Department submits you to are found on your personal casting
            calendar!</p>
        <p>Q: Why is there no contact info for the submission on my calendar? A:
            This is pursuant to casting directors' requests, any information that Explore
            Talent can provide you will be found in each submission.</p>
        <p>Q: If there is a submission that is not on my calendar, how do I get submitted?
            A: If a casting is found that is not on your personal casting calendar
            (and the submissions deadline has not passed) please make sure your casting
            preferences and talent information are updated.</p>
        <p>Q: Why is there no contact info on the auditions page, I am a Pro Package
            member? A: All notices that match the given talent information, will be
            found on your personal casting calendar. Needed contact information for
            the casting director could be found when you click submit ( unless done
            automatically via e-mail).</p>
        <p>Q: Where is the audition, it gives the date but not the place? A: When
            you are chosen for an audition, and the location is not specified in the
            casting notice, you will be notified by either the casting director or
            Explore Talent's Booking Department.</p>
        <p>Q: Why do you give me the info so last minute? It was for today (the submission
            date). A: The notices are 'real time' and are posted as soon as Explore
            Talent's Booking Department receives them.</p>
        <p>Q: Why does it keep asking me to join every time I submit for a casting?
            A: If you are a paid pro member, it is possible that you have created a
            second free account, and you are now loged-in to the wrong (free) account.
            Please logout your free account, and login again with your paid Pro account.</p>
        <p>Q: How come there are submissions on my calendar from the past? A: This
            if for the talents reference to gauge their marketability in the entertainment
            industry</p>
    </div>
    <div class="resources_content border_small">
        <h4>Submissions FAQ's for Non-Pro Package Memebers</h4>
        <p>Q: Why can't I submit myself to the castings I find in the View All Castings
            or Auditions? A: All notices that match the given model information will
            be found on your personal casting calendar, however the exposure (submission)
            to these casting director is one of the many benefits of becoming a Pro-Package
            member! Please call our New Talent Department at 800.598.7500 for details!</p>
        <p>Q: Why is there no contact info for the submission on my calendar? A:
            As a non-Pro-Package Member notices found on your personal casting calendar
            are Pre-Submissions...To receive any offered contact information or the needed
            exposure for this particular casting you must become a Pro-Package Member!
            Please call our New Talent Department at 800.598.7500 for details!</p>
        <p>Q: Where is the audition, it gives the date but not the place? A: As a
            non-Pro-Package Member notices found on your personal casting calendar
            are Pre-Submissions...To receive any offered contact information or the needed
            exposure for this particular casting you must become a Pro-Package Member!
            Please call our New Talent Department at 800.598.7500 for details!</p>
        <p>Q: Why does it keep asking me to join every time I submit for a casting
            or it says error? A: The View All Castings or Auditions lists are available
            to view, if an email is entered at the bottom a new or second account will
            be created. Please view your casting calendar for all matched Pre-Submissions!
            In order to be submitted you must become a Pro Package Member, Please call
            our New Talent Department at 800.598.7500 for details!</p>
        <p>Q: When viewing my calendar, how come the notice has little black x's?
            A: The black x's are found in place of where the casting notice originated
            from and is not apply to the audition or it's location.</p>
        <p>Q: How come there are submissions on my calendar from the past? A: This
            if for the talents reference to gauge their marketability in the entertainment
            industry.</p>
    </div>