<div class="profile_content border_small resources_title">Explore Talent Disclaimer</div>
<div class="resources_content border_small">
    <p>Understand that ExploreTalent ("ET") is an online talent database. ET
        is not an employment agency, casting agent, agency, manager, producer or
        a production company. ET does not procure, get, gain or retain employment,
        jobs, bookings or castings for our clients. ET does not represent the clients
        or guarantee any amount of income, jobs or employment from the use of this
        site.</p>
    <br>
    <p>It is ET's belief that the client or member is the only one person or
        entity that can successfully, gain, get, procure or retain a job, employment,
        booking or casting.</p>
    <br>
    <p>The submission and booking service is a free service provided to all ET
        members paying for the following: web hosting, sub domain, own web site,
        fully featured email, SMS messaging service, , top entry in ET's own talent
        search, search engine listing, photo gallery, access to premium resources
        and talent matching tools. Paying members' access to casting database and
        submission services are considered a convenience for talent who wants to
        spend more time on their career other than searching the net for possible
        legitimate casting calls.</p>
    <br>
    <p>ET does not offer advice, managerial directions, or opinions on any casting,
        job, engagement or audition. ET is merely messaging your headshot or comp
        card, like any resume, free of charge as requested by you. ET believes
        that the head-shot and comp cards, supplied by you to us, are equivalent
        to any resume.</p>
    <br>
    <p>ET does not print, reproduce or produce any type of images, film or digital,
        for the reason of selling or reselling photography. ET does not nor has
        it ever been a photographer or photographer studio. ET is not a print or
        graphics lab. ET does not sell hard copy or copies of images such as headshots,
        ZED / Comp cards, modeling or acting portfolios or the photos contained
        therein</p>
    <br>
    <p>The information in the database and forums are provided by ET members.
        ET does not warrant the accuracy and validity of any information provided,
        nor does it guarantee the quality of our members work. Members may include:
        talent agencies, casting-directors, acting schools, photographers, producers,
        promoters, actors, models, and all others relating to the entertainment
        industry. The purpose of this website is to help members make appropriate
        connections in the entertainment industry. Anyone who chooses to view and
        or make use of ET, for any reason, accepts full responsibility for any
        negative experiences that may occur.</p>
    <br>
    <p>You also agree to indemnify and hold harmless ET, affiliated companies
        and all of their respective officers, directors, agents, and employees
        from and against any and all actions, claims, demands, losses, damages,
        or causes of action by any third party arising from any claims to or against
        ET.</p>
    <br>
    <p>Any information, pictures, resumes, etc. submitted to ET, become property
        of ET, and will not be returned. Some information contained on the site
        is intended for entertainment purposes and the views and opinions expressed
        therein are not necessarily those of ET.</p>
    <br>
    <p>You may receive a password and account designation upon completing the
        Service's registration process. You are responsible for maintaining the
        confidentiality of the password and account, and are fully responsible
        for all activities that occur under your password or account. You agree
        to (a) immediately notify ET of any unauthorized use of your password or
        account or any other breach of security, and (b) ensure that you exit from
        your account at the end of each session. ET cannot and will not be liable
        for any loss or damage arising from unauthorized use of your username and/or
        password. Any fraudulent, abusive, or otherwise illegal activity may be
        grounds for termination of your account, at ET's sole discretion, and ET
        will refer you to appropriate law enforcement agencies.</p>
    <br>
    <p>You acknowledge and agree that all content and materials available on
        this site are protected by copyrights, trademarks, service marks, patents,
        trade secrets, or other proprietary rights and laws. Except as expressly
        authorized by ET, you agree not to sell, copy, reproduce, transmit, publicly
        display, publicly perform, publish, adapt, edit, license, rent, modify,
        distribute, or create derivative works from such materials or content.
        Systematic retrieval of data or other content from this site to create
        or compile, directly or indirectly, a collection, compilation, database
        or directory without written permission from ET is prohibited. In addition,
        use of the content or materials for any purpose not expressly permitted
        in our Talent Disclaimer or Terms of Use is strictly prohibited.</p>
    <br>
    <p>All Materials, Software, Information, services, and products, available
        through this site are provided as is and available for your use. The content
        is without warranties of any kind implied or express.</p>
</div>