<img src="<?php echo CDN_JS_CSS; ?>/graphics/billboards/homepagebanners_790x260_whats_new_inner.jpg" alt="" />
<br>
<br>
	<h1>Welcome to the new ExploreTalent website</h1>
<div class="resources_content border_small">
	<div class="home_advice">ExploreTalent</div><br>
	<p>We at ExploreTalent are dedicated to making your experience even better. We have been hard at work adding new features and improving the website just for you!</p>
	<p>Our goal is to give you easy access to all of our features and to help you better utilize ExploreTalent to get more auditions, book more jobs, and expand your network.</p>
	<p>We hope that you will love the site even more than before!</p>
	<p>Best regards,</p>
	<p>The ExploreTalent Team</p>
</div>

	<h1>So what’s new at ExploreTalent.com?</h1>
<div class="resources_content border_small">
	<div class="home_advice">New slick design</div><br>
	<p>We changed the look of the site to make it easier to find all of our  great features.</p>
	<p>ExploreTalent.com has a lot of features and tools. Now they are faster to locate and easier to use!</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">Multiple Profiles for all your talents</div><br>
	<p>Some of our members told us about other talents or skills they have, and after careful consideration about how we can help them we came up with a great solution. We can give them more Profiles! Every member can have a profile for each talent or skill they have, all under their Main Profile. This means you can add experience, pictures, videos and MP3s to every one of your profiles. You can meet and network with other people with the same talents as you. So, even if your talents are in sports, science, or juggling - you can have a profile for every one!</p>
	<p>This will increase the number of castings you match with, and give you a chance to show off your special skills.</p>
	<p>We know every talent is unique and everybody wants a chance to show why they are the best candidate.</p>
	<p>So now you have a prefect tool that allows you to do just that!</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">Add Interests to your profile</div><br>
	<p>Sometimes it is difficult to describe yourself using only your skills.</p>
	<p>So we decided to give you another tool. Interests! Once you add them to your profile you can meet and interact with other talents who share your same interests, and expand your social network!</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">Activities page</div><br>
	<p>Want to see what your friends on Explore Talent.com are up to? Just click on the Activity Feed link under “My Profile” and you will see who has uploaded new images and videos, who has stories or tips to share, and more!</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">Quick messaging and posting</div><br>
	<p>Using the activity feed you can post comments, write on another talent’s activity page and share what is on your mind!</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">New Easy Menu Options</div><br>
	<p>Need to order business cards? Want to see your upcoming auditions? We put all your favorite links under your profile menu so you can access them quickly and easily anytime you want.</p>
</div>

<div class="resources_content border_small">
	<div class="home_advice">We hope you love using our new site as much as we do! </div><br>
	<p>Good luck!!!!</p>
	<p><a href="/bugs">Report a bug</a></p>
</div>
