<div class="profile_content border_small resources_title">Frequently Asked Questions</div>
<p>If you can't find an answer to your question in our FAQ, please contact
    our <a href="/about/help">Customer Service Department</a> direct at Help or by phone at (800) 598-7500.</p>
<br>

<div class="border_small">
    <ul>
        <li><a href="#one">Username and Password</a></li>
        <li><a href="#two">Photo Upload</a></li>
        <li><a href="#three">Upload General Profile Picture</a></li>
        <li><a href="#four">Your Picture Has Been Reviewed</a></li>
        <li><a href="#five">Upload Videos</a></li>
        <li><a href="#six">How to view my submissions</a></li>
        <li><a href="#seven">Adding images or videos to the Activities pannel</a></li>
        <li><a href="#eight">Upload Main Profile Pictures</a></li>
        <li><a href="#nine">Your Explore Talent Website</a></li>
        <li><a href="#ten">Casting Calendar</a></li>
        <li><a href="#eleven">Payment Plans</a></li>
        <li><a href="#twelve">Account Status</a></li>
        <li><a href="#thirteen">Contact Us</a></li>
    </ul>
</div>

<div id="one" class="resources_content border_small">
    <div class="home_advice">Username and Password</div><br>
    <p>To request your username and password, click on the following link:
        <a href="/about/help">Password Help</a>.</p>
    <p>**Please note that it may take some time to receive your username and
        password, depending on the time of day. If you do not receive an email
        from us with your username and password, please email our Customer Service
        Department here:
        <a href="/about/help">Help</a>.</p>
    <p>Additionally, you should ensure that you are not SPAM filtering us--thereby
        discarding important emails. Check your "Bulk/Junk Mail" folder to be sure
        any messages we sent weren't accidentally mistaken for junk mail. To
        insure that all of our emails are going through, please follow these instructions
        to unblock email accounts.
        <a href="/about/help">Email Help</a>.</p>
    <p>Still having trouble logging on?</p>
    <p>Please make sure that you don't have the CAPS LOCK key on. User names
        are case-sensitive. Check to make sure the name you entered is the same
        case-sensitive name you entered when you registered.</p>
    <br>
</div>

<div id="two" class="resources_content border_small">
    <div class="home_advice">Photo Upload</div><br>
    <p>Before you upload your pictures:</p>
    <p>If possible, please select professional headshots and poses for your primary
        and secondary images. The next best thing is to use a good quality headshot
        photo of yourself.</p>
    <p>Do not use web cam photos as the quality is poor.</p>
    <p>Do not use group photos (the casting director won’t know which person you are)</p>
    <p>Do not use photos in which your face is obstructed by an object (hats,
        hands, sunglasses, etc.)</p>
    <p>Do not use photos containing nudity of any kind.</p>
    <p>Do not use photos containing animals.</p>
    <p>Make sure that you use a current photo.</p>
    <br>
    <p>If you have no way of scanning or transferring photos to a digital format,
        you can mail them to:</p>
    <p>Explore Talent</p>
    <p>3395 S. Jones Blvd #15</p>
    <p>Las Vegas, NV 89146</p>
    <br>
    <p>**Allow 2 weeks for the pictures to be placed on your website. You will
        receive an email when your image is approved and posted.</p>
    <p>**Please keep in mind that your pictures are reviewed and approved by
        our photography staff and screened for content and quality. Upon approval,
        your pictures will be immediately posted to your website.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="three" class="resources_content border_small">
    <div class="home_advice">Upload General Profile Picture</div><br>

    <p>Log into your ET profile and go to your profile homepage.</p>
    <p>Once at your ET profile homepage you will see your current or default profile image.
        From the Et profile homepage you will notice a PENCIL ICON on your current image.
        Click the PENCIL ICON and you will be taken to a screen that says “Upload Main Social Picture”.</p>
    <p>Click the button that says “Choose File” below the Upload Main Picture heading.
        Once you click “choose file” you will be prompted with a popup to choose the file you want as your profile image.</p>
    <p>(PLEASE NOTE THAT WE ONLY ALLOW THE FOLLOWING IMAGE FORMATS: gif,jpg,jpeg and png) and that (THE MAXIMUM IMAGE SIZE IS: 10M)</p>
    <p>Click on the image you want to set as your profile image and select open.  Once you click open the pop up box will disappear.
        Now click on the button that says “Submit”.</p>
    <p>Once you have clicked “Submit” your image will upload and now you can crop your image.
        Using the cropping tool provide crop your image so that your body is in the picture previewer.
        You want your face to be as clear as possible.</p>
    <p>Once your satisfied with your image click on the “crop image button”
        and now your profile image will be changed. </p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="four" class="resources_content border_small">
    <div class="home_advice">Your Picture Has Been Reviewed</div><br>
    <p>If you received an email labeled "Your Picture Has Been Reviewed," it
        is referring to an image that you uploaded and was rejected for one reason
        or another. More than likely the image was corrupted. This means that the
        upload may have timed out before the image was sent to us and therefore
        is not viewable.</p>
    <br>
    <p>Other reasons for rejection:</p>
    <p>Photo contains nudity.</p>
    <p>Photo may be too small or incorrectly cropped.</p>
    <p>Photo contains people other than yourself.</p>
    <p>Photo is irrelevant, of someone else, or is an inanimate object.</p>
    <p>After receiving this kind of email, please select a new photo/headshot
        for your website. Click on the link below for further assistance with uploading
        your picture.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="five" class="resources_content border_small">
    <div class="home_advice">Upload Videos</div><br>

    <p>Log into your ET profile and go to your profile homepage.</p>
    <p>Once at your ET profile homepage choose from your available Talent Profiles.
        Once you have chosen your talent profile that you would like to upload a video to click on the PENCIL ICON next to the “VIDEOS” heading.
    </p>
    <p>Now that you have clicked on the PENCIL ICON you will be taken to a screen that allows you to upload your video
        to that specific Talent Profile. Make sure you give your video a title.</p>
    <p>Please note that your video will be available
        after a few minutes.If you need to upload another video to a different talent profile follow the same steps as above.
        PLEASE NOTE THAT WE ONLY ALLOW THE FOLLOWING VIDEO TYPES: (AVI,MOV,WMV,MPEG AND FLV)</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="six" class="resources_content border_small">
    <div class="home_advice">How to view my submissions</div><br>

    <p>Log into your ET profile and go to your profile homepage.</p>
    <p>Once at your ET profile homepage scroll the page down and on the left hand side you will see “My Submissions” labeled in green text.
        Click on the My submissions and you will be taken to a page where you can view castings you have submitted to.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="seven" class="resources_content border_small">
    <div class="home_advice">Adding images or videos to the Activities pannel</div><br>

    <p>Log into your ET profile and go to your profile homepage.</p>
    <p>Once at your ET profile homepage click the headline that is labeled “Activities”.
        Once you have clicked on “Activities” you will notice 3 icons will appear to the right of the input text box for updating your status.
        Choose from the 3 icons depending on what you want to insert into your activity feed.</p>
    <p>Once you click on the icon a popup window will appear and let you insert the image or video you have chosen along with
        examples of how to insert the image or video into the activity feed. After you  have clicked on “add image” or “add video”
        you will notice text has now been placed within the status update box.
    <p>From here you can add text such as funny sayings,captions.etc..
        Once you are satisfied with your text click on “share” and now your image or video is posted into your activity feed.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="eight" class="resources_content border_small">
    <div class="home_advice">Upload Acting & Modeling, Musician and Dance Main Profile Picture</div><br>

    <p>Log into your ET profile and go to your profile homepage.</p>

    <p> From the Et profile homepage you will notice a PENCIL ICON next to the “Pictures” heading.
        Click the PENCIL ICON and you will be taken to a screen that will say “Upload Main Acting & Modeling,Musician or Dance Picture”.</p>
    <p>Click the button that says “Choose File” below the Upload Main Picture heading. Once you click “choose file”
        you will be prompted with a popup to choose the file you want as your profile image.</p>
    <p>(PLEASE NOTE THAT WE ONLY ALLOW THE FOLLOWING IMAGE FORMATS: gif,jpg,jpeg and png) and that (THE MAXIMUM IMAGE SIZE IS: 10M)
        Choose the image you want to set as your profile image and select “OPEN”.  Once you click OPEN the pop up box will disappear.
        Now click on the button that says SUBMIT.</p>
    <p>Once you have clicked “Submit” your image will upload and now you can crop your image.
        Using the cropping tool provide crop your image so that your body is in the picture previewer.</p>
    <p>You want your face to be as clear as possible. Once you’re satisfied with your image click on the “crop image button”
        and now your profile image will be changed. </p>
    <br>
    <p><a href="#top">Top</a></p>
</div>

<div id="nine" class="resources_content border_small">
    <div class="home_advice">Your Explore Talent Website</div><br>
    <p>Your Explore Talent web address is http://yourloginname.exploretalent.com</p>
    <br>
    <p>To email your web profile to someone, follow the steps below:</p>
    <br>
    <p>1. Log into your account.</p>
    <p>2. Click on "My Email."</p>
    <p>3. Click on "Email Profile" which will take you to a new web page allowing
        you to email someone your web profile.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>
<div id="ten" class="resources_content border_small">
    <div class="home_advice">Casting Calendar</div><br>
    <p>Your casting calendar is one of the most effective tools on your Explore
        Talent website. As a Pro Member, you can use your calendar to keep up-to-date
        on all the auditions Explore Talent has submitted you for.</p>
    <br>
    <p>The calendar is also how you will view audition notices for open calls
        and submit your profile to casting directors. Open audition notices will
        be clearly marked at the top of each submission. If no address, phone number,
        or instruction for response are provided, then you do not need to do anything.
        The casting director or photographer will call you when they wish to see
        you or to schedule your audition.</p>
    <br>
    <p>The auditions listed on your casting calendar notifies you that your preferences/model
        information matches a casting or project on file with us. (NOTE: You must
        be a Pro Member to get any further information about the casting or project.)</p>
    <br>
    <p>(Pro Members) On a date that you were submitted for an audition, you will
        see the word "Submission". This is to let you know that your image, either
        hard copy or electronic, was submitted to a casting director for consideration.</p>
    <br>
    <p>Click on the word 'Submission' and you will get all the project information
        available to you including the name and type of project, union status,
        rate and all roles that are being cast. When applicable, you'll also get
        audition dates, shoot dates, location, and production company information.</p>
    <br>
    <p>There are three different types of auditions you will find on your calendar:
        Request Audition -- Your profile is submitted to a casting director for
        consideration. If they are interested in calling you for an audition, they
        will contact us, requesting you. From there, we will contact you.</p>
    <br>
    <p>Self-Response Notification -- When you click on "Submission" you will
        get information about a project in the casting process. In this case, you
        will receive an email address or phone number to contact the casting office
        directly, should you be interested in the project. This will be clearly
        stated on the casting notice.</p>
    <br>
    <p>Open Call -- An address and time will be provided for you to attend the
        audition. You may participate in the audition merely by showing up at the
        appropriate place and time, as guided. Each time our team of in-house booking
        and submission representatives submit you to a casting, it appears automatically
        on your casting calendar. This allows you to constantly monitor your profile
        performance in real-time. The days that are marked "Submission" are the
        days that you were submitted for castings by us.</p>
    <br>
    <p>NOTE: If you are a Pro Member and do not have any submissions on your
        calendar or you have not been automatically matched with a casting that
        matches your model information, verify that your profile contains all of
        your information, including: age, height, gender, etc. Also, make sure
        your casting preferences are updated, including the 3 markets that you
        are willing to travel to. You may contact the Customer Service Department
        at (800) 598-7500 for assistance.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>
<div id="eleven" class="resources_content border_small">
    <div class="home_advice">Payment Plans</div><br>
    <p>ExploreTalent, provides access to an extensive 40,000+ Auditions data
        bases and the exposure to casting directors via submissions, charges for
        Services provided, are recurring for the purpose of providing an uninterrupted
        service for member's benefit. In order to cancel your account, you must
        submit a cancellation request prior to your next service automatic renewal
        date.</p>
    <br>
    <p>We offer the following Auto-Renewal plans: 1 month, 3 months, 6 months,
        12 months for as low as $16.63/month</p>
    <br>
    <p>1 month Pro Subscription - $29.95/month - After 7 days free</p>
    <br>
    <p>3 month Pro Subscription - $23.30/month - After 7 days free (Billed in
        1 prepayment of $69.90)</p>
    <p>6 month Pro Subscription - $19.98/month - After 7 days free (Billed in
        1 prepayment of $119.94)</p>
    <p>12 month Pro Subscription - $16.63/month - After 7 days free (Billed in
        1 prepayment of $199.50)</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>
<div id="twelve" class="resources_content border_small">
    <div class="home_advice">Account Status</div><br>
    <p>In order to cancel your account with ExploreTalent on-line, please click
        <a href="<?php echo STAFF_DOMAIN; ?>/cancel.php">Cancel Account.</a></p>
    <br>
    <p>You may also cancel at anytime during business hours 10am to 6pm Pacific
        Time Monday - Friday by calling (800) 598-7500. Ensure that you speak to
        a Customer Service Representative, versus leaving a message, as it is not
        always clear who you are through the message.</p>
    <br>
    <p><a href="#top">Top</a></p>
</div>
<div id="thirteen" class="resources_content border_small">
	<div class="home_advice">Contact Us</div><br>
    <p><a class="gbutton gbig" href="/requests/index/contact">If you still have any questions Click Here to contact customer service.</a></p>
	<br>
    <p><a href="#top">Top</a></p>
</div>