<div class="profile_content border_small resources_title"> Is Explore Talent A Scam? </div>

<div class="resources_content border_small">
	<p>
	Is Explore Talent A Scam? Let's clear the air : We made our site to fight talent exploitation and help give each talent a genuine opportunity to become a star. 
	Explore Talent is forcibly clearing the industry of fake firms who victimize talent by selling fake guarantees of their dreams turning out to be true. 
	"Be in the footage within 30 days", "Become a star overnight", Have your picture in next month's fashion mag, are only one or two or the fake claims put forward by our fake rivals.
	</p>
		<br>
	<p>
	How We Help Explore Talent supports victims in the Acting and Modeling business who have been ripped by off offering to compensate in services a close value you were swindled. 
	Explore Talent's monthly service is $29.95 ; so for each occurrence of this amount that you were conned, you can receive a free a month with Explore Talent.
	</p> 
		<br>
	<p>
	To get the free service, just supply us with a card or account statement showing the amount you were scammed. No billing data is wanted to claim this free service. 
	Now, is Explore Talent swindle ; we think not! Explore Talent is the world's largest talent net site with over 6.7 million members. 
	There are more than fifty thousand auditions and job openings listed monthly, twenty-five times the amount of any other site, with thousands of our capabilities getting auditions and 
	landing roles. 
	</p>
		<br>
	<p>
	No other programme even comes close to the price that Explore Talent provides its members. So is Explore Talent a Scam? 
	The answer : definitely not. It's tough to satisfy 5,000,000 members, but Explore Talent tries to delight, and is an A+ BBB member. 
	We are an A+ standing member with the Better Business Bureau as we actively work to satisfy all our buyers. Explore Talent isn't a Scam..
	</p>
</div>

<div class="profile_content border_small resources_title"> Featured Testimonials </div>

<div class="resources_content border_small">
	<div class="scam_video">
		<div class="scam_one">
			<img src="http://www.exploretalent.com/images/kidsignup/kid2.jpg" />
			<div>
				<a href="/testimonials">Read More..</a>
			</div>
		</div>
		<h3>Landed role in a film within 2 weeks!</h3>
		<p>AJ Heiss got a Bounty Paper Towels commercial!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="http://www.exploretalent.com/images/kidsignup/kid2.jpg" />
			<div>
				<a href="/testimonials">Read More..</a>
			</div>
		</div>
		<h3>AJ Heiss got a Bounty Paper Towels commercial!</h3>
		<p>Just wanted to say "Thank You" for getting AJ his last job. He just did a commercial for Bounty Paper Towels. </p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="http://www.exploretalent.com/images/kidsignup/kid1.jpg" />
			<div>
				<a href="/testimonials">Read More..</a>
			</div>
		</div>
		<h3>FIRST audition, FIRST booking...</h3>
		<p>We would like to give a huge thank you to the folks at Explore Talent for all you do.</p>
	</div>
</div>