<h1>Customer service contact form</h1>

<div class="border_small">
	<?php echo $this->form; ?>
	<div style="clear: both;"></div>
</div>

<div class="border_small">
	<p>Address:</p>
	<ul class="bullets">
		<li>
			<p>ExploreTalent.com Customer Service</p>
			<p>3395 S Jones Blvd, Suite 15</p>
			<p>Las Vegas, NV 89146</p>
		</li>
		<li>
			<p>Telephone: (800) 598-7500</p>
			<p>Office hours: M-F 10am-6pm PST</p>
			<p>Fax Number: (702) 997 5200</p>
		</li>
	</ul>
	<h3><a href="/about/faq">Before you e-mail us please read our FAQ's!</a></h3>
	<p>Most questions are answered in our FAQ's, please reference before emaling to avoid delay</p>
</div>