<h1>How To Earn Points</h1>

<p>At Explore Talent you can earn ET Points by simply participating in our community. With your earned ET Points you can purchase many items at our ET Store.</p>
<br>
<div class="border_small">
    <h2>Here's how to build more points:</h2>
    <p>Create a free Profile - 10 ET Points</p>
    <p>Upload your first picture - 20 ET Points</p>
    <p>Complete your profile - up to 100 ET Points</p>
    <p>Upgrade to Pro Membership - up to 1200 ET Points</p>
    <p>Invite your friends to join ExploreTalent - 20 ET Points for every friend that joins</p>
    <p>Add ExploreTalent friends - 2 ET Points for every 10 friends</p>
    <p>Enter a contest - 50 ET Points</p>
    <p>Get friends to vote for you in contests - 2 ET Points for every vote</p>
    <p>Vote for your friends in contests - 2 ET Points for every vote</p>
    <p>Become a ET Star Researcher - 25 ET Points per survey</p>
    <br>
    <p>Disclaimer: Cheating will result in forfeit of all points</p>
    <p>Read the <a style="display: inline;" href="/about/disclaimer">Terms &amp; Conditions</a></p>
    <?php if(LOGGEDIN){ ?>
    <br>
    <a href="/points/index/history" class="gbutton gbig" title="<?php echo $this->friend; ?>">View ET Points</a>
    <a href="/store" class="gbutton gbig" title="<?php echo $this->friend; ?>">View ET Store</a>
    <?php } ?>
</div>

<div class="border_small">
    <h2>Share Your Contest Entry With your Friends</h2>
    <p>Invite as many friends as possible to come and vote for you.</p>
    <p>You must have at least 20 votes to be considered.</p>
    <p>Top contestants will be verified to have valid votes.</p>
    <!-- AddThis Button BEGIN -->
    <div class="addthis_toolboxx addthis_default_style addthis_32x32_style">
	    <a class="addthis_button_preferred_1"></a>
	    <a class="addthis_button_preferred_2"></a>
	    <a class="addthis_button_preferred_3"></a>
	    <a class="addthis_button_preferred_4"></a>
	    <a class="addthis_button_compact"></a>
	    <a class="addthis_counter addthis_bubble_style"></a>
    </div>
    <script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4efa0cbe5c320b78"></script>
    <!-- AddThis Button END -->
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <h2>How to Promote Your ET Contest entry on Twitter:</h2>
    <p>Update your Tweetbox frequently and include the link to your entry so that your followers can view your entry and help you win.</p>
    <p>Encourage your followers to ReTweet (RT) your entry</p>
    <p>Tell your followers about the contest so that they can enter and then vote for each other!</p>
</div>

<div class="border_small">
    <h2>How to Promote Your ET Contest entry on Facebook:</h2>
    <p>We know you want to win, so here are a few pointers on how to get the word out about your contest entry!</p>
    <p>Write a note &amp; tag your friends in it!</p>
    <p>Ask your friends to share your entry with their friends! Remember, the more ratings you have the better your chance of winning!</p>
</div>

<div class="border_small">
    <h2>How to Promote Your ET Contest entry on Myspace:</h2>
    <p>We know you want to win, so here are a few pointers on how to get the word out about your contest entry!</p>
    <p>Update your status and include a link to your entry. Encourage your friends to visit and vote for you.</p>
    <p>Post a blog, post in forums and groups that you are a part of.</p>
    <p>Ask your friends to share your entry with their friends! Remember, the more ratings you have, the better your chance of winning!</p>
</div>

<div class="border_small">
    <h2>How to Promote Your ET Contest entry on Craigslist:</h2>
    <p>Post in various discussion forums by composing a new thread with all the details pertaining to the contest and where to go to view your contest entry.</p>
    <p>Post an ad in the community and encourage the community to visit and vote for you.</p>
</div>