<div class="profile_content border_small resources_title"> About Us </div>

<div class="resources_content border_small">
	<p>
	Since its debut in 2003, ExploreTalent.com has become the Internet's largest audition, job and casting call resource for actors, models, musicians, dancers, and production crew.
	Explore Talent's proprietary Cast Match technology is the most advanced entertainment-based technology of its kind. It matches a talent's attributes against tens of thousands of
	audition and job postings every day. Explore Talent's unique technology sends casting email alerts and posts auditions and jobs directly on talents' profiles, saving members hours
	of time from tedious searching. Explore Talent has proven to be the best possible destination for talents with well over 6.7 million members and over 60,000 auditions, castings,
	and production jobs listed - 40 times more postings than any other site!
	</p>
		<br>
	<p>
	Explore Talent is constantly working to find better ways to serve the best interest of its members. The Explore Talent team spends over 3,000 hours per week checking,
	sorting, and preparing casting information. Our dedicated full-time customer service reps and talent advisers are available by phone five days a week, providing the most
	personal service in the industry today. From the latest technology designed to connect the nation's top casting directors with member profiles, to its proprietary software
	designed to make the submission process as easy as possible, Explore Talent proudly offers the most cost-effective resource to aspiring and accomplished entertainers.
	</p>
		<br>
	<p>
	Explore Talent is committed to helping its members find work all across the globe. View our member <a href="/testimonials">Testimonials</a> and you'll see that Explore Talent's formula is extremely
	successful and saves members valuable time and money so they can find the success they deserve.
	</p>
		<br>
	<p>
	<a href="/join/flash">Join Now for $2 for the first 7 days!</a> Try our Pro Member services for 7 days for only $2 now and make your dreams happen!
	</p>
</div>

<div class="profile_content border_small resources_title"> What we have to offer: </div>

<div class="resources_content border_small">
	<h3>Personal Webpage</h3>
	<p>
	Have your own presence on the Internet and promote yourself across the globe! Your Explore Talent profile page will be your stage to the acting and modeling world.
	Casting directors, agents, photographers, prospective clients, friends, and family will gain instant access to your resume, headshot, and reel.
	</p>
		<br>
	<h3>Searchable Talent Database Listing</h3>
	<p>
	Exploretalent.com and its Talent search section is reviewed on a daily basis by casting directors, modeling and talent agents, production companies, and advertising agencies.
	Don't miss out on this great opportunity to be discovered. Many of our talent have booked their own jobs and enhanced their careers through ExploreTalent.com.
	</p>
		<br>
	<h3>Create & Post Your Resume using ExploreTalent.com's Resume Builder</h3>
	<p>
	A resume is an essential way to tell the world all about you. With Explore Talent you can easily create and post your resume with our resume builder.
	The resume builder can save you hours of time as it will guide you through the process of creating a professional resume designed to impress casting directors. Got a new gig to add?
	No problem! You can easily edit your resume online and always have the most up-to-date information readily available for agents to review.
	Using ExploreTalent.com's resume builder can also save you money as you won't need to reprint new copies every time you add an update.
	</p>
		<br>
	<h3>Immediately Email Your Headshot & Resume</h3>
	<p>
	Want to promote your talents across the Internet? Would you like to effortlessly submit yourself for production jobs and auditions?
	Don't just e-mail a headshot or waste time looking for files and attachments. ExploreTalent.com provides the easiest and fastest way for you to promote yourself online with
	an impressive submission that includes your resume and links to your online profile and reel.
	</p>
		<br>
	<h3>Upload Pictures</h3>
	<p>
	Got new photos and headshots? Just come back from a fashion shoot? As your experience grows you can easily upload, edit and change your photos as often as you like.
	</p>
		<br>
	<h3>Free Photo Scanning</h3>
	<p>
	Don't have digital images of yourself? No worries! Mail your photos to us and we will scan and post them for you for FREE.
	</p>
		<br>
	<h3>Access over 20,000 free Resources</h3>
	<p>
	Our online resource section has more than 20,000 listings for talent related services such as Agencies, Casting Directors, Photographers, Talent Managers, Coaches, Schools Studios,
	Make-up Artists, Print Shops, Organizations and more.
	</p>
		<br>
	<h3>Express Photo Approval</h3>
	<p>
	With a Pro Account, your photos will receive expedited processing for approval giving our Pro Members faster access to casting directors.
	</p>
		<br>
	<h3>Upload and Store Your Videos and Voiceovers</h3>
	<p>
	Want to impress agents even more? Post samples of your work or your personal reel on your unique ExploreTalent.com profile and showcase your talents!
	</p>
		<br>
	<h3>Access Thousands of Acting, Modeling, Musician, Dancing, and Crew Job Opportunities</h3>
	<p>
	As a Pro member, you can be your own agent and gain access to 1000s of opportunities nationwide. With your Pro Membership you can submit yourself directly to Casting Directors and
	Agents, and avoid paying an Agent if you book the gig, putting more money in your pocket!
	</p>
		<br>
	<h3>Matched Auditions</h3>
	<p>
	As a Pro Member, our team of in-house submission reps and proprietary technology will match you to castings and job postings that are right for you and display them on your
	Explore Talent profile for easy access. Our professional support team will even submit you to casting directors who've expressed an interest in you for no additional fee.
	It's as easy as 1, 2, 3!
	</p>
		<br>
	<h3>Fully Featured Webmail</h3>
	<p>
	All Pro Members receive their own e-mail address linked to their ExploreTalent.com website for easy career management.
	With 10 MB of storage, our Pro Member talents are able to send and receive large images and files often required in the entertainment industry.
	</p>
		<br>
	<h3>Submission to Search Engines - a $100 value!</h3>
	<p>
	FACT: 85% of all traffic to Web sites and 70% of all online purchases originate from a search engine like Google, Bing, Yahoo, or MSN. ExploreTalent.com helps
	Pro Members generate the visibility they need online by optimizing and submitting their ExploreTalent.com profile page to major search engines for no additional fee.
	</p>
		<br>
	<h3>100 Business Cards with Your Color Photo and Contact Information - an $80 value!</h3>
	<p>
	Want to be even more visible? Want to impress when you present yourself to new people or jobs? With your Pro Membership professional package you'll
	receive full color business cards featuring your photo, name, contact information and direct web site address. As an Explore Talent Pro Member you'll leave a
	memorable impression on the people you meet.
	</p>
		<br>
	<h3>Priority talent listing</h3>
	<p>
	All Pro member profiles appear on the top of the talent search so when Casting Directors or Agents search for talent, Pro Member profiles appear first.
	This higher visibility significantly increases a Pro Members chance to be contacted for auditions and jobs.
	</p>
		<br>
	<h3>Get SMS Audition Notifications Immediately Sent to Your Cell Phone - a $240 value!</h3>
	<p>
	Get SMS (Short Message Service or text) Messages sent to your cell phone - a $240 annual value! With the SMS feature, casting notices will be sent to your
	cell phone so you can be immediately notified when auditions are available for you.
	</p>
		<br>
	<p>
	<a href="">Click Here</a> to get your Explore Talent Pro Membership and get discovered now!
	</p>
</div>

<div class="profile_content border_small resources_title"> The Truth About Explore Talent </div>

<div class="resources_content border_small">
	<p> <a href="/about/scam">Is Explore Talent a Scam?</a> </p>
	<p> <a href="/about/genuine">Explore Talent Scam</a> </p>
	<p> <a href="/about/fraud">Is Explore Talent a Fraud?</a> </p>
	<p> <a href="/about/legit">Is Explore Talent Legit?</a> </p>
</div>

<div class="profile_content border_small resources_title"> Contact Information </div>

<div class="resources_content border_small">
	<p>Customer service</p>
	<p>Call us: (800) 598-7500 (M-F 10am-6pm PST)</p>
	<p>Fax Number: (702) 997 5200</p>

	<h3>Address:</h3>
	<p>Explore Talent</p>
	<p>3395 S. Jones Blvd #15</p>
	<p>Las Vegas, NV 89146</p>

	<p>Exploretalent.com <a style="display: inline;" href="/about/privacy">Privacy Policy</a> Check out our</p>
	<p>YouTube: <a style="display: inline;" href="http://www.youtube.com/exploretalent">Explore Talent</a></p>
	<p>MySpace: <a style="display: inline;" href="http://www.myspace.com/exploretalent">Explore Talent</a></p>
	<p>FaceBook: <a style="display: inline;" href="http://www.facebook.com/ExploreTalent">Explore Talent</a></p>

</div>

<div class="profile_content border_small resources_title"> More About Explore Talent </div>

<div class="resources_content border_small">

	<p>Explore Talent is the premiere online talent resource for acting, music, modeling and dance throughout the entertainment business.
	Explore Talent has the most advanced web-based software technology, benefiting members of Explore Talent by posting tens of thousands of auditions and job listings daily.</p>

	<h3>To learn more about Explore Talent, add us to your favorite network below:</h3>
	<p>Twitter: <a style="display: inline;" href="http://www.twitter.com/exploretalent">Explore Talent</a></p>
	<p>CrunchBase: <a style="display: inline;" href="http://www.crunchbase.com/company/explore-talent">Explore Talent</a></p>
	<p>YouTube: <a style="display: inline;" href="http://www.youtube.com/user/exploretalent">Explore Talent</a></p>
	<p>Myspace: <a style="display: inline;" href="http://www.myspace.com/exploretalent">Explore Talent</a></p>
	<p>Naymz: <a style="display: inline;" href="http://www.naymz.com/explore_talent_2581019">Explore Talent</a></p>

	<h3>For traffic statistics, Explore Talent can be found on the following sites:</h3>
	<p>Alexa: <a style="display: inline;" href="http://www.alexa.com/siteinfo/exploretalent.com">Explore Talent</a></p>
	<p>Cubestat: <a style="display: inline;" href="http://www.cubestat.com/www.exploretalent.com">Explore Talent</a></p>
	<p>SiteAnalytics: <a style="display: inline;" href="http://siteanalytics.compete.com/exploretalent.com/">Explore Talent</a></p>
	<p>WebsiteOutlook: <a style="display: inline;" href="http://www.websiteoutlook.com/www.exploretalent.com">Explore Talent</a></p>
	<p>QuantCast: <a style="display: inline;" href="http://www.quantcast.com/exploretalent.com">Explore Talent</a></p>
	<p>QuarkBase: <a style="display: inline;" href="http://www.quarkbase.com/exploretalent.com">Explore Talent</a></p>

</div>
