<h1>Glossary of Industry Terms</h1>
<h2>A</h2>
<div class="border_small industry">
    <p>
        <b>ABBY SINGER</b>- The shot before the last shot of the day. Named in honor
        of former first A.D., Abby Singer, who used to call the last shot of the
        day one shot too early.</p>
    <p>
        <b>ACTION!</b>- The command from the director for the scene to begin. It
        indicates that the camera is rolling.</p>
    <p>
        <b>A.D.</b>- The Assistant Director.</p>
    <p>
        <b>AD LIB</b>- Extemporaneous delivery without relying on a prepared script.</p>
    <p>
        <b>ADR</b>- Automated Dialogue Replacement. Dialogue added to a scene in
        post production. Sometimes erroneously called "looping".</p>
    <p>
        <b>AEA</b>- Actors' Equity Association; often called simply "Equity". SAG's
        sister union which represents stage actors.</p>
    <p>
        <b>AFI</b>- The American Film Institute</p>
    <p>
        <b>AFTRA</b>- American Federation of Television and Radio Artists. Represents
        radio artists and news broadcasters, and, in earlier times, television
        performers. In more recent times, however, television performers may be
        represented by either AFTRA or SAG, depending on the producer's contract.
        Discussions about merging the two organizations have been ongoing for several
        decades; recently the Television &amp; Film and Commercial Contracts have
        been jointly negotiated.</p>
    <p>
        <b>AGMA</b>- American Guild of Musical Artists</p>
    <p>
        <b>AGVA</b>- American Guild of Variety Artists</p>
    <p>
        <b>ART DIRECTOR</b>- Person who conceives and designs the sets.</p>
    <p>
        <b>AUDITION</b>- A tryout for a film, TV or stage role. Usually auditions
        involve reading from the script, but can also require improvisation.</p>
    <p>
        <b>AVAIL</b>- A courtesy situation extended by performer or agent to a producer
        indicating availability to work a certain job. Avails have no legal or
        contractual status.</p>
</div>
<h2>B</h2>
<div class="border_small industry">
    <p>
        <b>BACKGROUND</b>- The Extra performers. On the set, "Background!" is a verbal
        cue for the Extras to start their action.</p>
    <p>
        <b>BACK TO ONE!</b>- The verbal cue for performers to return to the mark
        where they started the scene.</p>
    <p>
        <b>BEAUTY SHOT</b>- The Assistant Director.</p>
    <p>
        <b>BEST BOY</b>- Extemporaneous delivery without relying on a prepared script.</p>
    <p>
        <b>BILLING</b>- Automated Dialogue Replacement. Dialogue added to a scene
        in post production. Sometimes erroneously called "looping".</p>
    <p>
        <b>BIO</b>- Actors' Equity Association; often called simply "Equity". SAG's
        sister union which represents stage actors.</p>
    <p>
        <b>BLOCKING</b>- The American Film Institute</p>
    <p>
        <b>BOOKING</b>- American Federation of Television and Radio Artists. Represents
        radio artists and news broadcasters, and, in earlier times, television
        performers. In more recent times, however, television performers may be
        represented by either AFTRA or SAG, depending on the producer's contract.
        Discussions about merging the two organizations have been ongoing for several
        decades; recently the Television &amp; Film and Commercial Contracts have
        been jointly negotiated.</p>
    <p>
        <b>BOOM</b>- American Guild of Musical Artists</p>
    <p>
        <b>BLUE SCREEN</b>- American Guild of Variety Artists</p>
    <p>
        <b>BREAKAWAY</b>- Person who conceives and designs the sets.</p>
    <p>
        <b>BREAKDOWN</b>- A tryout for a film, TV or stage role. Usually auditions
        involve reading from the script, but can also require improvisation.</p>
</div>
<h2>C</h2>
<div class="border_small industry">
    <p>
        <b>CALLBACK</b>- Any follow-up interview or audition.</p>
    <p>
        <b>CALL SHEET</b>- A sheet containing the cast and crew call times for a
        specific day's shooting. Scene numbers, the expected day's total pages,
        locations, and production needs are also included.</p>
    <p>
        <b>CALL TIME</b>- The actual time an actor is due on the set.</p>
    <p>
        <b>CAMERA CREW</b>- With the D.P. (Director of Photography) as its chief,
        this team consists of the camera operator, the first assistant camera operator
        (focus puller), the second assistant camera operator (film loader and clapstick
        clapper) and the dolly grip.</p>
    <p>
        <b>CAMERA OPERATOR</b>- The member of the camera crew who actually looks
        through the lens during a take. Responsible for panning and tilting and
        keeping the action within the frame.</p>
    <p>
        <b>CASTING DIRECTOR</b>- The producer's representative responsible for choosing
        performers for consideration by the producer or director.</p>
    <p>
        <b>CATTLE CALL</b>- A call for large groups of people.</p>
    <p>
        <b>CATERER</b>- Responsible for breakfast, lunch and dinner on a set. Different
        from Craft Services.</p>
    <p>
        <b>CD-ROM</b>- A compact disk that holds text, music and images. One of the
        principal new venues for interactive video games as well as for full motion
        video films. Acting for CD-ROM's is a new arena for actors. SAG 's Interactive
        Media Contract covers salaries and working conditions for this new medium.</p>
    <p>
        <b>CHANGES</b>- Outfits worn while performing.</p>
    <p>
        <b>CHEAT</b>- The actor's adjustment of body position away from what might
        be absolutely "natural" in order to accommodate the camera; can also mean
        looking in a different place from where the other actor actually is.</p>
    <p>
        <b>CHECKING THE GATE!</b>- A verbal command to check the lens on the camera;
        if the lens is - OK - the cast &amp; crew will move on to the next scene
        or shot.</p>
    <p>
        <b>CHIEF ELECTRICIAN</b>- Heads the electrician crew; also called the Gaffer.</p>
    <p>
        <b>CINEMATOGRAPHER</b>- Director of Photography</p>
    <p>
        <b>CLOSE-UP (CU)</b>- Camera term for tight shot of shoulders and face.</p>
    <p>
        <b>COLD READING</b>- Unrehearsed reading of a scene, usually at an audition.</p>
    <p>
        <b>COMMISSION</b>- Percentage of a performer's earnings paid to agents or
        managers for services rendered.</p>
    <p>
        <b>COMPOSITE</b>- A series of photos on one sheet representing an actor's
        different looks.</p>
    <p>
        <b>CONFLICT</b>- Status of being paid for services in a commercial for one
        advertiser, thereby contractually preventing performing services in a commercial
        for a competitor.</p>
    <p>
        <b>COPY</b>- The script for a commercial or voice over.</p>
    <p>
        <b>COVERAGE</b>- All camera shots other than the master shot; coverage might
        include two-shots and close-ups.</p>
    <p>
        <b>CRAFT SERVICES</b>- On-set beverage and snack table. Different from the
        Caterer.</p>
    <p>
        <b>CRANE SHOT</b>- A camera shot raised over or above the set or the action.</p>
    <p>
        <b>CRAWL</b>- Usually the end credits in a film or TV shot which "crawl"
        up the screen.</p>
    <p>
        <b>CREDITS</b>- Opening names in a film or TV show; also refers to one's
        performance experience listed on a resume or in a program.</p>
    <p>
        <b>CUE</b>- Signal, often an off-stage light or hand signal, by the assistant
        director to indicate an actor's entrance or action.</p>
    <p>
        <b>CUT!</b>- The verbal cue for the action of the scene to stop. At no time,
        may an actor call, "cut!"</p>
    <p>
        <b>CUTAWAY</b>- A short scene between two shots of the same person, showing
        something other than that person.</p>
</div>
<h2>D</h2>
<div class="border_small industry">
    <p>
        <b>DAILIES</b>- Screening of footage before it is edited.</p>
    <p>
        <b>DAY PLAYER (DAY PERFORMER)</b>- A principal performer hired on a daily
        basis, rather than on a longer-term contract.</p>
    <p>
        <b>DAYTIME DRAMA</b>- Soap opera.</p>
    <p>
        <b>DEMO TAPE</b>- An audio or video tape that agents use for audition purposes.</p>
    <p>
        <b>DGA</b>- Directors Guild of America.</p>
    <p>
        <b>DIALECT</b>- A distinctly regional or linguistic speech pattern.</p>
    <p>
        <b>DIALOGUE</b>- The scripted words exchanged by performers.</p>
    <p>
        <b>DIRECTOR</b>- The coordinator of all artistic and technical aspects of
        any production.</p>
    <p>
        <b>DIRECTOR OF PHOTOGRAPHY (D.P.)</b>- Supervises all decisions regarding
        lighting, camera lenses, color and filters, camera angle set-ups, camera
        crew and film processing.</p>
    <p>
        <b>DOLLY</b>- A piece of equipment that the camera sits on to allow mobility
        of the camera.</p>
    <p>
        <b>DOLLY GRIP</b>- The crew member who moves the dolly.</p>
    <p>
        <b>DOUBLE</b>- A performer who appears in place of another performer, i.e.,
        as in a stunt.</p>
    <p>
        <b>D.P.</b>- Director of Photography or Cinematographer.</p>
    <p>
        <b>DRESS THE SET</b>- Add such items to the set as curtains, furniture, props,
        etc.</p>
    <p>
        <b>DRIVE-ON PASS</b>- In Los Angeles, a pass to drive onto and park on a
        studio lot.</p>
    <p>
        <b>DUPE</b>- A duplicate copy of a film or tape; also, called a "dub"</p>
</div>
<h2>E</h2>
<div class="border_small industry">
    <p>
        <b>8x10</b>- Commonly used size of a performer's photos, usually in black
        and white.</p>
    <p>
        <b>18-TO-PLAY-YOUNGER</b>- A performer legally 18 years old, who can convincingly
        be cast as a younger age.</p>
    <p>
        <b>ELECTRICIAN</b>- In film, crew members who place lighting instruments,
        focus, gel and maneuver the lights.</p>
    <p>
        <b>EMPLOYER OF RECORD (EOR)</b>- The company responsible for employment taxes,
        unemployment benefits and workers compensation coverage.</p>
    <p>
        <b>EQUITY</b>- Actors Equity Association (AEA) Union representing stage actors.</p>
    <p>
        <b>EQUITY WAIVER</b>- In Los Angeles, 99-seat (or less) theatres, which were
        otherwise professional, over which Equity waived contract provisions under
        certain circumstances. Now officially called "Showcase code", the term
        "Equity waiver" is still used informally.</p>
    <p>
        <b>EXECUTIVE PRODUCER</b>- Person responsible for funding the production.</p>
    <p>
        <b>EXT. (Exterior)</b>- A scene shot outside.</p>
    <p>
        <b>EXTRA</b>- Background talent, used only in non-principal roles.</p>
</div>
<h2>F</h2>
<div class="border_small industry">
    <p>
        <b>FICA</b>- Social Security taxes (Federal Insurance Corporation of America).</p>
    <p>
        <b>FIELD REP.</b>- Union staff member who ensures contractual compliance
        on sets.</p>
    <p>
        <b>FIRST A.D.</b>- First Assistant Director; person responsible for the running
        of the set. Gives instructions to crew and talent, including calling for
        "first team," "quiet," "rehearsal," and "take five."</p>
    <p>
        <b>FIRST ASS'T. CAMERA OP.</b>- First Assistant Camera Operator is responsible
        for focusing the camera lens during the shooting of a scene; also known
        as the Focus Puller.</p>
    <p>
        <b>FIRST TEAM</b>- The production term for the principal actors in a scene.</p>
    <p>
        <b>4-A's</b>- Associated Actors and Artist's of America; umbrella organization
        for SAG, AFTRA, Equity and other performers' Unions.</p>
    <p>
        <b>FORCED CALL</b>- A call to work less than 12 hours after dismissal on
        the previous day. See TURNAROUND.</p>
    <p>
        <b>FOREGROUND CROSS</b>- Action in a scene in which an Extra Performer passes
        between the camera and the principal actors; sometimes called a "wipe".</p>
    <p>
        <b>FX (Effects)</b>- Special Effects.</p>
</div>
<h2>G</h2>
<div class="border_small industry">
    <p>
        <b>GAFFER</b>- The Chief Electrician.</p>
    <p>
        <b>GOLDEN TIME</b>- Contractually called 16 Hour Rule Violation for Extra
        Performers, is overtime, after the 16th hour, paid in units of one full
        day per hour.</p>
    <p>
        <b>GRIPS</b>- Members of the film crew who are responsible for moving set
        pieces, lighting equipment, dolly track and other physical movement of
        equipment.</p>
</div>
<h2>H</h2>
<div class="border_small industry">
    <p>
        <b>HAND MODEL</b>- A performer whose hands are used to double for others.</p>
    <p>
        <b>HIATUS</b>- Time during which a TV series is not in production.</p>
    <p>
        <b>HOLDING</b>- The designated area to which the Extra Performers report
        and stay while waiting to go on set.</p>
    <p>
        <b>HONEY WAGON</b>- A towed vehicle containing one or more dressing rooms,
        as well as crew bathrooms.</p>
</div>
<h2>I</h2>
<div class="border_small industry">
    <p>
        <b>IATSE</b>- International Alliance of Theatrical Stage Employees; the union
        which represents most off-camera crew members.</p>
    <p>
        <b>INDUSTRIAL</b>- Non-broadcast film or video, usually of an educational
        nature.</p>
    <p>
        <b>INSERTS</b>- Shots, usually close-ups of hands or close business, inserted
        into previously shot footage.</p>
    <p>
        <b>INT. (Interior)</b>- A scene shot indoors.</p>
    <p>
        <b>"IN" TIME</b>- The actual call time or start time; also, return time from
        a break.</p>
</div>
<h2>L</h2>
<div class="border_small industry">
    <p>
        <b>LINE PRODUCER</b>- The producer responsible for keeping the director on
        time and budget; generally the most visable producer on the set.</p>
    <p>
        <b>LONG SHOT (LS)</b>- A camera shot which captures the performer's full
        body.</p>
    <p>
        <b>LOOPING</b>- An in-studio technique used to fix dialogue already performed
        during principal photography by matching voice to picture.</p>
</div>
<h2>M</h2>
<div class="border_small industry">
    <p>
        <b>MARK</b>- The exact position(s) given to an actor on a set to insure that
        he/she is in the proper light and camera angle; generally marked on the
        ground with tape or chalk.</p>
    <p>
        <b>MARKER!</b>- A verbal cue that the take has been identified on camera
        both verbally and with the slate board.</p>
    <p>
        <b>MARTINI SHOT</b>- The last shot of the day.</p>
    <p>
        <b>MASTER SHOT</b>- A camera shot that includes the principal actors and
        relevant background activity; generally used as a reference shot to record
        the scene from beginning to end before shooting close-ups, over-the-shoulders,
        etc.</p>
    <p>
        <b>MATCHING ACTIONS</b>- The requirement that the actor match the same physical
        movements in a scene from take to take in order to preserve the visual
        continuity.</p>
    <p>
        <b>MEAL PENALTY</b>- A fee paid by the producer for the failure to provide
        meals or meal breaks as specified by the contract.</p>
    <p>
        <b>MIXER</b>- Chief of the sound crew; responsible for the quality of the
        sound recording on a shoot.</p>
    <p>
        <b>MOS (Mit Out Sound/Motion Only Shot)</b>- Any shot without dialogue or
        sound recording.</p>
    <p>
        <b>M.O.W.</b>- Movie of the week</p>
</div>
<h2>N</h2>
<div class="border_small industry">
    <p>
        <b>ND MEAL (NON DEDUCTABLE MEAL)</b>- A 15 minute meal break provided to
        actors by the production company to bring actors in sync with crew break
        time. It must be completed within 2 hours of performers call time.</p>
    <p>
        <b>NIGHT PREMIUM</b>- A surcharge for certain work performed after 8 p.m.</p>
</div>
<h2>O</h2>
<div class="border_small industry">
    <p>
        <b>OFF-CAMERA (OC or OS)</b>- Dialogue delivered without being on screen.</p>
    <p>
        <b>OUT OF FRAME</b>- An actor outside the camera range.</p>
    <p>
        <b>"OUT" TIME</b>- The actual time when you are released after you have changed
        out of wardrobe and make-up.</p>
    <p>
        <b>OVER-THE-SHOULDER</b>- A shot over the shoulder of one actor, focusing
        entirely on the face and upper torso of the other actor in a scene; generally
        shot in pairs so both actors expressions can later be edited together.</p>
    <p>
        <b>OVERDUBBING</b>- In studio singing or voice work, the process of laying
        one soundtrack over another.</p>
    <p>
        <b>OVERTIME (OT)</b>- Work extending beyond the contractual work day.</p>
</div>
<h2>P</h2>
<div class="border_small industry">
    <p>
        <b>P.A.</b>- Production Assistant.</p>
    <p>
        <b>PAN</b>- A camera shot which sweeps from side-to-side.</p>
    <p>
        <b>PAYMASTER</b>- An independent talent payment service acting as the employer
        of record.</p>
    <p>
        <b>PENSION &amp; HEALTH PAYMENT</b>- An additional amount of money paid by
        the employer to cover employee benefits under union contract.</p>
    <p>
        <b>PER DIEM</b>- Fee paid by producer on location shoots to compensate performer
        for expenditures for meals not provided by the producer.</p>
    <p>
        <b>PHOTO DOUBLE</b>- An actor cast to perform on camera in place of another.</p>
    <p>
        <b>PICK UP</b>- Starting a scene from a place other than the beginning.</p>
    <p>
        <b>PICTURE'S UP!</b>- Warning that the sequence of cues to shoot a scene
        is about to begin.</p>
    <p>
        <b>POV SHOT</b>- Point-of-View shot; camera angle from the perspective of
        one actor.</p>
    <p>
        <b>POST-PRODUCTION</b>- The phase of filmmaking that begins after the film
        has been shot. Includes scoring, sound and picture editing, titling, dubbing,
        and releasing.</p>
    <p>
        <b>PRE-PRODUCTION</b>- The phase of filmmaking before shooting begins; includes
        writing, scouting locations, budgeting, casting, hiring crews, ordering
        equipment and creating a shooting schedule.</p>
    <p>
        <b>PRINCIPAL</b>- A performer with lines.</p>
    <p>
        <b>"PRINT!"</b>- A call from the director at the end of a take that that
        particular take is good enough to be printed.</p>
    <p>
        <b>PRODUCER</b>- Often called the Line Producer; the person responsible for
        the day-to-day decision-making on a production.</p>
    <p>
        <b>PRODUCTION COMPANY</b>- The company actually making the film or television
        show.</p>
    <p>
        <b>PROPS</b>- Any objects used by actors in a scene.</p>
    <p>
        <b>PSA</b>- Public Service Announcement.</p>
</div>
<h2>R</h2>
<div class="border_small industry">
    <p>
        <b>RESIDUAL</b>- The fee paid to performers for rebroadcast of a commercial,
        film or TV program.</p>
    <p>
        <b>RESUME</b>- List of credits, usually attached to an 8x10 or composite.</p>
    <p>
        <b>REWRITE</b>- Changes in the script, often using color-coded pages to indicate
        the most current version.</p>
    <p>
        <b>RIGHT-TO-WORK-STATES</b>- Those states which do not honor certain union
        provisions.</p>
    <p>
        <b>ROLLING!</b>- The verbal cue for the camera film and audio tape to start
        rolling.</p>
    <p>
        <b>ROOM TONE</b>- A sound recording (sometimes made upon completion of a
        scene) to record existing noise at the location. Also called "wild track".</p>
</div>
<h2>S</h2>
<div class="border_small industry">
    <p>
        <b>SAG</b>- Screen Actors Guild.</p>
    <p>
        <b>SCALE</b>- Minimum payment for services under union contracts.</p>
    <p>
        <b>SCRIPT</b>- The written form of a screenplay, teleplay, radio or stage
        play.</p>
    <p>
        <b>SCRIPT SUPERVISOR</b>- The crew member assigned to record all changes
        or actions as the production proceeds.</p>
    <p>
        <b>SDI</b>- State Disability Insurance.</p>
    <p>
        <b>SECOND ASSISTANT DIRECTOR</b>- Often two or three on a set, they handle
        checking in the talent, insuring proper paperwork is filed, and distribute
        script revisions. Actors check in with the 2nd A.D. upon arrival on the
        set.</p>
    <p>
        <b>SECOND TEAM!</b>- The verbal cue for the stand-ins to come to the set
        and be ready to stand in.</p>
    <p>
        <b>SEGUE</b>- In film or tape editing, a transition from one shot to another.</p>
    <p>
        <b>SET</b>- The immediate location where the scene is being filmed.</p>
    <p>
        <b>SET-UP</b>- Each time the camera changes position.</p>
    <p>
        <b>SFX</b>- Sound effects.</p>
    <p>
        <b>SIDES</b>- Pages or scenes from a script, used in auditions or (if on
        a film set) those scenes being shot that day.</p>
    <p>
        <b>SIGNATORY</b>- An employer who has agreed to produce under the terms of
        a union contract.</p>
    <p>
        <b>SLATE</b>- A small chalkboard and clapper device, often electronic, used
        to mark and identify shots on film for editing; also the process of verbal
        identification by a performer in a taped audition (e.g., "Slate your name!").</p>
    <p>
        <b>SPEED!</b>- A verbal cue that the audio tape is up to speed for recording.</p>
    <p>
        <b>SPIKING THE LENS</b>- Looking directly into the lens during a scene; since
        it destroys the illusion of realism, actors should never spike the lens
        unless specifically directed to do so for specific effect.</p>
    <p>
        <b>STAGE RIGHT</b>- To the performer's right side, to the audience's left
        side. Likewise, STAGE LEFT is to the performer's left, the audience's right.
        Stage directions are for actors, not audiences, therefore they are always
        given from the actor's point of view to the audience.</p>
    <p>
        <b>STANDARD UNION CONTRACT</b>- The standard format/contract approved by
        the Unions and offered to performers prior to the job.</p>
    <p>
        <b>STANDARDS &amp; PRACTICES</b>- The network TV censorship departments.</p>
    <p>
        <b>STAND-INS</b>- Extra Performers used as substitutes for featured players,
        for the purpose of setting lights and rehearsing camera moves; also known
        as the second team.</p>
    <p>
        <b>"STICKS"</b>- Slate or clapboard.</p>
    <p>
        <b>STUDIO</b>- A building, recording room or sound stage which accommodates
        film or TV production.</p>
    <p>
        <b>STUNT COORDINATOR</b>- The person in charge of designing and supervising
        the performance of stunts and hazardous activities.</p>
    <p>
        <b>STUNT DOUBLE</b>- A stuntperson who performs stunts for a principal.</p>
    <p>
        <b>STUNTPERSON</b>- A specially trained performer who actually performs stunts.</p>
    <p>
        <b>SUBMISSION</b>- An agent's suggestion to a casting director for a role
        in a certain production.</p>
    <p>
        <b>SW</b>- A notation on a call sheet that an actor is starting on that day
        and working on that day.</p>
    <p>
        <b>SWF</b>- A notation on a call sheet that an actor is starting, working,
        and finished on that day.</p>
    <p>
        <b>SWEETENING</b>- In singing/recording, the process of adding additional
        voices to previously recorded work.</p>
    <p>
        <b>SYNDICATION</b>- Selling TV programs to individual stations rather than
        to networks.</p>
</div>
<h2>T</h2>
<div class="border_small industry">
    <p>
        <b>TAFT-HARTLEY</b>- A federal statute which allows 30 days after first employment
        before being required to join a Union.</p>
    <p>
        <b>TAKE</b>- The clapboard indication of a shot "taken" or printed.</p>
    <p>
        <b>"TAKE 5"</b>- The announcement of periodic five minute breaks.</p>
    <p>
        <b>TELEPROMPTER</b>- The brand name of a device which enables a broadcaster
        to read a script while looking into the camera lens.</p>
    <p>
        <b>THEATRICAL</b>- TV shows or feature film work, as opposed to commercials.</p>
    <p>
        <b>THREE BELLS!</b>- An audible warning for QUIET because a scene is about
        to be filmed.</p>
    <p>
        <b>TIGHT SHOT (Go in Tight)</b>- Framing of a shot with little or no space
        around the central figure(s) of feature(s); usually a close-up.</p>
    <p>
        <b>TILT</b>- The up and down movement of a camera.</p>
    <p>
        <b>TIME-AND-A-HALF</b>- Overtime payment of 1 1/2 times the hourly rate.</p>
    <p>
        <b>TRACKING SHOT</b>- A shot taken while the camera is moving, either on
        a dolly or mounted on a moving vehicle.</p>
    <p>
        <b>TRADES</b>- Short for "trade papers" - The newspapers and periodicals
        such as the Hollywood Reporter and Variety that specifically feature information
        on the entertainment industry.</p>
    <p>
        <b>TURNAROUND</b>- (a) The number of hours between dismissal one day and
        call time the next day. (b) To shoot a scene from another direction.</p>
    <p>
        <b>TWO-SHOT</b>- A camera framing two persons.</p>
</div>
<h2>U</h2>
<div class="border_small industry">
    <p>
        <b>UNDERSTUDY</b>- A performer hired to do a role only if the featured player
        is unable to perform; used primarily in live theatre.</p>
    <p>
        <b>UPGRADE</b>- The promotion of an extra performer in a scene to the category
        of principal performer.</p>
    <p>
        <b>UPM</b>- Unit Production Manager - Oversees the crews and handles the
        scheduling of all the technical responsibilities of the production.</p>
    <p>
        <b>UP STAGE</b>- (a) The area located at the back of the stage. Down Stage
        is the area in front of the performer. (b) To draw attention to oneself
        at the expense of a fellow performer.</p>
</div>
<h2>V</h2>
<div class="border_small industry">
    <p>
        <b>V.O.</b>- Voice over. An off-camera voice coming either from an actor
        not in the frame, or from a secondary source such as a speakerphone or
        answering machine.</p>
    <p>
        <b>VOUCHER</b>- Time slip with all pertinent information needed for getting
        paid properly.</p>
</div>
<h2>W</h2>
<div class="border_small industry">
    <p> <b>W</b>- A notation on the call sheet indicating that an actor is working that day.</p>
    <p> <b>WAIVERS</b>- Union-approved permission for deviation from the terms of a contract.</p>
    <p> <b>WALKAWAY</b>- A meal break in which all cast and crew are on their own to get lunch.</p>
    <p> <b>WARDROBE</b>- The clothing a performer wears on camera.</p>
    <p> <b>WARDROBE ALLOWANCE</b>- A maintenance fee paid to on-camera talent for the use (and dry cleaning) of talent's own clothing.</p>
    <p>
        <b>WARDROBE FITTING</b>- A session held prior to production to prepare a
        performer's costumes.</p>
    <p>
        <b>WEATHER PERMIT CALL</b>- Due to weather conditions, the production company
        has the option to release an actor four hours after the call time (if the
        camera has not started to roll) with a reduced rate of pay for the day.</p>
    <p>
        <b>WILD TRACK</b>- A recording of dialog or sound effects on the set of a
        film but without the camera running.</p>
    <p>
        <b>W/N</b>- Will Notify. A notation on a call sheet that tells the actor
        that he/she will probably work that day but the specific time has not yet
        been decided.</p>
    <p>
        <b>WRAP</b>- The completion of a day's filming or of an entire production.</p>
</div>
<h2>Z</h2>
<div class="border_small industry">
    <p>
        <b>ZOOM</b>- A camera technique with a special lens to adjust the depth of
        a shot, accomplished without moving the camera.</p>
</div>