<h2>Explore Talent Media Kit</h2>

<div class="border_small">
	<div>
		<h3>Who We Are</h3>
		<p>The Leader in Social Networking for Talent, ExploreTalent.com has quickly dominated the online community as the place for actors, models, dancers, musicians and crew to apply directly for auditions and jobs. </p>
		<p>For more information download our media kit. <a href="/about/faq">Contact Us Now</a></p>
	</div>
	<div style="clear:both;"></div>
	<div class="media_kit">
		<a href="/assets/et_mediakit.pdf" target="_blank"><img src="<?php echo CDN_JS_CSS; ?>/graphics/mediakit_pdf.png" /></a>
		<h3>PDF</h3>
		<p>This Download is a PDF file which can be viewed with Adobe Reader. Adobe Reader is known as the go to program for viewing PDF files and is available absolutely free. To download Adobe Reader please visit:
			<a href="http://get.adobe.com/reader" rel="nofollow" target="_blank" title="Download Adobe Reader">http://get.adobe.com/reader</a>
		</p>
	</div>
	<div style="clear:both;"></div>
	<div class="media_kit">
		<a href="/assets/et_mediakit.rar" target="_blank"><img src="<?php echo CDN_JS_CSS; ?>/graphics/mediakit_jpg.png" /></a>
		<h3>JPEG Zip Archive</h3>
		<p>This Download includes 11 high quality images that have been compressed into one archive for your convenience. This download is a good option for users That do not have a pdf reader and do not want to install additional software.
		</p>
	</div>
	<div style="clear:both;"></div>
	<img alt="madia_image" src="<?php echo CDN_JS_CSS; ?>/graphics/media_kit_contents.jpg">
</div>