<h1>Be safe ! Avoid scams and fraud! Beware of getting advance check</h1>

<div class="border_small">
	<h2>Follow these common-sense rules:</h2>
	<ul class="bullets">
		<li>Deal ONLY with people you can meet in person - Use this simple rule and you will avoid 99% of the scam attempts.</li>
		<li>NEVER wire money through MONEYGRAM, WESTERN UNION, or any other wire service - anyone who asks you to do so is a scammer.</li>
		<li>FAKE CASHIER CHECKS &amp; MONEY ORDERS ARE COMMON, and your bank will cash these checks and than hold you responsible when the fake check is discovered days later.</li>
		<li>ExploreTalent is not part on any transaction, and does not handle payments, guarantee transactions, or offer any "buyer protection".</li>
		<li>Do not give out your financial information (bank account number, social security number, PayPal info, etc.)</li>
	</ul>
</div>

<h1>Who should I notify about fraud or scam attempts?</h1>

<div class="border_small">
	<h4>If you suspect that any project on our site is a scam, please report <a href="/about/help">here</a></h4>
	<h2>If you become a victim report to the below agencies</h2>
	<ul class="bullets">
		<li>FTC toll free hotline: 877-FTC-HELP (877-382-4357) </li>
		<li><a href="http://www.ftc.gov/">FTC online complaint form</a></li>
		<li><a href="http://www.ic3.gov/default.aspx">Internet Fraud Complaint Center</a></li>
		<li>on-emergency number for your local police department.</li>
	</ul>
</div>

<h1>Recognizing scams</h1>

<div class="border_small">
	<h2>Most scams involve one or more of the following:</h2>
	<ul class="bullets">
		<li>Inquiry from someone far away, or "traveling" </li>
		<li>Money Gram, Western Union, cashier's check, money order.</li>
		<li>Refusal or inability to meet face-to-face before consummating transaction</li>
	</ul>
	<p>Warning: Never pay back a "commission" fee back to any fake "agent' or "scout" in return for an "advance payment" cashier's check or a check sent or given to you as payment for a job or role. Value of cashier's check often exceeds what's due to you for the job you perform - scammer offers to "trust" you, and asks you to wire his "commission" via money transfer service. Your bank will cash these fake checks and than hold you responsible when the check fails to clear.</p>
</div>