<div class="profile_content border_small resources_title">Explore Talent
	Scam: Is Explore Talent a Scam</div>

<div class="resources_content border_small">
	<p>Competitors have been posting negative stuff about us, however you
		cannot argue with success.</p>
</div>

<div class="profile_content border_small resources_title">Facts:</div>

<div class="resources_content border_small">
	<p>1. ExploreTalent.com is by far world's largest talent website with
		over 6.7 million members.</p>
	<p>2. ExploreTalent.com has over 50,000 auditions and job openings, 25
		times than any other.</p>
	<p>3. No other site comes even close to the value that ExploreTalent is
		providing its members.</p>
	<p>4. The Internet is a media that everyone anonymously, can go and
		post unverifiable stories.</p>
	<p>5. Negative comments about us are posted by competitors who cannot
		stand our success.</p>
	<p>6. Tens of Thousands auditions and jobs, has been landed by
		ExploreTalent.com members.</p>
	<br>
	<p>People have asked if Explore Talent is a scam. Explore Talent has
		had a reputation of being a scam or frauds. With over 6.7 million
		members Explore Talent has proved it is not a scam. Explore Talent has
		thousands of positive testimonies a month and continues to take pride
		in their work.</p>
	<br>
	<p>If you are an aspiring talent, you can't go wrong with the services
		of Explore Talent and be genuinely comfortable knows it is not a scam.
		With over 6.7 million members and counting the proof is unstoppable.
		ExploreTalent.com is by far the world's largest talent resource
		website and their services are unbeatable. With a big name like
		Explore Talent, we cant afford to be a scam nor would we want to.</p>
	<br>
	<p>In recent years it seems to be that "talent resources and agencies"
		are coming out of the woodwork, with promises of making you an over
		night Hollywood sensation. These type of companies are truly scam
		agencies. And really with promises like that, who wouldn't fall victim
		to these scam and fraudulent companies? If you feel that you
		victimized by one of these scam or fraudulent companies, and blinded
		with their absurd lies and manipulation Explore Talent is here to
		help.</p>
	<br>
	<p>Explore Talent wants to help you if you have been a victim to a
		scam. Here at Explore Talent we intend to raise the bar in legitimacy
		and set a higher standard of honesty and services to each and every
		hopeful talent that fell victim to being a scam by one of our
		"competitor" companies. This higher standard starts with our Fraud
		Compensation Program, which will provide victims with restored hope,
		faith and peace of mind, to continue pursuing their dreams and
		aspirations. For every $29.95 you were defrauded, you will receive
		Explore Talent's monthly service for free! Don't fall for another scam
		again!</p>
	<br>
	<p>Qualifying for this program is easy and stress free; simply provide
		Explore Talent with your credit card statement, showing the amount in
		which you were defrauded. Absolutely no credit card billing
		information is required for you to claim your free service. Explore
		Talent is prudent about exposing industry scam artist, who practice
		victimizing aspiring talents by selling them lies, broken promises and
		empty dreams, and a big scam for a fee. Never fall for a scam again!
		Let Explore Talent help you pick up your life after being a victim of
		a scam.</p>
	<br>
	<p>So what are you waiting for, you have nothing to lose; with Explore
		Talent's anti scam project called Fraud Compensation Program you can
		get your dreams and career back on track and never fall for another
		scam again. Let the world's largest talent website extend their hand
		to helping you, and never feel like a victim or scammed again!</p>
	<br>
	<p>Please see below some of Explore Talent members testimonials.</p>
</div>

<div class="profile_content border_small resources_title">Success
	Stories of ExploreTalent customers</div>

<div class="resources_content border_small">
	<p>
		<a href="/media/video/testimonials">Casting Directors & Talent Agents Success Stories</a> -
        <a href="">Got your own Success Story?</a> -
        <a href="">More happy customers</a>
	</p>
	<br>
	<div class="scam_video">
		<div class="scam_one">
			<iframe width="272" height="180"
				src="http://www.youtube.com/embed/M5s5TLqlOwI" frameborder="0"
				allowfullscreen></iframe>
		</div>
		<div class="scam_two">
			<h3>Explore Talent member Boby Banhart from A Shot at Love with Tila
				Tequila</h3>
			<p>Bobby Banhart found a job on A Shot at Love with Tila Tequila
				through ExploreTalent.com shortly after he joined. He submitted his
				resume and headshot and was cast in the highest rated MTV show with
				6.7 million viewers.</p>
		</div>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<iframe width="272" height="180"
				src="http://www.youtube.com/embed/SYgk5Evphc8" frameborder="0"
				allowfullscreen></iframe>
		</div>
		<div class="scam_two">
			<h3>"Explore Talent is Hot!"</h3>
			<p>"Forget LA Casting, this is the new hot one right here!
				ExploreTalent.com!" Christopher Warren, actor in CSI:NY and
				Journeyman, gives his advice to actors just starting out. Explore
				Talent is hot!</p>
		</div>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<iframe width="272" height="180"
				src="http://www.youtube.com/embed/hiYuVunbpjs" frameborder="0"
				allowfullscreen></iframe>
		</div>
		<div class="scam_two">
			<h3>"ExploreTalent is an awesome outlet"</h3>
			<p>I had been with LA Casting for 9 months. After submitting for
				auditions and getting nothing, I decided to give Explore Talent a
				try. Within two weeks of becoming a member of Explore Talent, I
				started going on 2-3 auditions per week. I have now been with
				ExploreTalent.com for 6 months and I have not stopped working. I
				never even got any auditions on LACasting.com and everything changed
				after I joined ExploreTalent.com.</p>
		</div>
	</div>
	<div class="scam_video">
        <h3>A member was pre-selected for the leading role in a major movie
            without the Casting Director even seeing him in person</h3>
		<div class="scam_one">
			<iframe width="272" height="180"
				src="http://www.youtube.com/embed/wvXGgOcSegc" frameborder="0"
				allowfullscreen></iframe>
		</div>
		<div class="scam_two">
			<h3>"One Hour Fantasy Girl" Film Screening With Explore Talent Actor</h3>
			<p>Explore Talent member John Morgan Woodward at the private cast and
				crew screening of "One Hour Fantasy Girl". Producer John Paul Rice
				used Explore Talent's service to cast the role of Roger in his film.
				John Morgan Woodward, a member of Explore Talent, found the call
				after one week of being a member. He responded to the call through
				Explore Talent, auditioned and was cast in this powerful dramatic
				independent film. John Paul Rice will use Explore Talent again for
				his upcoming film "The Boy Who Couldn't Say No". Look for upcoming
				film auditions, movie auditions, film roles with Explore Talent.</p>
		</div>
	</div>
    <div style="clear: both;"></div>
</div>

<div class="resources_content border_small">
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media414/0004140121/th0004140121_PM_1309230786.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4140121">View My Profile</a>
			</div>
		</div>
		<p>I just wanted to take a few minutes of my time to say what a great
			experience I have had with Explore Talent. I joined as a Pro Member
			one month ago and less than two weeks later, I received a call from a
			director wanting me for an infomercial. I had the best experience
			filming it and learned so much. I have received more than once the
			"Like-It" Email from a casting director. I thought this was all going
			too fast, so I called Explore Talent. The staff was so friendly and
			explained to me that yes, I was actually viewed by the director on
			this site and he liked what he saw. This was a SAG film also!! I was
			so excited. Thanks so much to the wonderful and professional staff at
			Explore Talent.</p>
		<p>Amy</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media088/0000882191/th0000882191_PM_1207125077.jpg" />
			<div>
				<a href="/profile/social/social-info/id/882191">View My Profile</a>
			</div>
		</div>
		<p>Landed 2 movie roles...</p>
		<p>Thank you ExploreTalent... Christina landed 2 Feature Film roles.
			These are independent movies that will be shown in all the major
			International Film Festivals. She just joined ExploreTalent and
			already has more opportunities than we ever imagined. An elite
			modeling management agency in New York contacted us after seeing
			Christina's profile on ExploreTalent. A casting director personally
			asked Christina to audition personally for both a TV SHOW and a Music
			Video. A producer/director from Tampa requested a dancing video of
			Christina for a short he is producing. We are actually overwhelmed by
			the response we have gotten from working with ExploreTalent Casting
			Directors and Producers.Thank you again. You are the BEST,</p>
		<p>Christina McGill, Actress/Model &amp; Jeanne McGill, Mother.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media489/0004890092/th0004890092_PM_1327457145.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4890092">View My Profile</a>
			</div>
		</div>
		<p>Back in April I filmed a short film called "The Time" and a couple
			weeks ago I filmed as an extra in the Adam Sandler film "I Hate You
			Dad" which has a release date for next Summer. I have also had an
			offer to film a Meg Ryan film called "Lives of Saints" in November in
			Los Angeles and have had offers for four Disney shows A.N.T Farm
			Shake it Up Good Luck Charlie and Zeke and Luther. This is all in
			addition to offers for Big Time Rush & True Jackson VP and have been
			contacted by Ashley Argota's publicist who may work with me starting
			this July.</p>
		<p>Thank you Explore!</p>
		<p>Lindsey M.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media432/0004328367/th0004328367_PM_1328888651.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4328367">View My Profile</a>
			</div>
		</div>
		<p>Explore Talent is making Jillian's dreams come true! Jillian has
			been acting and modeling locally and had a good resume for a
			nine-year-old. After exploring several options to bump up her
			activity, Explore Talent seemed to be a reasonably priced and good
			way to find auditions. We had no idea just how awesome the site was!
			Jillian has had several opportunities and has been chosen as
			Director's Choice on several occasions. She won a role in an
			off-Broadway show and just recently has been chosen as a Cover Model
			for an upscale salon in Brooklyn called Felicity where she will be
			one of their "Faces of Felicity". She will be doing commercials, TV
			appearances and print marketing for this salon. She will also be
			featured on their website. They have been on ABC News with Lauren
			Glassberg and featured in magazine publications like Essence and New
			York Magazine. They are gearing up for a large scale marketing
			campaign, and Jill gets to be a part of it! She is so excited! She
			also has an audition to be on Law and Order coming up in June. We
			have actually had to turn down some auditions recently because she is
			so busy! Imagine??</p>
		<p>As a mother of a young child, I feel confident that the auditions
			that we go on are legitimate and safe. The Explore Talent team has
			contacted us to give us advice on how to better structure Jill's
			profile and support us any way they can. It is so easy to use. They
			do all the organizing for us. The matched auditions feature is the
			best! I don't have to struggle to search for appropriate auditions,
			they are right there for me. I love the automatic email feature that
			sends me the most up-to-date opportunities in our area. This site is
			awesome and the staff cares about us!</p>
		<p>Thanks Explore Talent! You guys are the best!</p>
		<p>Jillian's Mom</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media293/0002933626/th0002933626_PM_1327456692.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2933626">View My Profile</a>
			</div>
		</div>
		<p>I'm so happy to say that since I enrolled with Explore Talent my
			life style has changed. I have meant with some beautiful people from
			all around the world. I have performed several Theater projects in
			New York City. " 13 Ways to Screw up a College Interview", "The
			Little mermaid" and "Christmas Extravaganza". I was also cast for a
			film " The Industry". Once again thanks Explore Talent for such an
			awesome website which has open the doors to a brighter future</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media212/0002120130/th0002120130_PM_1249458790.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2120130">View My Profile</a>
			</div>
		</div>
		<p>Got casted in less than 1 week</p>
		<p>I just wanted to thank Explore Talent so much! I just recently
			landed the Role of Jackie in the Movie "Siphon". I play the leading
			role of the smart, sexy, college girl! I start filming this week.</p>
		<p>It was my first audition and I booked the role! I have five more
			upcoming auditions and have been labeled on the "Like it List" from
			even more Casting Directors. I also got asked to audition for the Act
			Up documentary seen by over 40 million people world wide.</p>
		<p>I also have an audition for a new vampire movie. My dreams are
			finally coming true. I found my passion and realized I can do it with
			the help of Explore Talent. I'm like my own manager! I submit my
			picture to the Casting Directors, and if I fit the role they email me
			back with more information on when I can audition.</p>
		<p>The best part is I set the days I want to audition and I can submit
			to as many auditions as I want to! The trick is Submit, submit,
			submit! Never give up!! You can't just have instant success - you
			have to work for it!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media248/0002485135/th0002485135_PM_1262589797.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2485135">View My Profile</a>
			</div>
		</div>
		<p>Thanks so much Explore Talent! It's only been 6 months that I've
			been able to aggressively pursue acting jobs and already I've landed
			a feature role in an independent film and an extra role with great
			face time on Tyler Perry's Meet the Browns! It would not have been
			possible without your help, thanks again Explore Talent, your
			AWESOME!!! I can't wait to see what the future holds.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media485/0004855323/th0004855323_PM_1331265897.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4855323">View My Profile</a>
			</div>
		</div>
		<p>I was thinking that at 56 years old maybe it was to late after be
			away from acting for me to land anything. Well not true thanks to a
			post on Explore Talent I was just casted as a support actor for a
			feature film being shot in Seattle, Wa. Don't give up hope on not
			getting roles ... they will come. And never give up hope on yourself!
			If this Old Bird can do it -- so can you! Good luck to everyone out
			there looking and auditioning, and thanks again Explore Talent!
			Without your help I wouldn't be acting again.</p>
		<p>Dreams really can come true.</p>
		<p>Mike Cahill</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media218/0002180766/th0002180766_PM_1327456609.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2180766">View My Profile</a>
			</div>
		</div>
		<p>Olivia has gotten several jobs from your website, although they are
			not high paying, they have been fun and exciting for Olivia and kept
			her doing what she loves - acting. Two of her roles, indie feature
			films "Leaving Hollywood" and "6 Nonsmokers" were screened at the
			Senator Theater in Baltimore this summer. She just finished filming a
			horror movie called "The Talking." She has also got to be on TV in
			National Geographic's "The Secret Lives of Charles Lindbergh."
			Thanks</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media054/0000549370/th0000549370_PM_1327456502.jpg" />
			<div>
				<a href="/profile/social/social-info/id/549370">View My Profile</a>
			</div>
		</div>
		<p>Got a part in a movie!</p>
		<p>I just recently got a part in the movie Totally Baked with National
			Lampoon, met with Michael Gaylord the photographer, and also have met
			a few production agencies and a few agents that are interested in me!
			You guys have been a lot of help! Thank you so much. I have met a lot
			of wonderful people that are helping me further my dreams! Explore
			Talent has helped me to realize some of the potential that I possess;
			this means a lot to me thank you again!</p>
		<p>Jiazi WangPS NY, NY</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media024/0000243891/th0000243891_PM_1128101000.jpg" />
			<div>
				<a href="/profile/social/social-info/id/243891">View My Profile</a>
			</div>
		</div>
		<p>Good Morning, I wanted to send you an e-mail over the weekend, but
			have been extremely busy with acting classes in order to prepare for
			my role in an independent film about the Washington DC Sniper. I am
			very grateful to the service that Explore Talent offers and refer
			this service to several of my counterparts in acting class.</p>
		<p>On another note, I want to extend my greatest thanks to you and the
			great customer service you provide to me each and every time I call.
			You not only make sure that any information given to me is accurate,
			but you also make sure that I receive the full benefits of using
			Explore Talent for my acting career and I want to say again, thanks.</p>
		<p>Nichola GrahamWashington, DC</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media375/0003757600/th0003757600_PM_1318959750.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3757600">View My Profile</a>
			</div>
		</div>
		<p>Hello everyone, I have been with Explore Talent for a month now and
			already getting emails from director to auditions I went on one
			audition and landed a role in a Feature Film. I have a supporting
			role playing a Jamaican girl this is going to be so much fun! I have
			also received many more auditions as well. I want to say THANK YOU
			EXPLORE TALENT. I tell everyone if you have dreams in life I'm
			telling them to come to ET they are the best.. Thank you again
			EXPLORE TALENT Jiniece H</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media209/0002097417/th0002097417_PM_1245382898.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2097417">View My Profile</a>
			</div>
		</div>
		<p>Thanks Explore Talent!</p>
		<p>I submitted my daughter Zoe for a paid modeling job and she got it.
			It was a lifestyle shoot for Carhartt! She had so much fun and
			everyone was super nice!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media220/0002205734/th0002205734_PM_1301004548.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2205734">View My Profile</a>
			</div>
		</div>
		<p>Within 2 weeks if signing up I GOT A ROLE IN AN UPCOMING
			INDEPENDENT FILM!!!</p>
		<p>I want to start off by thanking Jennifer from Explore Talent
			because she was VERY helpful and gave good advice on what to do and
			what not to do with my profile. Second I want to say that Explore
			Talent really helps their customers be the best they can be. Being
			only with Explore Talent for 3 months I have already gotten feedback
			6 times from casting directors. I didn't think I'd have the
			opportunity, but Explore Talent gave it to me! Thank you for helping
			and promoting me!</p>
		<p>-Jesseal:)</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media420/0004200866/th0004200866_PM_1314192495.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4200866">View My Profile</a>
			</div>
		</div>
		<p>I just want to let people out there know that I have enjoyed my
			experience this far tremendously. I've gotten auditions for paying
			jobs 3 times already and landed a lead role in a community play in
			the 2 months I've been part of Explore Talent. I've made some great
			friends and even won a prize in a contest for best smile. I look
			forward to more auditions and using Explore Talent as a boost to my
			career.</p>
		<p>Scott Price</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media051/0000519737/th0000519737_PM_1123628351.jpg" />
			<div>
				<a href="/profile/social/social-info/id/519737">View My Profile</a>
			</div>
		</div>
		<p>Landed a $1,600 gig on my 2nd day of signing up!</p>
		<p>I signed up on a Wednesday and was hired for a gig Thursday! It is
			a "Live Event" - Game show Host for the Independent Film Channel.The
			opportunity was placed on my calendar, I sent my info to the contact
			person and two phone calls later I was hired. I was flown to NYC, put
			up in a hotel for a night and spent a day in training. Upon
			completion (12 days total,3-4 hours a day) I will have earned $1,600!
		</p>
		<p>Just wanted to say THANK YOU!</p>
		<p>Jacqueline Rich</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media041/0000413527/th0000413527_PM_1179724387.jpg" />
			<div>
				<a href="/profile/social/social-info/id/413527">View My Profile</a>
			</div>
		</div>
		<p>I got 4 jobs within 3 days !</p>
		<p>HI Explore Talent, my name is Erica Hamilton. I just want to say
			thank you for the many jobs I have received. I have been on the
			website for a short period of time and I am really pleased. I
			recently got a call from Juan Meet in Miami a new line of maternity
			clothing for a catalog. I was also contacted by cardwell talent for
			promotional modeling for the Nivea Event and future events. It does
			not stop there I was contacted by Talent Inc for Venus modeling
			promotion as well. Just when I thought that would stop I got a
			contract for International Shopping Headquarters for catalog work.
			Wow and it still does not stop I was also contacted by Cardwell
			promotions for the Discover promotional Modeling Event and future
			promotions. I have gotten these jobs over a period of three days. I
			look forward in the near future to audition for film and other jobs.
			I just want to say you have to stay motivated and positive and never
			give up on your dreams. I wont stop. I plan to stay active and take
			more jobs. "Thank You Explore Talent" You made it possible for me to
			achieve my goals, dreams and goal are possible just stay positive.</p>
		<p>Sincerely,Erica Hamilton</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media048/0000481195/th0000481195_PM_1119389522.jpg" />
			<div>
				<a href="/profile/social/social-info/id/481195">View My Profile</a>
			</div>
		</div>
		<p>Got a role in a full length feature film!</p>
		<p>Just wanted to give a big "Thank You" to Explore Talent. My
			daughter Julia Hodgkins auditioned for a role in a full length
			feature film called Second Wind and got a co-supporting role in the
			film! We're presently in rehearsals and will be filming in a couple
			of weeks. The experience has been amazing and so rewarding. Working
			with director, Daryl C. Sylva is awesome. If it weren't for Explore
			Talent, we wouldn't be here right now! We're very grateful for your
			service.</p>
		<p>Maria Hodgkins & Julia Hodgkins</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media436/0004361516/th0004361516_PM_1311790369.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4361516">View My Profile</a>
			</div>
		</div>
		<p>I love this site, it is so helpful and I got my first audition
			within the first 10 days of signing up as a member! I HIGHLY
			recommend using this site! Thanks Explore Talent, Nicole</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media295/0002954563/th0002954563_PM_1326942744.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2954563">View My Profile</a>
			</div>
		</div>
		<p>I am very proud of the recent job that my family and I were able to
			land with Explore Talent! Our new web-series on MSN is promoting
			"family," exercise and utilizing the many incredible National Parks
			in our country. As the current Mrs.Iowa-America and "Mrs.Fitness
			2009," at Mrs.America, the show has been able to project a very
			meaningful cause for me as well, fitness. My family was flown out to
			Joshua Tree National Park on a whirlwind week of vacation and family
			challenges where we were introduced to camera men from Amazing Race
			and Reveille (The Office, Biggest Loser and Ugly Betty) production
			and staff. The experience was inspiring and professional...Explore
			Talent connected us to some really great work and some to the biggest
			in the business! I can now add companies such as Benadryl, National
			Parks Foundation, Walmart and Revielle to my resume experience
			now...Just from this one job!! Thank you Explore Talent!</p>
		<p>Loni McNertney Mrs. Iowa America 2009</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media027/0000273432/th0000273432_PM_1098380499.jpg" />
			<div>
				<a href="/profile/social/social-info/id/273432">View My Profile</a>
			</div>
		</div>
		<p>Got Warner Bros. KTLA channel 5 Commercial !</p>
		<p>Michael recently co-stared in a promotional commercial for the WB
			(Warner Bros.) KTLA channel 5. Michael really enjoyed this experience
			and looks forward to many more! He found being in front of the
			cameras was fun and enjoyed being the center of attention. Warner
			Brothers picked him through Explore Talent's web site. He received
			$300 for the shoot. A copy of Michael's commercial is available on
			his profile.</p>
		<p>Michael's Father</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media419/0004196515/th0004196515_PM_1319226540.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4196515">View My Profile</a>
			</div>
		</div>
		<p>I just wanted to take a moment and express my heartfelt gratitude
			to the wonderful staff at ET. I was very impressed with the
			professionalism from the very beginning and as the months went by
			that first impression only grew even more.Within the span of just
			months, I landed 4 roles including one with Jennifer Lopez. I also
			have a lead role in a Stage production.It is great to be able to pick
			and choose what roles to accept all thanks to the many opportunities
			provided by Explore Talent. My immediate goal was to get some
			additional experience under my belt and now I feel that my resume is
			solid and able to take things to the next level. Explore Talent has
			absolutely been crucial to my success without which I would not be in
			the position that I am today. Also thank you to Kari who has been so
			warm, professional, and able to help guide me to enjoy the full
			benefits of being a member and facilitate my professional career and
			an actor/ singer. The best advice it to keep your excitement and
			enthusiasm and stay focused/determined. Stay active, check your
			matched opportunities and submit your profile. THANK YOU
			EXPLORETALENT.COM Dwayne B</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media332/0003329235/th0003329235_PM_1281324824.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3329235">View My Profile</a>
			</div>
		</div>
		<p>I will be in a movie as a main character, just one month after
			joining!! I auditioned and landed the part. Thank you Explore
			Talent!!</p>
		<p>Matthew</p>
		<p></p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media040/0000408381/th0000408381_PM_1144279210.jpg" />
			<div>
				<a href="/profile/social/social-info/id/408381">View My Profile</a>
			</div>
		</div>
		<p>Got a speaking part in a full-length Movie</p>
		<p>Exploretalent is so helpful for people that aren't on the East or
			West coast. I have lots of auditions to go to, but many areas are too
			far away. ExploreTalent uses the whole U.S., and I went to my first
			audition (in Minnesota) and got a speaking part in a full-length
			movie, and want to thank Explore Talent for the opportunities it
			opens up to me.</p>
		<p>Ana Rocha</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media047/0000477152/th0000477152_PM_1154636180.jpg" />
			<div>
				<a href="/profile/social/social-info/id/477152">View My Profile</a>
			</div>
		</div>
		<p>Landed 2 Feature Film major roles with some great cash!...</p>
		<p>Since I joined Exploretalent.com last year around this time, I have
			landed two Feature Film major roles! I never would have realized the
			opportunities had it not been for you guys! The first film I received
			a part in was a feature by Raj Rahi called "ShutUp!", it will be
			completed this year. The second I am currently shooting here in
			Memphis is a major role with some great cash! I thought that this
			might be another one of those pay for nothing sites, but obviously
			you guys know what you are doing. Keep up the good work and keep the
			roles coming for me!!</p>
		<p>--Chris Plumlee</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media197/0001979451/th0001979451_PM_1218737331.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1979451">View My Profile</a>
			</div>
		</div>
		<p>You had matched me with a role and I got the part as a Extra in the
			short film called "A New Day." I filmed about 3 days, had a good
			time, and got to meet some new people. The producers where great and
			I hope to work with them again. I look forward to doing more acting
			and someday land that lead role.</p>
		<p>John Luna</p>
		<p></p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media583/0005833429/th0005833429_PM_1327469487.jpg" />
			<div>
				<a href="/profile/social/social-info/id/5833429">View My Profile</a>
			</div>
		</div>
		<p>I am 11 years old and I signed up for the 7-day trial membership. I
			have never modeled before and I saw a print job on Explore Talent. I
			sent in my information and got a job on my first interview and try.</p>
		<p>Thank you Explore Talent, who knows whats in store for my future!
			The job I got was in Dallas, Texas and it pays $25 per hour, wow my
			first paying job!</p>
		<p>Kamyn</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media061/0000612622/th0000612622_PM_1306858405.jpg" />
			<div>
				<a href="/profile/social/social-info/id/612622">View My Profile</a>
			</div>
		</div>
		<p>Received audition for commercial...got job!</p>
		<p>Through Explore Talent I received an audition for a commercial for
			the product "Go Smile" Teeth Whitening. I got the job and shot the
			commercial on two different occasions in Riverside, CA. I had so much
			fun and met great people.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media397/0003972622/th0003972622_PM_1312673377.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3972622">View My Profile</a>
			</div>
		</div>
		<p>I would like to thank Explore Talent for giving me all the help
			from your company. I got accepted to multiple Agencies! It's great to
			be a member of ET. I have been on local commercials as well. I will
			be on the cover of our Cities Plan For Success Book.The Networking
			this site brings is one of a kind and I want to say " THANK YOU
			EXPLORE TALENT"</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media256/0002561408/th0002561408_PM_1275904925.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2561408">View My Profile</a>
			</div>
		</div>
		<p>Hello Explore Talent! My experience with your site has been
			wonderful!! I've gotten so many auditions! I got an offer to do a
			tear sheet! Which is major in the modeling industry. It will be
			published in the 2010 Fashion Look Book and it will be seen
			nationally. I have an upcoming photo shoot for a magazine, billboard
			and gallery work. The pay will be $1500.00!! I also have an upcoming
			fashion show and been picked by two modeling agencies to model
			wedding dresses. This is awesome! Thank you Explore Talent. My dreams
			have come true!!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media034/0000345025/th0000345025_PM_1198023886.jpg" />
			<div>
				<a href="/profile/social/social-info/id/345025">View My Profile</a>
			</div>
		</div>
		<p>Got into Warner Brothers "Elimidate" TV Show</p>
		<p>Hi, my name is Courtney Warner and I am writing to let you guys
			know this site has made my dreams come true!! I have been getting
			auditions left and right, and I want to thank you for this
			opportunity and breaking into a "not so easy field to break into". I
			wanted to let you know I recently have been contacted by Warner
			Brothers, to audition for the hit reality T.V. show "Elimidate" and I
			landed the audition! I will be appearing on the show. So, what I can
			say to all the members of this site is Follow your heart and
			yourdreams, BELIEVE in yourself, and things will start to happen for
			you. Thanks again to a wonderful staff, in making everyone's dream a
			reality:)</p>
		<p>Best Regards, Courtney</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media485/0004855181/th0004855181_PM_1318714676.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4855181">View My Profile</a>
			</div>
		</div>
		<p>After signing up with ExploreTalent.com I have had 6 offers to
			audition for modeling and acting jobs in the last month. I got a paid
			job with Schwartzkopf Hair for a weekend gig and they want me back
			for two more shows in the future. Also, I auditioned for a print and
			commercial job this weekend in Atlanta. Waiting for good news!</p>
		<p>Thanks for giving me the boost my career needed!</p>
		<p>Megan L.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media403/0004039501/th0004039501_PM_1326490776.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4039501">View My Profile</a>
			</div>
		</div>
		<p>I wanted to Thank Explore Talent! I have had over 10 job offer for
			everything from hair modeling to movies. I am in an independent film
			as the main character. I now have a contract, and i am on my way to
			Hollywood in a few days.Without Explore Talent i would have never had
			such a huge opportunity. I happened so fast. I never thought that I
			would get back into acting again after many years of not being able
			to walk. I got back a lot more than I could ever imagine! I never
			thought that one site would get me anywhere, I was wrong. Explore
			Talent does... Thank You Explore Talent. Natalie,</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media037/0000373494/th0000373494_PM_1162337759.jpg" />
			<div>
				<a href="/profile/social/social-info/id/373494">View My Profile</a>
			</div>
		</div>
		<p>I've submitted to many casting's and was selected!</p>
		<p>I will have to compliment on the professionalism and fast
			instantaneous service that ExploreTalent.com has provided me. It is
			unlike any other service I've used with its caring staff and
			immediate help that I've received from customer service and its state
			of the art web technology that really electrifies me! It really is
			the quality of service that makes Explore Talent stand as MY NUMBER 1
			MARKETING SERVICE. I've submitted to many casting's and was selected
			by one of the WORLDS leading photographers, and Agents to work
			exclusively with them for many projects. I even met the casting
			director of General Hospital that works exclusively with my new agent
			as his assistant! If this isn't striking it big, I'll never know what
			is. I'm currently working from my home state with an e-bay project
			then I'm heading to AZ to really launch my career as my Agent works
			with only vast clients such as Abercrombie & Fitch, Calvin Klein etc.
			Thank-you EXPLORE TALENT for everything you do!</p>
		<p>Yours Truly, Joe Bryant -- Actor / Model</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media285/0002857190/th0002857190_PM_1303807860.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2857190">View My Profile</a>
			</div>
		</div>
		<p>I started out with just a 3-month membership and have already had
			almost more work than I can handle. I think the greatest thing about
			Exploretalent is the people that work there. I feel that with no
			matter what talent advisor you are assigned to, they will put you in
			the position to succeed. It almost feels like you have a step up on
			everyone else in the industry. You have countless opportunities for
			auditions and jobs, you just have to be willing to submit yourself
			for work and be hungry for the opportunities that are in front of
			you.</p>
		<p>ExploreTalent is the perfect place for me, and at this point in my
			career I could not be happier with the results.</p>
		<p>David Kanak</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media438/0004382866/th0004382866_PM_1289183583.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4382866">View My Profile</a>
			</div>
		</div>
		<p>I got my first e-mail from Explore Talent about one month after
			signing up. Someone was not only looking for a makeup artist but also
			an actress to play a role that I fit for a trailer to a movie that he
			was producing. Although there was no pay for the acting I got paid
			great for doing the makeup and had so much fun! Now the trailer for
			the movie has been bought and I am looking forward to working on the
			movie.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media087/0000872413/th0000872413_PM_1167211747.jpg" />
			<div>
				<a href="/profile/social/social-info/id/872413">View My Profile</a>
			</div>
		</div>
		<p>GOT A MOVIE ROLE AND PHOTOSHOOT IN ONE MONTH</p>
		<p>Just wanted to thank Explore Talent for their outstanding
			service!!! My daughter landed a great movie role in an upcoming
			feature film and also a great photoshoot after just one month as a
			member. Today we just heard from another director who would like to
			cast her in ANOTHER feature film!!!!Thanks so much,Alexis Banta</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media311/0003116225/th0003116225_PM_1259721872.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3116225">View My Profile</a>
			</div>
		</div>
		<p>I have been modeling for a couple of different modeling
			organizations, and I've signed up for modeling opportunities on the
			internet. Finally I have found the right one, and that is you Explore
			Talent!! I have received the part of "Emily." A main character in a
			Disney Movie!! All my life I've dreamed of a chance to act and model,
			and now my dream has come true! THANK YOU EXPLORE TALENT!</p>
		<p>Samanta Sgro</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media336/0003365574/th0003365574_PM_1278647750.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3365574">View My Profile</a>
			</div>
		</div>
		<p>When it comes to most online websites that promise you work after
			creating a profile, I had tended to be leery. But two weeks after
			creating one with Explore Talent, I heard back from a company who
			were looking for live promo event actors! I had submitted myself for
			the position, but wasn't expecting to hear back so soon! I was
			requested to attend an audition in Boston, and got CALLED BACK the
			SAME NIGHT and was offered the job! It pays up to $1600 a week, and I
			couldn't be happier at this point. But that's not all! It seems that
			ever since I landed that audition I have been offered audition, after
			audition!!! My next one is for a televised fitness show! Keep faith,
			and never stop believing in yourself and you are guaranteed success!
		</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media052/0000527569/th0000527569_PM_1169195630.jpg" />
			<div>
				<a href="/profile/social/social-info/id/527569">View My Profile</a>
			</div>
		</div>
		<p>Got a part on the Martha Stewart Show.</p>
		<p>I'm just letting you know that I signed my granddaughter up with
			explore talent 2 weeks ago and she already got a part on the Martha
			Stewart Show which will air on national TV the end of August or
			beginning of September. I'll keep you posted when I have the details.</p>
		<p>Thanks for the opportunity. This will really boost her career.
			She's only 5 years old.</p>
		<p>Rose Young</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media039/0000398387/th0000398387_PM_1156970260.jpg" />
			<div>
				<a href="/profile/social/social-info/id/398387">View My Profile</a>
			</div>
		</div>
		<p>Got a fashion job within two days of signing up!</p>
		<p>Thank you so much Explore Talent! I got a great job in a fashion
			show within two days of signing up. This program is amazing and I
			really appreciate all of the help I received from you! I followed
			just what you told me to do and before I knew it I was getting work
			and making money. I am so excited and extremely happy to be working
			with you. Thank you all for your help!</p>
		<p>- Christina Baas</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media213/0002131515/th0002131515_PM_1279768743.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2131515">View My Profile</a>
			</div>
		</div>
		<p>Got a print show in 4 days</p>
		<p>Thanks to Explore talent my son Gabriel has done a print show for
			Kids Rock which got him used to doing runway modeling and was asked
			to take pictures for a major agency to help start a new modeling
			company. But his biggest accomplishment was doing two non-profit
			commercials for Coalition for Pulmonary Fibrosis and 2Senseworth
			which paid him 75$ and got him more exposure. Thanks for everything
			and look forward to Gabriel getting even more work.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media032/0000322025/th0000322025_PM_1270623859.jpg" />
			<div>
				<a href="/profile/social/social-info/id/322025">View My Profile</a>
			</div>
		</div>
		<p>Got Century 21 commercial run on HGTV</p>
		<p>Kendra wants to thank you guys for giving her the exposure for her
			first commercial! She got role in Century 21 commercial run on HGTV,
			Thank you!</p>
		<p>I thank you too,</p>
		<p>Kathi Ike, Proud Mom =)</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media013/0000135377/th0000135377_PM_1111610827.jpg" />
			<div>
				<a href="/profile/social/social-info/id/135377">View My Profile</a>
			</div>
		</div>
		<p>Explore Talent,</p>
		<p>I wanted to thank you for your wonderful services. I really enjoy
			checking my calendar to see what new and exciting casting calls are
			listed.</p>
		<p>Because of you I was cast as a featured extra (Big Tony's sexy
			girlfriend)in the short film TKO. I hope this leads to more
			opportunities. This ExploreTalent website has been a wonderful
			experience and I tell everyone about you. Thanks again!!! Keep those
			submissions coming.</p>
		<p>Thanks for your time,Kimberly Morris</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media163/0001635605/th0001635605_PM_1304387088.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1635605">View My Profile</a>
			</div>
		</div>
		<p>I would like to share my success story! I recently had the
			opportunity to Model for Joico/Iso for Hair and Make-up. I also was a
			"Featured Artist" in a Showcase for J-Land Productions in NYC and
			they are interested in marketing my talent!!</p>
		<p>All the Best,</p>
		<p>Ashley BeardThank you Explore Talent!!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media226/0002260131/th0002260131_PM_1327467113.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2260131">View My Profile</a>
			</div>
		</div>
		<p>My daughter has a part in a short film and has only been a member
			for 18 days. She would recommend the service to anyone. She was using
			other sites for acting and now she only uses Explore Talent.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media075/0000753784/th0000753784_PM_1218959262.jpg" />
			<div>
				<a href="/profile/social/social-info/id/753784">View My Profile</a>
			</div>
		</div>
		<p>Landed a commercial that pays $500.00 for one day!</p>
		<p>Don't give up! I have had my daughter Ashley signed up with Explore
			Talent since April. We have found many, many auditions through this
			website. We just recently landed a commercial that pays $500.00 for a
			one day shoot! Ashley has a talent agency in Atlanta, GA, but since
			agencies do not always have work, this is the best way to find jobs.
			Keep on your toes; don't give up! EXPLORE TALENT finds the auditions
			that you are looking for. Keep checking in on your calendar and
			you'll find that Explore Talent has you lined up for not one, but
			several auditions. We did!! Thanks to Explore Talent Ashley got her
			first paying job!!!</p>
		<p>Sandy H.(Mom,Of Ashley H.)</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media195/0001955164/th0001955164_PM_1251701505.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1955164">View My Profile</a>
			</div>
		</div>
		<p>First of all I wanted to thank Explore talent for getting me out
			there and starting to network for jobs. I went to 3 auditions this
			past weekend, and have gotten the lead on a student film!! My first
			call-back! I also landed a role on another Indie film that willbegin
			filming the end of December! Three auditions, two call-backs. Not
			bad! I am finally on my way thanks to Explore Talent!</p>
		<p>Kristy Chamberlain</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media028/0000281929/th0000281929_PM_1307002989.jpg" />
			<div>
				<a href="/profile/social/social-info/id/281929">View My Profile</a>
			</div>
		</div>
		<p>Thank you for the job with Miller Lite</p>
		<p>I just landed a job with Miller Lite. I am promoting approx 10 hrs
			a week and making around $400 weekly . Thanks again for the leads. By
			the way this has not been the first job I have landed with your web
			site. I look forward to more jobs.</p>
		<p>Deana Aburto, 281929 Los Angeles, CA</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media076/0000766122/th0000766122_PM_1146682079.jpg" />
			<div>
				<a href="/profile/social/social-info/id/766122">View My Profile</a>
			</div>
		</div>
		<p>FIRST audition, FIRST booking...</p>
		<p>We would like to give a huge thank you to the folks at Explore
			Talent for all you do. Matthew was selected for a role in an Indie
			film "I am Dallas Lattrell" after his FIRST audition from an Explore
			Talent booking. The film will be viewed at Film Festivals. Keep up
			the good work!</p>
		<p>Matthew Spears-Heinel (Son) & Patricia Spears-Heinel (Mother)</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media386/0003862611/th0003862611_PM_1307686410.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3862611">View My Profile</a>
			</div>
		</div>
		<p>I just wanted to say thank you to Exploretalent for your
			professionalism, great staff, and the exposure I've received through
			this site! I just got my first movie role that I didn't even submit
			for, but the director saw me on Exploretalent's site and requested
			me! I auditioned and got the part. I'm so excited about starting this
			project in Spring 2011! I recommend other talents to sign up with
			Exploretalent for national exposure! Keep up the great work!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media236/0002364458/th0002364458_PM_1327468863.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2364458">View My Profile</a>
			</div>
		</div>
		<p>Thank you so much Explore Talent for this easy to use site full of
			opportunity. I signed my 6 year old daughter Chloe up for this site
			beginning April and within first two weeks went to casting for photo
			shoot ad for Jacksonville Tea House and Chloe got the part, and then
			following week went on casting with Full Sail University for a part
			as 1890's era orphan girl extra and we just finished filming it this
			past weekend.</p>
		<p>This has been a wonderful experience and greatopportunity for
			Chloe. Again--thank you so much</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media070/0000707607/th0000707607_PM_1257282049.jpg" />
			<div>
				<a href="/profile/social/social-info/id/707607">View My Profile</a>
			</div>
		</div>
		<p>I got an audition for (Deliver My Family) a live touring play. The
			audition process to me was very organized and professional. The staff
			was professional and knowledgeable. I understand that RBI Production
			is a new company with Explore Talent, and I truly believe it was well
			organized. It was a two part audition, I passed the first audition
			and was called back for the second, however, I did not receive the
			leading role for the play. The executive director is considering me
			for an upcoming film project that will be filming in early spring. He
			stated that he will contact me the beginning of March. This has been
			so far a rewarding experience to be noticed, just after 2 weeks! of
			signing on with you. I look forward to having more emails sent to me
			very soon. Thank you for all of your help!</p>
		<p>Be Well,Jennifer Hope</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media046/0000469322/th0000469322_PM_1252390743.jpg" />
			<div>
				<a href="/profile/social/social-info/id/469322">View My Profile</a>
			</div>
		</div>
		<p>I just did my first film in Lake Ariel, PA. I was working with a
			great Director and the wonderful people I've ever worked with in my
			entire small career. I was so excited and had a load of fun. I'm
			always telling people where and how I landed my auditions. I just
			want to thank exploretalent.com for helping land that job.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media080/0000803177/th0000803177_PM_1156928326.jpg" />
			<div>
				<a href="/profile/social/social-info/id/803177">View My Profile</a>
			</div>
		</div>
		<p>Within the first week of signing up for Explore Talent, I went out
			for a Discovery Channel show, got the part, and was paid around $500,
			which more than covers the cost of the site for over a year! This
			website is a useful tool to any actor.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media063/0000639256/th0000639256_PM_1271214137.jpg" />
			<div>
				<a href="/profile/social/social-info/id/639256">View My Profile</a>
			</div>
		</div>
		<p>Landed role in a film within 2 weeks!</p>
		<p>I would like to thank Explore Talent for signing up my daughter
			Terah. She has only been with Explore Talent for about 2 weeks and
			received a submission request on her calendar for a role in a feature
			film. Everything went so fast. She is new to acting/modeling. She was
			scheduled for an audition and within one week was notified that she
			got the part. She was so excited. This is her first project and it
			gave her the confidence she needs for other auditions. Thanks.</p>
		<p>Sonya Burnett</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media058/0000585803/th0000585803_PM_1327468969.jpg" />
			<div>
				<a href="/profile/social/social-info/id/585803">View My Profile</a>
			</div>
		</div>
		<p>Landed a Job for The New CW Channel</p>
		<p>Hello ExploreTalent! My name is Jaquiya Jones. I have been a member
			for only a month now. So far I have been on lots of auditions as well
			as a table reading for an Independent Film. I recently landed my
			first promotional job for The New CW Channel making some real CA!!! I
			just wanted to thank you so much; keep up the good work ...THANKS
			AGAIN</p>
		<p>- Jaquiya Jones</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media197/0001979451/th0001979451_PM_1218737331.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1979451">View My Profile</a>
			</div>
		</div>
		<p>You matched me with a role in July, got the part as a Extra in a
			short film called "A New Day". I filmed about 3 days, had a good
			time, and got to meet some new people.</p>
		<p>The producers were great and I hope to work with them again!</p>
		<p>I look forward to doing more acting, and someday that lead role
			will come.</p>
		<p>Thank you!John</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media038/0000385403/th0000385403_PM_1224142381.jpg" />
			<div>
				<a href="/profile/social/social-info/id/385403">View My Profile</a>
			</div>
		</div>
		<p>Got a lead role in a feature film !</p>
		<p>ExploreTalent has definitely opened doors for my daughter
			Christina. In the Fall, she will appear in an independent feature
			film, "Indiscretion" in one of the lead roles. She is so excited and
			we are all proud of her! I am very pleased with ExploreTalent's
			customer service. Whenever I have a question or concern, the staff is
			very professional and friendly.</p>
		<p>Keep doing an excellent job! -- Staci Carrera</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media295/0002957918/th0002957918_PM_1289685161.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2957918">View My Profile</a>
			</div>
		</div>
		<p>Looking forward to the future.</p>
		<p>I started working with Explore Talent just about a year ago. I had
			some acting experience when I was younger but throughout my adult
			life I hadn't acted at all even though I'd done public speaking as
			part of my job and outside activities. Through Explore Talent I've
			been able to do just that: explore my latent talent. I've
			participated in some amateur film projects and local community
			theater. I've also had the opportunity to do some professional
			modeling that has more than paid for my first two years of
			membership. I look forward to getting more involved and developing my
			talent and craft. Thank you, Explore Talent!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media029/0000296145/th0000296145_PM_1123735329.jpg" />
			<div>
				<a href="/profile/social/social-info/id/296145">View My Profile</a>
			</div>
		</div>
		<p>Landed a big SBC print job!</p>
		<p>Hello,</p>
		<p>I just wanted to thank Explore Talent. Sandi Smith landed me a big
			SBC print job! It was a national SBC global ad and I am getting a
			little over 1000.00.</p>
		<p>Thank you once again - Gabriela</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media027/0000279457/th0000279457_PM_1276063785.jpg" />
			<div>
				<a href="/profile/social/social-info/id/279457">View My Profile</a>
			</div>
		</div>
		<p>I got my SAG card...</p>
		<p>I use my Explore Talent URL on my resume and I faithfully check my
			calendar. I've been with Explore Talent for two years. Go to my page
			and review my two resumes! Films and Music Videos are many. I'm now a
			SAG actress. Modeling includes bookings with the AVP Tour
			(Volleyball), National Surfing Championship, Clairol - the list goes
			on and on! I don't work unless I am paid! I'm doing great booking
			jobs with Explore Talent. It's so nice to say that I am very busy!
			Thanks Explore Talent!</p>
		<p>Vanessa Ross</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media428/0004284342/th0004284342_PM_1296010317.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4284342">View My Profile</a>
			</div>
		</div>
		<p>Extra in Movie "Contagion"</p>
		<p>Ashton was excited that he finally got to be on a big production
			movie set. The movie is called "Contagion" starring Matt
			Damon,Gweneth Paltrow, Kat Winslet, Laurence Fishburne, Jude Law and
			Marion Cotlliard. We did get to meet the director Steven Soderbergh
			who is very Professional and worked well with the kids. (: Ashton got
			to be in the Shedds Aquarium shoot which was shot on October 19th and
			received his 1st paycheck last week.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media030/0000301028/th0000301028_PM_1149132993.jpg" />
			<div>
				<a href="/profile/social/social-info/id/301028">View My Profile</a>
			</div>
		</div>
		<p>Got an Allstate Print job</p>
		<p>Thank you for letting me submit to the Allstate Print, they picked
			me and I made $250.00.</p>
		<p>Victoria LewisLos Angeles, CA</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media026/0000265701/th0000265701_PM_1169199081.jpg" />
			<div>
				<a href="/profile/social/social-info/id/265701">View My Profile</a>
			</div>
		</div>
		<p>AJ Heiss got a Bounty Paper Towels commercial !</p>
		<p>Just wanted to say "Thank You" for getting AJ his last job. He just
			did a commercial for Bounty Paper Towels.</p>
		<p>Thanks,Dyanna Heiss</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media049/0000494808/th0000494808_PM_1151956936.jpg" />
			<div>
				<a href="/profile/social/social-info/id/494808">View My Profile</a>
			</div>
		</div>
		<p>I just booked a TV show!</p>
		<p>I just want to thank Explore Talent for all the auditions you've
			supplied me with. I currently just booked the TV Show "HoodLyfe".
			This is such a great opportunity for me to gain experience and get my
			face out there.Thank you again.</p>
		<p>Keyanna Hayes</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media033/0000333851/th0000333851_PM_1170731922.jpg" />
			<div>
				<a href="/profile/social/social-info/id/333851">View My Profile</a>
			</div>
		</div>
		<p>Thank you for my first job</p>
		<p>I am so excited to get my first job through you. I did my print job
			for Cellphone Co. in Austin, the photographer is famous Jack. I made
			$150.00. Thank you! Yvonne/Houston, TX</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media461/0004613552/th0004613552_PM_1307551895.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4613552">View My Profile</a>
			</div>
		</div>
		<p>I am so excited! Through Explore Talent website and with Cami's
			assistance at Explore Talent, I have some very promising auditions.
			All of this happened in a short span of one month! I encourage all
			who are submitting to dream big an stay focused.</p>
		<p>Blessed,sheridan gaines</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media002/0000029998/th0000029998_PM_1117137896.jpg" />
			<div>
				<a href="/profile/social/social-info/id/29998">View My Profile</a>
			</div>
		</div>
		<p>Got movie role in 5 days, I made $1,000. Thanks</p>
		<p>Let me tell you, in only five days I was picked up for a role in a
			movie called "Coming Attractions," shooting here in Orlando. It has
			many stars cast such as Angie Everheart (Supermodel/Bordello of
			Blood) Micheal Laslow (Beverly Hills Cop Movies) Pat Morita (Kirate
			Kid) and many more! I always knew that this site was different from
			all of the scam sites who don't even provide you with anything you
			need. Just some address to send off a headshot and resume to a
			Casting Director, or Production company when they end up throwing all
			of those out anyways. Explore Talent Allows you to book yourself.
			Thanks to everyone at Explore Talent, who helps me to have my
			submissions out right away!!</p>
		<p>April Florio</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media203/0002032653/th0002032653_PM_1220577414.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2032653">View My Profile</a>
			</div>
		</div>
		<p>My name is Mark Dent I am from New Jersey and I only been on
			Exploretalent for about 3 1/2 months and Been on 2 Auditions and my
			Second one was the one I got picked For Main Lead Role In the Movie
			TOMORROW....playing as Mike.....and I just can't wait to get started
			I just wanted to say Thank You ExploreTalent for your resources
			reaching out to me.....I hope for more work soon...So Please People
			don't give up because it's real out there. So Explore Thank you
			again....</p>
		<p>Mark Dent</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media039/0000390199/th0000390199_PM_1108616520.jpg" />
			<div>
				<a href="/profile/social/social-info/id/390199">View My Profile</a>
			</div>
		</div>
		<p>Thank you guys very much! I have been on your website for about 3
			weeks and I have already got one booking in Nashville and was signed
			to Alpha Model Group in Atlanta!!! I wouldn't have been able to get
			these without you, so I am very appreciative!</p>
		<p>Again, thank you so much! Just yesterday I had a job through you in
			Nashville, TN for ASAP Models, and because of it they want to sign me
			to their agency!!! Now, because of you guys, I have been signed to
			two non-exclusive agencies in a matter of a few weeks! That is twice
			the opportunity for more work, and then the work I will still receive
			from exploretalent.com. So in total, that is 3 times the chance of
			getting seen and one day fulfilling my dream of making it big in the
			entertainment business. Again, thank you so much! - Derek Yates,
			Chattanooga, TN</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media241/0002415154/th0002415154_PM_1247707696.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2415154">View My Profile</a>
			</div>
		</div>
		<p>I began submitting through Explore Talent at the end of February.
			In less than two months, I have been selected to be a feature model
			in a music video, asked to several auditions and am a finalist for a
			cover shoot for a national magazine. Thank you for showing all the
			opportunities that are available to me.</p>
		<p>Troy Malek</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media302/0003025909/th0003025909_PM_1259889950.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3025909">View My Profile</a>
			</div>
		</div>
		<p>I'd like to thank you Explore Talent. I have only been a member for
			two weeks and I already got my first gig! A few days after becoming a
			member I got an audition for an off Broadway show, Christmas Wizard
			of OZ. Two days later I found out I got the part! Thank you again.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media201/0002015612/th0002015612_PM_1327467829.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2015612">View My Profile</a>
			</div>
		</div>
		<p>Hi. My name is Aaron Turgeon and I am writing to tell you about all
			of the good things that have happened since I joined Explore Talent.</p>
		<p>Since I joined ET three months ago, I have had 15 auditions and 8
			call backs.I'v gotten parts in 2 independent movies, which I've
			already filmed. I got a recurring part in a new kid's tv show that we
			haven't started filming yet,but scheduled to come out this summer. I
			have also been on 2 modeling shoots for different companies. I can't
			believe how well things are going! It is unreal... Thanks Explore
			Talent</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media083/0000837875/th0000837875_PM_1327467923.jpg" />
			<div>
				<a href="/profile/social/social-info/id/837875">View My Profile</a>
			</div>
		</div>
		<p>Got a part in a Film with in a week</p>
		<p>I signed up with Exploretalent on a Tuesday, had an audition on
			Friday and a part in a Non-SAG film the following Tuesday! Since
			then, I have been contacted for auditions on two new projects. I am
			so happy that I joined Exploretalent and I look forward to a
			successful career in the entertainment industry.</p>
		<p>Kristine Quick-Reide</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media044/0000447025/th0000447025_PM_1169351213.jpg" />
			<div>
				<a href="/profile/social/social-info/id/447025">View My Profile</a>
			</div>
		</div>
		<p>I applied for a training film with the Fabian-Baber, the biggest in
			the nation and got a deal for five 25-minute DVD video-recording! I
			am getting paid $1500 in total. This is amazing for my resume and I
			now have way too much to decide what to put on my reel! Thanks!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media080/0000804555/th0000804555_PM_1272519884.jpg" />
			<div>
				<a href="/profile/social/social-info/id/804555">View My Profile</a>
			</div>
		</div>
		<p>Got a Film role on first day</p>
		<p>Only after being registered on Explore Talent for 1 day, I got a
			roll of "Zoe" in Bondage, a short film in Phoenix Az. We begin
			shooting August 5. Thanks Explore Talent.</p>
		<p>Makenna Summersett</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media196/0001968033/th0001968033_PM_1240281930.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1968033">View My Profile</a>
			</div>
		</div>
		<p>Thank you, Explore Talent. Since I have been a member, I have
			gotten several jobs from music videos, to fashion shows, to the
			latest, a lead role in a theater play called, "Will a Real Man Please
			Stand", which is in production now.Some paid and some not paid but
			good for my resume' or portfolio. All of this has been a truly
			memorable experience. Thank you for being the beginning of a new life
			for me. God Bless!!!</p>
		<p>Wardel</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media059/0000598245/th0000598245_PM_1129665910.jpg" />
			<div>
				<a href="/profile/social/social-info/id/598245">View My Profile</a>
			</div>
		</div>
		<p>Hello. I am Rushia Cooper. I recently signed up with Explore Talent
			in October. I am a 33 year old business woman, who is a mother of two
			and wife for nine years. I have always been told that I should be an
			actor because of my personality and flare for style. I didn't know
			how to break into acting from my level, no formal training or
			connections. I found the link for Explore Talent and decided to give
			it a try. I am very serious about my career but I did not want to
			waste my time or money. Speaking with Sal helped to ease my concerns.
			Every time I call with a question he is enthusiastic about helping me
			and I am grateful. I was skeptical at first but within 2 weeks of
			becoming a member I was picked to work in a Lee Jeans Promotion
			making $14.00 per hr. It's not the dream acting job I am pursuing but
			it is a start, and it shows that Explore Talent does what they
			advertise; your company is in business to promote talent, and I am
			very pleased with your services. The business cards are beautiful and
			I look forward to gaining recognition with them while promoting your
			services at the same time.</p>
		<p>Rushia Cooper</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media005/0000050351/th0000050351_PM_1099644757.jpg" />
			<div>
				<a href="/profile/social/social-info/id/50351">View My Profile</a>
			</div>
		</div>
		<p>I just want to say thanks for your site. You guys have really
			helped me in this business. I was turned down by so many agents and
			managers that I can't even count them on my fingers. I have even been
			scammed by two of them. I found my new manager that I am signed right
			now on this website from one of the auditions. I auditioned for the
			management and was signed two weeks later. I am so excited and now I
			have movies in the works and so much other projects. I couldn't be
			more happy. You guys truly are awesome and I recommend everyone and
			anyone who wants to be an actor or singer or dancer this is the place
			to be. That send you to nothing but the best auditions and take it
			from me it may take time to get accepted to most of the auditions
			that you are cast for but believe me its worth the time. Remember its
			not your choice its what has already been mapped out for you, so
			don't hesitate. Sign up for exploretalent.com and you won't be
			disappointed. Thank you once again.</p>
		<p>Kenneth Edwards</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media001/0000015636/th0000015636_PM_1072145830.jpg" />
			<div>
				<a href="/profile/social/social-info/id/15636">View My Profile</a>
			</div>
		</div>
		<p>Got a part in a SAG movie</p>
		<p>I am thrilled to have signed up with Explore Talent! I have
			alreadybooked a small part in a SAG movie which was posted on Explore
			Talent in January.</p>
		<p>Thanks for your service!!</p>
		<p>Karen GerstmanNew York City, NY</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media158/0001588795/th0001588795_PM_1203551827.jpg" />
			<div>
				<a href="/profile/social/social-info/id/1588795">View My Profile</a>
			</div>
		</div>
		<p>I've been on here for 3 days and got booked for a OJ ad and
			commercial. I get paid and I also get residuals. Thanks so muchfor
			posting so many job opportunities....</p>
		<p>Thanks,JESSE REITER</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media029/0000293238/th0000293238_PM_1099426551.jpg" />
			<div>
				<a href="/profile/social/social-info/id/293238">View My Profile</a>
			</div>
		</div>
		<p>I got a role in an up coming movie</p>
		<p>It has been a great experience being with Explore Talent. Going in
			for an audition competing amongst ourselves for role that best fits
			us leaves you with a knot in your throat when you get a call back or
			a response telling you that you got a role in the movie. Which makes
			you know that you did an excellent job at what you went in for. Of
			course you go in with butterflies in your stomach and that must be
			the main obstacle to get through but when you do your best and give
			it your all nothing can come between the passion one has for acting
			or doing what they enjoy the most. To say that I got a role in an
			upcoming movie that I got in through Explore Talent, with some
			assistance of a wonderful person of course!! The service at explore
			talent is excellent also. Their up to date calendar and in general
			the system they use. Customer service... WOW!!! Thank you so much and
			GOD BLESS!!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media464/0004643175/th0004643175_PM_1290466130.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4643175">View My Profile</a>
			</div>
		</div>
		<p>Hi, I got a job through ExploreTalent in a stage play "Family
			Secrets" as Alexandria Jones. The play is a bibical stage play and it
			was fun working with the writer and the cast.</p>
		<p>Thanks you so much!!Aysia</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media044/0000445463/th0000445463_PM_1327468679.jpg" />
			<div>
				<a href="/profile/social/social-info/id/445463">View My Profile</a>
			</div>
		</div>
		<p>My sons have done many jobs!</p>
		<p>I just wanted to Thank Explore Talent for helping Triston Coleman
			my son and Trevon Coleman my other son with pursuing their acting
			career. Because of you they have done many jobs and have just landed
			membership with a SAG Franchised Agency that will allow them to go
			anywhere to follow there dreams. Thank You!</p>
		<p>Great Thanks! Triston Coleman age 7 Trevon Coleman age 6</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media073/0000739994/th0000739994_PM_1281931568.jpg" />
			<div>
				<a href="/profile/social/social-info/id/739994">View My Profile</a>
			</div>
		</div>
		<p>Thanks for the exposure Explore Talent! I received a contract with
			Imperative Talent Management and was a part of a documentary after
			being a member for merely three weeks! Last night I even scheduled my
			first paid shoot, and I know there are many more to come. I wanted to
			give a special thanks to Brittany from Explore Talent. She helped me
			every step of the way and has given me great support and motivation!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media056/0000561471/th0000561471_PM_1179526668.jpg" />
			<div>
				<a href="/profile/social/social-info/id/561471">View My Profile</a>
			</div>
		</div>
		<p>Got a role in movie called "Shaka Muni"</p>
		<p>Thanks to Explore Talent casting, I have received a chance to
			audition for a children movie called "Shaka Muni". I was cast that
			very same day. I've only just recently finished filming this DVD. The
			producers are shopping this movie to CBS. This project has the
			potential to air as a children series. Hopefully they will succeed
			and call me back to film some more. Thanks again Explore Talent, I
			couldn't have done it without you :)</p>
		<p>Jazmine Arram</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media249/0002490549/th0002490549_PM_1239934683.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2490549">View My Profile</a>
			</div>
		</div>
		<p>I have only been with Explore Talent for one month and great things
			are happening already! I did a movie trailer with
			actor/writer/producer Walker Howard which was a lot of fun and I
			gained a lot of knowledge about making a film and being on set! Also,
			I just landed a photo shoot for a clothing line that is paying me
			$1,800 for a 6 hour shoot! I would like to give a special thanks to
			Brittaney Taylor who has been very kind and attentive to me even when
			she had some busy days! Thank you so much Brittaney and everybody
			else at Explore Talent for making my dream a reality.</p>
		<p>John West</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media277/0002770692/th0002770692_PM_1249536314.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2770692">View My Profile</a>
			</div>
		</div>
		<p>I was only on Explore Talent for four months before I got my first
			job.</p>
		<p>It was for a Fashion Show in Chicago that pays $375.</p>
		<p>If you really put yourself out there you will get noticed in time!</p>
		<p>Thanks Explore Talent!</p>
		<p>Hoping for a good show,Lenora</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media358/0003580870/th0003580870_PM_1327467435.jpg" />
			<div>
				<a href="/profile/social/social-info/id/3580870">View My Profile</a>
			</div>
		</div>
		<p>After only 2 weeks signed with Explore Talent my daughter was
			booked for a print ad. She had a blast and we look forward to working
			with Explore Talent in the future.</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media428/0004283696/th0004283696_PM_1331194015.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4283696">View My Profile</a>
			</div>
		</div>
		<p>I just got a part in the movie ' ORANGE JUMPSUIT '. We just rapped
			the movie.... And it was so fun doing the movie & the people I worked
			with were wonderful. Orange Jumpsuit was the first project I've done
			since I've been with Explore Talent. And I plan to do more movies in
			the future. I can't wait for my next Gig!!I have been Very Very Happy
			with Explore Talent &amp; I would recommend them to Everyone!</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media234/0002341629/th0002341629_PM_1233457981.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2341629">View My Profile</a>
			</div>
		</div>
		<p>Book 2 jobs in such a short time</p>
		<p>Explore Talent is the leader in obtaining quality auditions. I have
			been on over 10 auditions and landed a T.V. Pilot, a commercial, a
			feature indie film and offered to be represented by a talent agency
			for modeling and acting. Explore Talent has been beneficial in my
			success and I will continue to utilize their services.</p>
		<p>Larry A. Peterman</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media422/0004228813/th0004228813_PM_1300871203.jpg" />
			<div>
				<a href="/profile/social/social-info/id/4228813">View My Profile</a>
			</div>
		</div>
		<p>Thanks for your help to get me started right away. I got to work
			for Paul Mitchell over the weekend in the Beauty Classics. What a
			wonderful, well-organized show. Can't wait to work for them again.</p>
		<p>Tracey</p>
	</div>
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media244/0002449032/th0002449032_PM_1238034116.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2449032">View My Profile</a>
			</div>
		</div>
		<p>I landed a voice over role in an Independent Film on my first
			audition with Explore Talent.</p>
		<p>I am very happy with service and would also like to thank Justin
			for all of his help.</p>
		<p>Thanks Explore Talent!</p>
		<p>Niya</p>
	</div>
	<div style="clear: both"></div>
</div>
