<h1>
	<a href="/profile/social/social-info/id/<?php echo $this->talentname['talentnum']; ?>"><?php echo $this->talentname['fname'].' '.$this->talentname['lname']?></a>
</h1>

<div class="my_name">Edit General Profile</div>
<br>
<div id="edit_pictures">
    <ul class="nav">
        <li class="nav-one border_small"><a href="#primary_info" class="current">Upload <b>Main</b> Social Picture</a></li>
        <li class="nav-two border_small"><a href="#secondary_info">Add/Edit More Info &amp; About Me</a></li>
    </ul>

    <div class="list-wrap border_small">
        <ul id="primary_info">
            <li>
                <div class="profile_content">
                    <div class="settings_title">Upload <b>Main</b> Social Picture</div>
                    <?php echo $this->form; ?>
                    <div style="clear:both"></div>
                </div>
                <br>
                <?php if($this->imagepath != null){ ?>
                <div class="profile_content">
                    <div class="settings_title">Crop <b>Main</b> Picture</div>
                    <p><i>*Use the croping feature to optimize your <b>main</b> picture</i>. Select and drag to crop</p>
                    <br>
                    <div id="data">
                        <div class="primary_image"><img src="<?php echo $this->imagepath.'?'.time(); ?>"  id="cropbox" alt="Primary Image" /></div>
                        <div style="width:200px;height:300px;overflow:hidden;">
                            <img src="<?php echo $this->imagepath.'?'.time(); ?>" id="preview" alt="Preview" />
                        </div>

                        <form action="" method="post" onsubmit="return checkCoords();">
                            <input type="hidden" id="filename" name="filename" value="<?php echo $this->imagepath; ?>"/>
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <input type="submit" value="Crop Image" name="cropped_image_social"/>
                        </form>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <?php } ?>
            </li>
        </ul>
        <ul id="secondary_info" class="hide">
            <li>
                <div class="profile_content">
                    <div class="edit_about">
                        <div class="settings_title">Edit More Info</div>
                        <?php echo $this->editresume; ?>
                    </div>
                    <div style="clear:both"></div>
                </div>
                <br>
                <div class="profile_content">
                    <div class="edit_resume">
                        <div class="settings_title">Edit About Me</div>
                        <?php echo $this->editabout; ?>
                    </div>
                    <div style="clear:both"></div>
                </div>
            </li>
        </ul>
    </div>
</div>



<?php if($this->infoedit == 'edit'){ ?>
<script type="text/javascript">
    $(document).ready(function() {
        $('li.nav-two a').click();
    });
</script>
<?php } ?>


