<h1>
	<a href="/profile/social/social-info/id/<?php echo $this->talentname['talentnum']; ?>"><?php echo $this->talentname['fname'].' '.$this->talentname['lname']?></a>
</h1>

<div class="my_name">Edit Info</div>

<div class="profile_content border_small">
	<div class="upload_main_picture">
		<div class="settings_title">Change personal info</div>
		<?php echo $this->form; ?>
	</div>
    <div style="clear:both"></div>
</div>