<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Aaron Carter</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join" >
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/0_PX2LE-Blk?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/AaronCarter.jpg" alt="Aaron Carter" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('AARONCARTER').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Aaron Carter</div>
			</div>
			<div class="content_paragraph">
        <p>Aaron Charles Carter (born December 7, 1987) is an American singer. He is the younger brother of singer Nick Carter, from the boy band Backstreet Boys. He came to fame as a pop and hip hop singer in the late-1990s, establishing himself as a star among preteen and teenage audiences during the early-first decade of the 21st century. He has also launched an acting career.
        <a href="/industry/aaron-carter">Aaron Carter</a> was born at the Tampa General Hospital in Tampa, Florida, where his parents ran the Garden Villa Retirement Home; the family was originally from upstate New York,where his brother Nick was born. Carter is named after his maternal grandfather Douglas &quot;Charles&quot; Spaulding and paternal grandfather (Aaron Charles Carter).
        Aside from his older brother Nick, he also has three sisters: twin sister Angel (a model), BJ and Leslie. He also has an older half-sister named Ginger, from his father's first marriage, and a younger half-brother, Kaden (from his father's new marriage). He also has a younger stepsister, Taelyn, by his father's new wife. Carter has said that the mood in his home was often tense because of his parents' divorce. His parents would often argue about his money and Carter would often be in the middle of the fight, trying to stop it. Carter also remembers being pushed into show business when he was too young.
        Carter attended the Frank D. Miles Elementary School and the Ruskin School in Florida.</p>

		<p>Carter began his performing career at the age of seven, as the lead singer of a local band, Dead End. He left the band after two years because they were leaning towards alternative music and he wanted to do pop. He made his first solo appearance, singing a cover of The Jets' &quot;Crush on You,&quot; when opening for the Backstreet Boys in Berlin in March 1997. The performance was followed by a record contract, and in the fall of 1997, he released his first single, &quot;Crush on You.&quot; His first full-length album was released on December 1, 1997. The eponymous debut album achieved gold status in Norway, Spain, Denmark, Canada, and Germany, and was released in the United States on June 16, 1998.
        On November 17, 1996, Carter released the EP Let The Music Heal Your Soul. The record was a fund-raising project that featured vocals by Carter, The Backstreet Boys, 'N Sync, The Moffatts, and other artists (collectively referred to as the &quot;Bravo All Stars&quot; after the German youth magazine Bravo).
        Carter's parents later filed a lawsuit against his former manager, Lou Pearlman (now in federal prison for major fraud), alleging failure to pay hundreds of thousands of dollars in royalties on Carter's 1998 album, which was released through Pearlman's label and production company, Trans Continental. On March 13, 2003, Pearlman was declared in contempt of court for ignoring a court order to produce documents relating to royalty payments.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Aaron Carter? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/black-eyed-peas">Black Eyed Peas</a></div>
				<div><a href="/industry/david-banner">David Banner</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


