<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Ariel Tweto</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/sE_8R4XOMvc?fs?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/ariel_tweto.jpg" alt="Ariel Tweto" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('ArielTweto').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/industry//join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Ariel Tweto</div>
			</div>
			<div class="content_paragraph">
				<p>Ariel Eva Tundraq Atauchiaq Tweto. I am from Unalakleet, Alaska but right now she go to school at Chapman University in Orange County. She go to major in communications and minor in broadcast journalism. she love talking to people, meeting people, getting lost, and exploring.
				<a href="/industry/ariel-tweto">Ariel Tweto</a> first gained national attention when she appeared as a contestant on ABC's "Wipeout."  Ariel was the first shown to clear the Big Balls, but is more famous for her blooper on the Pole Vault, where she couldn't spot the 30' pole that was right in front of her.  Ariel returned for the All-Star Edition of 'Wipeout,' was referred to as Ariel "Never Been Kissed" Tweto.
				Ariel is an actress who stars in the Discovery Chanel reality docu-series. Ariel (Flying Wild Alaska) She is a member  of the ground crew for the airline ERA Alaska.
				Ariel Tweto was born in 1987, growing up in Unalakleet Alaska and followed in the footsteps of her hard working parents. Ariel Tweto (Flying Wild Alaska) was known around town for being a fierce  competitor on her high school's co-ed wrestling team!</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">Be like Ariel Tweto</div>
			</div>
			<div class="content_paragraph">
				<p>Like her  mother, Ariel Tweto competed in cross-country, and has run every day  since May of 2002. One of Ariel Tweto's most vivid memories was when  she shot her first caribou with her grandma at age 9. The recoil from  the gun was so strong that Ariel Tweto was left with a black  eye.Ariel Tweto is the only member of the family who does not have a  pilot's license.
				If  you would like to become a reality star like Ariel Tweto, the first  step is to develop an acting or modeling portfolio complete with a  headshot, body shots and a resume.
				Ariel  Tweto tells of success as an actress. www.exploretalent.com Ariel is  a member of Explore Talent and has appeared on reality and network  television shows and also in an upcoming movie release. She is  currently in development talks for two upcoming television  shows.<br>
				-Ariel  Tweto </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/industry//join/flash">Interested in Becoming Famous TV
				Personality like Ariel Tweto? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/1pic1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/1pic2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/1pic3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/1pic4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/1pic5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/karina-smirnoff">Karina Smirnoff</a></div>
				<div><a href="/industry/sean-kingston">Sean Kingston</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


