<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table width="auto" class="border_small">
	<tr>
		<td valign="top" align="left" class="vid-quest-head2"><h2>Madisen Beatty from <em>The Curious Case of Benjamin
			Button</em></h2></td>
	</tr>
	<tr>
		<td valign="top" align="center" style="padding-top:10px">
			<div id="outerdiv" align="center">
				<iframe title="YouTube video player" width="560" height="349"
						src="http://www.youtube.com/embed/vd6N7-0D20g" frameborder="0" allowfullscreen></iframe>
			</div>
		</td>
	</tr>
	<tr>
		<td valign="top" align="left" style="padding:10px 40px">
			<p>Oscar nominated best picture <em>The Curious Case of Benjamin Button</em> actress Madisen Beaty gives an
				exclusive interview to Explore Talent. The film won three Oscar awards at the 81st Academy Awards.</p>
		</td>
	</tr>
	<tr>
		<td valign="top" ><a href="/industry/celebrities-exclusive-interviews" style="text-decoration:none"><span
				class="vid-head">More Celebrity Videos</span></a></td>
	</tr>
	<tr>
		<td valign="top" style="border:1px solid #009900; padding:2px"><br>
			<table >
				<tr>
					<td  valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/snoop-dogg"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-snoopdogg-150.jpg" width="150" height="131"
										border="0"
										alt="Snoop Dogg gives advice exclusively to Explore Talent members from his trailer on the set of his new variety show on MTV - Dogg After Dark"/></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Snoop Dogg</p>

									<p>Snoop Dogg on the set of MTV's "Dogg After Dark" Join ExploreTalent - "Get hooked
										up"</p></td>
							</tr>
						</table>
						<br>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/adele"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-adele-150.jpg"
										alt="Adele Grammy Award Winner 2009 Best New Artist Interview" width="150"
										height="131" /></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Adele</p>

									<p>Adele, Grammy award winner for best new artist, gives an exclusive interview with
										Explore Talent. Adele gives tips for up and coming new talents.</p></td>
							</tr>
						</table>
						<br>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/karadioguardi"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-karadioguardi-150.jpg" width="150" height="131"
										border="0"
										alt="Kara DioGuardi, American Idol's newest judge, gives an exclusive interview with Explore Talent"/></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Kara DioGuardi</p>

									<p>American Idol's newest judge's exclusive interview with Explore Talent. Her
										advice is to be bold, different and unique. The best thing to do as a songwriter
										or talent is to find a great producer.</p></td>
							</tr>
						</table>
						<br>
						<br/>
					</td>
					<td width="5">&nbsp;</td>
					<td  valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/joan-rivers"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-joanrivers-150.jpg" width="150" height="131"
										border="0" alt="Joan Rivers Celebrity Apprentice"/></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Joan Rivers</p>

									<p>Explore Talent exclusive interview with Celebrity Apprentice winner Joan
										Rivers.</p></td>
							</tr>
						</table>
						<br/>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/jonasbrothers"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-jonasbrothers-150.jpg" width="150" height="131"
										border="0" alt="Jonas Brothers Exclusive Interview with Explore Talent"/></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Jonas Brothers</p>

									<p>Jonas Brothers give tips and advice to young talents in this exclusive interview
										with Explore Talent. </p></td>
							</tr>
						</table>
						<br>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/dave-grohl"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-davegrohl-150.jpg" border="0"
										alt="Dave Grohl of the Foo Fighters Interview exclusively for ExploreTalent"/></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Foo Fighters - Dave Grohl</p>

									<p>Dave Grohl of the Foo Fighters gives advice to aspiring musicians in an exclusive
										interview for Explore Talent.</p></td>
							</tr>
						</table>
						<p align="right"><a href="/industry/celebrities-exclusive-interviews">See all Celebrity Interviews</a></p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
