<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Black Eyed Peas</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/p2fE-oDuqWI?fs?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/black_eyed_peas.jpg" alt="Black Eyed Peas" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('bep').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Black Eyed Peas</div>
			</div>
			<div class="content_paragraph">
				    <p>The <a href="/industry/black-eyed-peas">Black Eyed Peas</a> is an American hip hop group that formed in Los  Angeles, California in 1995. The group is composed of rapper and  multi-instrumentalist will.i.am, rappers apl.de.ap and Taboo, and  singer-rapper Fergie.
					The group scored its first worldwide hit with &quot;Where Is the Love?&quot; in 2003, which topped over ten charts  worldwide. The group recently performed at halftime at the Super Bowl in Dallas and have been seen on several music award shows including  the Grammy's and The American Music Awards.
					In the always-changing music industry that's defined by minimal  expectations, a &quot;successful&quot; career means having one, maybe  two hit records. The Black Eyed Peas are a glorious exception. They  have become one of the best selling, most popular and most innovative  groups for over a decade.
					They have transformed themselves from a  beloved backpack rap troop from the West Coast Underground into  fully-fledged, massive global superstars whose music can be heard in  any country around the world.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">Black Eyed Peas New Album</div>
			</div>
			<div class="content_paragraph">
					<p>They&acute;ve  done this the right way: creating albums that are more innovative  than the last; which has translated into each new album being more  popular than the last. And in following this pattern, The Black Eyed  Peas will soon be releasing their sixth full-length album, The  Beginning.
					The Beginning follows on the heels of 2009&acute;s The E.N.D., BEP&acute;s most  popular and most creative album to date - and the album that reaffirmed their singular status as global music icons. The E.N.D  sold more than 11 million copies worldwide; it entered the Billboard  Top 200 Chart at #1 outperforming their previous cd, Monkey Business - an unheard of feat in this day and age.
					Black Eyed Peas new Song Someday (KNIGHT AND DAY Theme) for Upcoming Tom Cruise/Cameron Diaz Movie. Today, will.i.am and Tom Cruise announced today that the Black Eyed Peas have written a special song titled "Someday" for the upcoming movie "Knight and Day" starring Tom Cruise and Cameron Diaz. </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Black Eyed Peas? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/pic1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/pic2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/pic3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/pic4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/pic5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/sean-kingston">Sean Kingston</a></div>
				<div><a href="/industry/usher-raymond">Usher Raymond</a></div>
			</div>
		</td>
	</tr>
</table>


