<h1>Exclusive Celebrity Interviews & Advice</h1>

<p class="celeb_main_paragraph">
    Welcome to Explore Talent's Exclusive Celebrity Interviews & Advice! Where Explore Talent brings you the brightest entertainment stars and celebrities in the entertainment business today. Explore Talent has gathered some of the hottest actors, models, singers, dancers and musicians in the world to share their insights and secrets for success. Check out the videos and interviews available here to see the latest in celebrity tips, tricks, trends and advice to help make your entertainment career a success!
</p>
<br>
<div class="border_small">
    <div class="celeb_title">Bobby Banhart</div>
    <div>
        <div class="celeb_video"><iframe width="334" height="270" src="https://www.youtube.com/embed/M5s5TLqlOwI" frameborder="0" allowfullscreen></iframe></div>
        <div class="celeb_video">
            <iframe width="334" height="270" src="https://www.youtube.com/embed/RWvewJOUgLE" frameborder="0" allowfullscreen></iframe>
            <p class="celeb_paragraph">Explore Talent exclusive interview with Singer / Songwriter Usher.</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">Snoop Dogg - Recommends</div>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-snoopdogg-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Snoop Dogg</div>
            <p class="celeb_paragraph">Snoop Dogg on the set of MTV's "Dogg After Dark" Join ExploreTalent - "Get hooked up"</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-carlosmcswain-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Carlos McSwain, Snoop Dogg's Drummer</div>
            <p class="celeb_paragraph">Advice from Snoop Dogg's drummer to Explore Talent members.</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">Celebrity Apprentice Finale</div>
    <p>Celebrity interviews at the finale of Celebrity Apprentice in New York City.</p>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-joanrivers-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Joan Rivers</div>
            <p class="celeb_paragraph">Explore Talent exclusive interview with Celebrity Apprentice winner Joan Rivers.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-piersmorgan-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Piers Morgan</div>
            <p class="celeb_paragraph">Piers Morgan gives an exclusive interview to ExploreTalent.com</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">Beverly Hills Film Festival 2009</div>
    <p>Celebrity interviews at Clarity Theater in Beverly Hills. Interviews include two-time academy award winning cinematographer Haskell Wexler (America America, One Flew Over the Cuckoo's Nest, Bound for Glory, Who's Afraid of Virginia Woolf? and Coming Home), and Antonio Sabato, Jr., star of the festival film Drifter: Henry Lee Lucas.</p>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-bhff1-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Beverly Hills Film Festival</div>
            <p class="celeb_paragraph">Interviews on the red carpet</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-steve-o-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Steve-O</div>
            <p class="celeb_paragraph">Steve-O exclusive interview at the Beverly Hills International Film Festival</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-michael-lohan-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Michael Lohan</div>
            <p class="celeb_paragraph">Michael Lohan at the Beverly Hills International Film Festival</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-red-carpet-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Red Carpet Posture</div>
            <p class="celeb_paragraph">Tips and advice for how to walk the red carpet</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-jackiewatson-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Jackie Watson</div>
            <p class="celeb_paragraph">Jackie Watson writer-producer of Wanna Be Me. Jackie Watson talks to Explore Talent about the genesis of her feature film.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-dwaine-stevenson-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Dwaine Stevenson</div>
            <p class="celeb_paragraph">Dwaine Stevenson at the Beverly Hills Film Festival.</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">Oscars</div>
    <p>Exclusive interviews with the stars of Academy Award nominated films.</p>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-anilkapoor-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Slumdog Millionaire star Anil Kapoor</div>
            <p class="celeb_paragraph">Explore Talent exclusive interview with Anil Kapoor, star of the Oscar winning film Slumdog Millionaire.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-chevychase-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Chevy Chase</div>
            <p class="celeb_paragraph">Chevy Chase gives an exclusive interview to ExploreTalent.com. Chevy gives advice to upcoming talents. You should write and hope for luck.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-michaelsheen-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Frost/Nixon star Michael Sheen</div>
            <p class="celeb_paragraph">Academy Award nominated best picture Frost/Nixon actor Michael Sheen gives an exclusive interview to Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-madisenbeaty-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Madisen Beaty from The Curious Case of Benjamin Button</div>
            <p class="celeb_paragraph">Madisen Beaty gives an exclusive interview to Explore Talent.</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">Grammy's</div>
    <img style="float: left;" src="<?php echo CDN_JS_CSS; ?>/images/celebs/musicares.gif" />
    <p>Hollywood, Calif. (Feb. 6th, 2009) - ExploreTalent.com in conjunction with the MusicCares Foundation is sponsoring the 2009 gala at the MusicCares Person of the Year gala dinner, award ceremony and benefit concert for official Grammy Week of the 51st Annual GRAMMY Awards. GRAMMY-winning recording artist Neil Diamond will be honored as the 2009 MusiCares Person of the Year.
        Proceeds from the annual GRAMMY Week gala dinner and concert honoring Diamond will provide essential support for MusiCares, which ensures that music people have a place to turn to in times of financial, medical and personal need. The MusiCares Person of the Year tribute ceremony is one of the most prestigious events held during GRAMMY Week.</p>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-jonasbrothers-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Jonas Brothers</div>
            <p class="celeb_paragraph">Jonas Brothers give tips and advice to young talents in this exclusive interview with Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-adele-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Adele</div>
            <p class="celeb_paragraph">Adele, Grammy award winner for best new artist, gives an exclusive interview with Explore Talent. Adele gives tips for up and coming new talents.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-davegrohl-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Foo Fighters - Dave Grohl</div>
            <p class="celeb_paragraph">Dave Grohl of the Foo Fighters gives advice to aspiring musicians in an exclusive interview for Explore Talent</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-karadioguardi-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Kara DioGuardi</div>
            <p class="celeb_paragraph">American Idol's newest judge's exclusive interview with Explore Talent. Her advice is to be bold, different and unique. The best thing to do as a songwriter or talent is to find a great producer.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-ericbenet-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Eric Benet</div>
            <p class="celeb_paragraph">Eric Benet, R & B star, gives an exclusive interview with Explore Talent. Hear advice for upcoming musicians.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-patboone-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Pat Boone</div>
            <p class="celeb_paragraph">Pat Boone, actor-singer-writer, gives tips to young musicians in this exclusive interview with Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-johnstamos-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">John Stamos</div>
            <p class="celeb_paragraph">John Stamos talks to Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-cassandrawilson-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Cassandra Wilson</div>
            <p class="celeb_paragraph">Cassandra Wilson, Grammy Award winning jazz singer and songwriter, gives an exclusive interview with Explore Talent. She encourages young talents to be true to their dreams and find their own voice.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-terenceblanchard-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Terence Blanchard</div>
            <p class="celeb_paragraph">Terence Blanchard, Grammy Award winning jazz trumpeter, gives an exclusive interview with Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-donwas-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Don Was</div>
            <p class="celeb_paragraph">Don Was, record producer and performer, gives an exclusive interview and advice to new musicians. He encourages all musicians to perform live as much as possible.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-eddierodriquez-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Los Volcanes</div>
            <p class="celeb_paragraph">Los Volcanes give exclusive interviews with Explore Talent.</p>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/thumb-urgeoverkill-150.jpg" width="150" height="131" /></a>
            <div class="celeb_title">Urge Overkill</div>
            <p class="celeb_paragraph">Urge Overkill gives an exclusive interview with Explore Talent.</p>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <div class="celeb_title">More Celebrities at the Explore Talent Booth</div>
    <div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/slide-chris-cornell.jpg" width="249" height="200" /></a>
            <div class="celeb_title">Chris Cornell</div>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/slide-neil-diamond.jpg" width="249" height="200" /></a>
            <div class="celeb_title">Neil Diamond</div>
        </div>
        <div class="celeb_video">
            <a class="celeb_img"><img src="<?php echo CDN_JS_CSS; ?>/images/celebs/slide-meat-loaf.jpg" width="249" height="200" /></a>
            <div class="celeb_title">Meat Loaf</div>
        </div>
    </div>
    <div style="clear: both;"></div>
</div>

<div class="border_small">
    <img src="<?php echo CDN_JS_CSS; ?>/images/celebs/et-signatures.jpg" width="750" height="371"/>
</div>