<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>David Alan Grier</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="joina">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/vH7nhw5GfR4?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier_main.jpg" alt="David Alan Grier" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('davidalangrier').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About David Alan Grier</div>
			</div>
			<div class="content_paragraph">
			<p>David Alan Grier was born June 30, 1956. He is also known as "D.A.G." (DAG). He is an American actor and comedian who became famous for his work on the sketch comedy television show 'In Living Color.'
				<a href="david-alan-grier" title="David Alan Grier">David Alan Grier</a> was born Detroit and graduated from Detroit's magnet high school, Cass Tech He received a B.A. from the University of Michigan, and an M.F.A. from the Yale School of Drama. Immediately after graduating, he landed the role of Jackie Robinson in the short-lived Broadway musical The First, directed by Martin Charnin and written by Joel Siegel.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from David Alan Grier</div>
			</div>
			<div class="content_paragraph">
			<p>Grier got his start on the National Public Radio radio drama adaptation of Star Wars in 1980. He was the voice of a nameless X-Wing fighter pilot during the Battle of Yavin.
				Grier was nominated for a Tony Award for Best Featured Actor in a Musical and won the Theatre World Award for The First. He later starred as James "Thunder" Early in the hit Broadway musical Dreamgirls. Grier made his film debut in 1983 in Streamers, directed by Robert Altman. He won the Golden Lion for Best Actor at the Venice Film Festival for the film. He also appeared in the Negro Ensemble Company production A Soldier's Play and reprised his role in the film version A Soldier's Story. Grier also appeared as a geology professor at the fictitious Hillman College in the show A Different World where he was a crush of several of the girls on the show including lead character Denise Huxtable played by actress Lisa Bonet.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like David Alan Grier? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/david_alan_grier5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/usher-raymond">Usher Raymond</a></div>
				<div><a href="/industry/grabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/matt-damon">Matt Damon</a></div>
			</div>
		</td>
	</tr>
</table>


