<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
    <tr>
        <td class="name_title"><h2>Gabrielle Union</h2></td>
        <td>
            <div class="joinbutton"><a href="/join/flash">
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
            </div>
        </td>
    </tr>
</table>

<table class="industry_header">
    <tr>
        <td>
            <iframe title="YouTube video player" width="290" height="242"
                    src="http://www.youtube.com/embed/UKrU6lisVvs?rel=0" frameborder="0" allowfullscreen></iframe>
        </td>
        <td>
            <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-205x295.jpg" alt="Gabrielle Union"
                 name="profile_pic"
                 id="profile_pic"/>
        </td>
        <td>
            <div id="twitter_container">
                <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
                    <script type = "text/javascript" >
                            new TWTR.Widget({
                                version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
                                theme:{
                                    shell:{background:'#009dff', color:'#ffffff'},
                                    tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
                                },
                                features:{
                                    scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
                                }
                            }).render().setUser('itsgabrielleu').start();
                </script>
            </div>
        </td>
    </tr>
</table>

<table class="industry_add">
    <tr>
        <td>
            <a href="/join/flash" target="_blank" class="join_link">
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30"/>
            </a>
        </td>
        <td>
            <div class="celeb-ad">
                <script type="text/javascript">
                    <!--
                    google_ad_client = "pub-7367493847549945";
                    /* 468x60, created 1/26/11 */
                    google_ad_slot = "3706098432";
                    google_ad_width = 468;
                    google_ad_height = 60;
                    //-->
                </script>
                <script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                </script>
            </div>
        </td>
    </tr>
</table>

<table class="industry_body">
    <tr>
        <td>
            <div class="content_title">
                <div class="title_text">About Gabrielle Union</div>
            </div>
            <div class="content_paragraph">
                <p>Gabrielle Monique Union (born October 29, 1972) is an American actress and former model. Among her
                    notable roles is as the cheerleader opposite Kirsten Dunst in the film Bring it On. <a
                            href="/industry/gabrielle-union">Gabrielle Union</a> starred opposite Will Smith and Martin
                    Lawrence in the blockbuster film Bad Boys II and played a medical doctor in the CBS drama series
                    City of Angels.
                    She starred with LL Cool J and Meagan Good in Deliver Us from Eva in 2003. Gabrielle Union was born
                    in Omaha, Nebraska, the daughter of Theresa and Sylvester Union. She was raised Catholic. At the age
                    of eight, her family moved to Pleasanton, California, where she grew up and attended Foothill High
                    School. In high school, Gabrielle Union was an all-star point guard in basketball and a year-round
                    athlete, also playing in soccer and running track.
                    Gabrielle Union attended the University of Nebraska before moving on to Cuesta College. Gabrielle
                    Union eventually transferred to UCLA and earned a degree in sociology. While studying there, she
                    interned at the Judith Fontaine Modeling &amp; Talent Agency to earn extra academic credits. Invited
                    by the agency's owner, Judith Fontaine, Gabrielle Union started working as a model to pay off
                    college loans.
                    Gabrielle Union started her acting career in minor roles. Most were in teen movies such as 10 Things
                    I Hate About You and Love and Basketball. In 1997, Gabrielle Union appeared in a sixth-season
                    episode of Star Trek: Deep Space Nine as the Klingon N'Garen. She also appeared in Sister, Sister as
                    Vanessa, in Smart Guy as Denise, and in five episodes of 7th Heaven as Keesha Hamilton. In 2000,
                    Gabrielle Union landed the role of Isis in the cheerleading movie Bring it On opposite Kirsten
                    Dunst. Bring It On helped push into the mainstream and she began gaining more exposure. This led to
                    Gabrielle Union being cast in the CBS television drama City of Angels as Dr. Courtney Ellis.
                    Gabrielle Union was cast in her first leading role in the 2003 film Deliver Us from Eva with rapper
                    L.L. Cool J.</p>
            </div>
        </td>
        <td>
            <div class="content_title">
                <div class="title_text">A few words from Gabrielle Union</div>
            </div>
            <div class="content_paragraph">
                <p>This was her second time working with the rapper since making a cameo in his video &quot;Paradise&quot;
                    in 2002. The film received fair reviews from critics and it showed that Gabrielle Union was a
                    leading lady. Gabrielle Union landed the role of Will Smith's girlfriend Syd in the film Bad Boys
                    II, a box office success grossing over $273 million worldwide.
                    Gabrielle Union starred with Academy Award winner Jamie Foxx in the film Breakin' All the Rules in
                    2004. Gabrielle Union starred in the short-lived 2005 ABC series Night Stalker. She has also starred
                    in the independent drama films Neo Ned and Constellation, the latter of which was released to
                    theaters. She won an award for Best Actress in Neo Ned at the Palm Beach International Film
                    Festival, and the film received awards at several festivals. She starred in the 2005 remake of The
                    Honeymooners with comedian Cedric The Entertainer. In 2006, she starred as Busta Rhymes' love
                    interest in the music video for Rhymes' &quot;I Love My Chick.&quot;
                    Gabrielle Union starred in the 2007 films Daddy's Little Girls by <a href="/industry/tyler-perry">Tyler
                        Perry</a> (released on Valentine's Day) and the Christmas film The Perfect Holiday which opened
                    on December 12. In an interview with Art Nouveau Magazine, Gabrielle Union complained about the lack
                    of roles for black actresses and actors in Hollywood: &quot;There used to be specifically written
                    black, if you knew Denzel was doing a movie you knew his wife, girl or love interest was going to be
                    black but that's not necessarily the case anymore. You're in that room with every amazingly talented
                    actress of every hue, and it's a dogfight, it's hard.&quot;
                    In 2008, Union appeared on Ugly Betty for 3 episodes (36-38) as Renee, Wilhelmina Slater's (Vanessa
                    L. Williams) sister and Daniel Meade's (Eric Mabius) love interest. She also made a cameo appearance
                    in the music video for Ne-Yo's &quot;Miss Independent.&quot; She joined the cast of the U.S.
                    television series Life on NBC and appeared in four episodes prior to the cancellation of series in
                    May 2009. She appears in the ABC series FlashForward alongside John Cho and Joseph Fiennes which
                    premiered on September 24, 2009. </p>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="become_famous">
            <a href="/join/flash">Interested in Becoming Famous TV
                Personality like Gabrielle Union? Click Here to Start Your Career!</a>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div class="content_title">Photos</div>
            <div class="photo_container">
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-1.jpg" width="124" height="164"
                     class="profile_pic"/>
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-2.jpg" width="124" height="164"
                     class="profile_pic"/>
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-3.jpg" width="124" height="164"
                     class="profile_pic"/>
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-4.jpg" width="124" height="164"
                     class="profile_pic"/>
                <img src="<?php echo CDN_JS_CSS; ?>/images/industry/gabrielle_union-5.jpg" width="124" height="164"
                     class="profile_pic"/>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div class="content_title">Other Celebrities</div>
            <div class="other_celebs">
                <div><a href="/industry/piers-morgan">Piers Morgan</a></div>
                <div><a href="/industry/trey-songz">Try Songz</a></div>
                <div><a href="/industry/tyler-perry">Tyler Perry</a></div>
            </div>
        </td>
    </tr>
</table>


