<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2">Guns N' Roses</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/xOHI5c9oraw?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/guns_n_roses.jpg" alt="Guns N' Roses" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('gunsnroses').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Slash from Guns N' Roses</div>
			</div>
			<div class="content_paragraph">
				<p>Saul Hudson (born July 23, 1965), better known by his stage name <a href="/industry/guns-n-roses">Slash from Guns N' Roses</a>, is a British-American musician. He is the former lead guitarist of the American hard rock band Guns N' Roses, with whom he performed and recorded between 1985 and 1996. He later formed Slash's Snakepit and co-founded Velvet Revolver with his former band mates Duff McKagan and Matt Sorum, and his debut solo album, Slash, was released in April 2010.
					Slash from Guns N' Roses has received critical recognition as a guitarist. In August 2009, Time Magazine ranked him #2 on its list of the &quot;10 Best Electric Guitar Players of All-Time&quot;. He was also ranked #21 on Gigwise's list of the &quot;50 Greatest Guitarists Ever.&quot;
					In June 1985, Slash and Steven Adler were invited to join with Axl Rose, Duff McKagan and Izzy Stradlin as the band Guns N' Roses.
					Guns N' Roses toured bars and opened for larger acts throughout 1985 and 1986. It was during this period that they wrote most of their classic material, including &quot;Welcome to the Jungle,&quot; &quot;Sweet Child o' Mine,&quot; and &quot;Paradise City.&quot; During this time, they were scouted by several major record labels, and signed with Geffen and they were tagged the &quot;Most Dangerous Band In The World.&quot;</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">More on Slash</div>
			</div>
			<div class="content_paragraph">
				<p>After his departure from Guns N' Roses, Slash focused on his side-project, Snakepit, playing a few tour dates before disbanding the group in 1998. Over the next decade, Slash became an in-demand session musician, recording music with the likes of Bob Dylan, Alice Cooper, Sammy Hagar, Insane Clown Posse, Ronnie Wood, Bad Company, Cheap Trick, Michael Jackson, and Ray Charles.</p>
				<p>In 1990, Slash from Guns N' Roses was contacted by Michael Jackson to work on his upcoming album, Dangerous. Slash played lead guitar on the single &quot;Give In to Me;&quot; he also appeared in the music video of the latter. He also played guitar on &quot;Black or White.&quot; On several occasions, Slash from Guns N' Roses appeared onstage with Jackson, performing &quot;Black or White&quot; during the Dangerous World Tour.
					Slash and Jackson appeared together at the MTV 10th Anniversary in 1991, where Michael and Slash performed &quot;Black or White&quot; live for the first time and at 1995 MTV Video Music Awards where Michael performed a medley of his hits while Slash played guitar for &quot;Black or White.&quot;</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Guns N' Roses? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-1-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-2-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-3-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-4-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-5-123x164.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/gabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
			</div>
		</td>
	</tr>
</table>


