<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table width="auto" class="border_small">
<tr>
    <td height="38" align="center" valign="top"><strong>Hip Hop and R&amp;B Interviews &amp;Advice</strong>
        <br/>
        <br/>
        Welcome to Explore Talent's Exclusive Hip Hop and R&amp;B Interviews and Advice page! Explore Talent has
        gathered some of the hottest singers, songwriters, rappers and all-around musicians in the urban music business
        to share their tips for success as well as reminiscing about the fun and crazy times they've encountered during
        their career paths along the way. So check out Explore Talent's interviews available here to see the latest and
        greatest in tips, trends, advice and fun anecdotes coming straight from the biggest names in the urban music
        world themselves to help you make your music career a fun and exciting venture!
        <br/>
        <br/>
    </td>
</tr>

<tr>
    <td valign="top"><span class="vid-head"> </span></td>
</tr>
<tr>
<td valign="top" style="border:1px solid #009900; padding:2px">

    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/rayjinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_rayj_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Ray J exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Ray J </p>

                            <p>Ray J's exclusive interview with ExploreTalent. Musician-Actor-Producer, Ray J, gives tips to
                                musicians and actors about how to "make it" in the entertainment industry.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/beyedpinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_bleypeas_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Polo Molina exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Black Eyed Peas </p>

                            <p>Polo Molina and Venus Brown talk with ExploreTalent. Watch this exclusive interview from the
                                81st Grammy Awards with Polo Molina of the Black Eyed Peas and Venus Brown.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/snoop-dogg"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-snoopdogg-150.jpg" width="150"
                                height="131" border="0"
                                alt="Exclusive interview with Snoop Dogg in his trailer on the set of his new variety show on MTV Dogg After Dark"/></a>
                        </td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Snoop Dogg</p>

                            <p>Snoop Dogg, on the set of MTV's "Dogg After Dark," gives his two cents why you will get
                                "hooked up" by joining ExploreTalent.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/snoop-doggdrummer"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-carlosmcswain-150.jpg" width="150"
                                height="131" border="0"
                                alt="Snoop Dogg's drummer Carlos McSwain"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Carlos McSwain, Snoop Dogg's Drummer</p>

                            <p>Snoop Dogg's drummer passes along his experience and advice to ExploreTalent's members.</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/souljaboyinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_souljaboy_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Soulja Boy exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Soulja Boy </p>

                            <p>Soulja Boy interviews with ExploreTalent at the 2009 BET Awards, talking about making music
                                while passing along some sound advice to up and coming musicians.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/ericbenet"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-ericbenet-150.jpg" width="150"
                                height="131" border="0"
                                alt="Exclusive interview with Eric Benet"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Eric Benet </p>

                            <p>Hear Eric Benet's advice for upcoming musicians in this exclusive interview. His albums
                                include "Love and Life," "Hurricane"; and his platinum selling album, "A Day In The
                                Life."</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/methodmaninterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_methodman_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Method Man exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Method Man </p>

                            <p>Musician1.com's interview with Method man.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/redmaninterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_redman_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Redman exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Redman </p>

                            <p>Redman talks to Musician1.com prior to a private Method Man-Redman show in Hollywood,
                                promoting their new record, "Blackout 2."</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/bmcknightinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_bmcnkight_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Brian McKnight exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Brian McKnight </p>

                            <p>Brian McKnight gives tips to budding musicians in this ExploreTalent interview. Brian tells
                                his story of how he made it in the "biz" and passes along career advice to up and coming
                                musicians and songwriters.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/albsureinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_albsure_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Al B Sure exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Al B Sure </p>

                            <p>Al B Sure gives musical advice to ExploreTalent's listeners.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/mariointerview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_mario_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Mario exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Mario</p>

                            <p>Mario's exclusive interview with Musician1.com. Mario gives advice to new and up and coming
                                musicians.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/swayinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_sway_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Sway exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Sway </p>

                            <p>Sway, the infamous Host from MTV News and "Total Request Live," gives a shout out to
                                Musician1.com!</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/djdramainterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_djdrama_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="DJ Drama exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">DJ Drama</p>

                            <p>DJ Drama gives musical advice to aspiring young talent.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/wutanginterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_wusystem_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Wu Tang exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Wu Tang Clan </p>

                            <p>Bass player Shavo from "System of a Down" does an interview with his friends from Wu Tang
                                Clan, RZA, Achozen, Black Knights and GraveDiggaz.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/jadakissinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_jadakiss_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Jadakiss exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Jadakiss</p>

                            <p>Jadakiss exclusive interview with Musician1.com.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/envogueinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_nvogue_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="En Vogue exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">En Vogue </p>

                            <p>The group En Vogue interviews with ExploreTalent. En Vogue talks about being reunited and
                                gives tips to up and coming musicians.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/bobbybrowninterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_bobbybrown_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Bobby Brown exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Bobby Brown </p>

                            <p>Bobby Brown and Ralph Tresvant (New Edition, Heads Of State) interview from the BET Awards
                                2009 red carpet. Bobby and Ralph give a tribute to Michael Jackson and tips for up and
                                coming new musicians. </p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/johnnygilinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_jgill_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Johnny Gil exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Johnny Gil </p>

                            <p>Johnny Gill is a Grammy Award nominated R&amp;B singer-songwriter. He gives advice to up and
                                coming musicians in this exclusive interview.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/acrockettinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_acrockett_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Affion Crockett exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Affion Crockett </p>

                            <p>Affion Crocket is a musician, actor, dancer and comedian. He gives advice to up and coming
                                artists in this exclusive interview. </p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/viinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_vi_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Vi exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Vi</p>

                            <p>Vi gives advice to up and coming musicians.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/ditchinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_ditch_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Ditch exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Ditch </p>

                            <p>Ditch gives an exclusive interview with ExploreTalent.&nbsp; Music tips from Hip Hop musician
                                performer-producer Ditch.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/cocaineinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_cocaine_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Cocaine exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Cocaine</p>

                            <p>Hip Hop performer Cocaine interviews with ExploreTalent. Cocaine gives music tips to young
                                musicians seeking to break into the industry.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/sleepybinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_sleepyb_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Sleepy Brown exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Sleepy Brown </p>

                            <p>Sleepy Brown of "OutKast" talks with Musician1.com. Producer-Musician Sleepy Brown gives
                                advice to up and coming musicians.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/etceterainterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_etcetera_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Etcetera exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Etcetera</p>

                            <p>Etcetera interviews with Musician1. Etc talks about his new single, "Crazy."</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/mamsinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_mams_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Mams Taylor exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Mams Taylor </p>

                            <p>Mams Taylor speaks with Musician1.com, sharing advice to up and coming new artists while
                                filling us in on his new song "Girl Gotta Girlfriend" with Snoop Dogg and Bobby V.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/yroscoeinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_youngroscoe_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Young Roscoe exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Young Roscoe </p>

                            <p>Young Roscoe gives some valuable lessons as he speaks with Musician1.com in a quick interview
                                when asked to give some tips to up and coming musicians on how to make it in the music
                                business.</p></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <br/>
    <table width="auto" border="0" cellspacing="0" cellpadding="1">
        <tr>
            <td valign="top">
                <table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
                    <tr>
                        <td valign="top" width="150"><a href="/industry/jconwayinterview"><img
                                src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_conway_150x131.jpg" width="150"
                                height="131" border="0"
                                alt="Jimmy Conway exclusive interview with ExploreTalent"/></a></td>
                        <td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
                                style="font-size:16px; font-weight:bold">Jimmy Conway </p>

                            <p>Jimmy Conway raps at the Jadakiss album release party.</p></td>
                    </tr>
                </table>
            </td>
            <td width="5">&nbsp;</td>
            <td valign="top">&nbsp;</td>
        </tr>
    </table>
</td>
</tr>
</table>