<div class="profile_content border_small resources_title">Explore Talent Industry Insider</div>

<div class="resources_content border_small">
	<ol>
		<li> <b>Casting Directors</b> 	- <a href="">Post your casting on ExploreTalent.com</a></li>
		<li> <b>Talent Agents</b> 		- <a href="">Interested in representing our talent?</a></li>
		<li> <b>Photographers</b> 		- <a href="">Get listed on ExploreTalent.com</a></li>
		<li> <b>Photography Studio</b> 	- <a href="">Get listed on ExploreTalent.com</a></li>
		<li> <b>Modeling Schools</b> 	- <a href="">Get listed on ExploreTalent.com</a></li>
		<li> <b>Acting Schools</b> 		- <a href="">Get listed on ExploreTalent.com</a></li>
		<li> <b>Acting Coaches</b> 		- <a href="">Get listed on ExploreTalent.com</a></li>
		<li> <b>Employers</b> 			- <a href="">Post a job listing, and access our members</a></li>
	</ol>
</div>

<div class="profile_content border_small resources_title"> Glossary of Industry Terms </div>

<div class="profile_content border_small resources_title"> A</div>
<div class="resources_content border_small">

<h3>ABBY SINGER</h3>
<p>The shot before the last shot of the day. Named in honor of former first A.D., Abby Singer, who used to call the last shot of the day one shot too early.</p>

<h3>ACTION!</h3>
<p>The command from the director for the scene to begin. It indicates that the camera is rolling.</p>

<h3>A.D.</h3>
<p>The Assistant Director.</p>

<h3>AD LIB</h3>
<p>Extemporaneous delivery without relying on a prepared script.</p>

<h3>ADR</h3>
<p>Automated Dialogue Replacement. Dialogue added to a scene in post production. Sometimes erroneously called "looping/p>

<h3>AEA</h3>
<p>Actors' Equity Association; often called simply "Equity". SAG's sister union which represents stage actors.</p>

<h3>AFI</h3>
<p>The American Film Institute</p>

<h3>AFTRA</h3>
<p>American Federation of Television and Radio Artists. Represents radio artists and news broadcasters, and, in earlier times, television performers. In more recent times, however, television performers may be represented by either AFTRA or SAG, depending on the producer's contract. Discussions about merging the two organizations have been ongoing for several decades; recently the Television &amp; Film and Commercial Contracts have been jointly negotiated.</p>

<h3>AGMA</h3>
<p>American Guild of Musical Artists</p>

<h3>AGVA</h3>
<p>American Guild of Variety Artists</p>

<h3>ART DIRECTOR</h3>
<p>Person who conceives and designs the sets.</p>

<h3>AUDITION</h3>
<p>A tryout for a film, TV or stage role. Usually auditions involve reading from the script, but can also require improvisation.</p>

<h3>AVAIL</h3>
<p>A courtesy situation extended by performer or agent to a producer indicating availability to work a certain job. Avails have no legal or contractual status.

</div>

<div class="profile_content border_small resources_title"> B</div>
<div class="resources_content border_small">

<h3>BACKGROUND</h3>
<p>The Extra performers. On the set, "Background!" is a verbal cue for the Extras to start their action.</p>

<h3>BACK TO ONE!</h3>
<p>The verbal cue for performers to return to the mark where they started the scene.</p>

<h3>BEAUTY SHOT</h3>
<p>The Assistant Director.</p>

<h3>BEST BOY</h3>
<p>Extemporaneous delivery without relying on a prepared script.</p>

<h3>BILLING</h3>
<p>Automated Dialogue Replacement. Dialogue added to a scene in post production. Sometimes erroneously called "looping/p>

<h3>BIO</h3>
<p>Actors' Equity Association; often called simply "Equity". SAG's sister union which represents stage actors.</p>

<h3>BLOCKING</h3>
<p>The American Film Institute</p>

<h3>BOOKING</h3>
<p>American Federation of Television and Radio Artists. Represents radio artists and news broadcasters, and, in earlier times, television performers. In more recent times, however, television performers may be represented by either AFTRA or SAG, depending on the producer's contract. Discussions about merging the two organizations have been ongoing for several decades; recently the Television &amp; Film and Commercial Contracts have been jointly negotiated.</p>

<h3>BOOM</h3>
<p>American Guild of Musical Artists</p>

<h3>BLUE SCREEN</h3>
<p>American Guild of Variety Artists</p>

<h3>BREAKAWAY</h3>
<p>Person who conceives and designs the sets.</p>

<h3>BREAKDOWN</h3>
<p>A tryout for a film, TV or stage role. Usually auditions involve reading from the script, but can also require improvisation.


</div>

<div class="profile_content border_small resources_title"> C</div>
<div class="resources_content border_small">


<h3>CALLBACK</h3>
<p>Any follow-up interview or audition.</p>

<h3>CALL SHEET</h3>
<p>A sheet containing the cast and crew call times for a specific day's shooting. Scene numbers, the expected day's total pages, locations, and production needs are also included.</p>

<h3>CALL TIME</h3>
<p>The actual time an actor is due on the set.</p>

<h3>CAMERA CREW</h3>
<p>With the D.P. (Director of Photography) as its chief, this team consists of the camera operator, the first assistant camera operator (focus puller), the second assistant camera operator (film loader and clapstick clapper) and the dolly grip.</p>

<h3>CAMERA OPERATOR</h3>
<p>The member of the camera crew who actually looks through the lens during a take. Responsible for panning and tilting and keeping the action within the frame.</p>

<h3>CASTING DIRECTOR</h3>
<p>The producer's representative responsible for choosing performers for consideration by the producer or director.</p>

<h3>CATTLE CALL</h3>
<p>A call for large groups of people.</p>

<h3>CATERER</h3>
<p>Responsible for breakfast, lunch and dinner on a set. Different from Craft Services.</p>

<h3>CD-ROM</h3>
<p>A compact disk that holds text, music and images. One of the principal new venues for interactive video games as well as for full motion video films. Acting for CD-ROM's is a new arena for actors. SAG 's Interactive Media Contract covers salaries and working conditions for this new medium.</p>

<h3>CHANGES</h3>
<p>Outfits worn while performing.</p>

<h3>CHEAT</h3>
<p>The actor's adjustment of body position away from what might be absolutely "natural" in order to accommodate the camera; can also mean looking in a different place from where the other actor actually is.</p>

<h3>CHECKING THE GATE!</h3>
<p>A verbal command to check the lens on the camera; if the lens is - OK - the cast &amp; crew will move on to the next scene or shot.</p>

<h3>CHIEF ELECTRICIAN</h3>
<p>Heads the electrician crew; also called the Gaffer.</p>

<h3>CINEMATOGRAPHER</h3>
<p>Director of Photography</p>

<h3>CLOSE-UP (CU)</h3>
<p>Camera term for tight shot of shoulders and face.</p>

<h3>COLD READING</h3>
<p>Unrehearsed reading of a scene, usually at an audition.</p>

<h3>COMMISSION</h3>
<p>Percentage of a performer's earnings paid to agents or managers for services rendered.</p>

<h3>COMPOSITE</h3>
<p>A series of photos on one sheet representing an actor's different looks.</p>

<h3>CONFLICT</h3>
<p>Status of being paid for services in a commercial for one advertiser, thereby contractually preventing performing services in a commercial for a competitor.</p>

<h3>COPY</h3>
<p>The script for a commercial or voice over.</p>

<h3>COVERAGE</h3>
<p>All camera shots other than the master shot; coverage might include two-shots and close-ups.</p>

<h3>CRAFT SERVICES</h3>
<p>On-set beverage and snack table. Different from the Caterer.</p>

<h3>CRANE SHOT</h3>
<p>A camera shot raised over or above the set or the action.</p>

<h3>CRAWL</h3>
<p>Usually the end credits in a film or TV shot which "crawl" up the screen.</p>

<h3>CREDITS</h3>
<p>Opening names in a film or TV show; also refers to one's performance experience listed on a resume or in a program.</p>

<h3>CUE</h3>
<p>Signal, often an off-stage light or hand signal, by the assistant director to indicate an actor's entrance or action.</p>

<h3>CUT!</h3>
<p>The verbal cue for the action of the scene to stop. At no time, may an actor call, "cut!"</p>

<h3>CUTAWAY</h3>
<p>A short scene between two shots of the same person, showing something other than that person.

</div>

<div class="profile_content border_small resources_title"> D</div>
<div class="resources_content border_small">

<h3>DAILIES</h3>
<p>Screening of footage before it is edited.</p>

<h3>DAY PLAYER (DAY PERFORMER)</h3>
<p>A principal performer hired on a daily basis, rather than on a longer-term contract.</p>

<h3>DAYTIME DRAMA</h3>
<p>Soap opera.</p>

<h3>DEMO TAPE</h3>
<p>An audio or video tape that agents use for audition purposes.</p>

<h3>DGA</h3>
<p>Directors Guild of America.</p>

<h3>DIALECT</h3>
<p>A distinctly regional or linguistic speech pattern.</p>

<h3>DIALOGUE</h3>
<p>The scripted words exchanged by performers.</p>

<h3>DIRECTOR</h3>
<p>The coordinator of all artistic and technical aspects of any production.</p>

<h3>DIRECTOR OF PHOTOGRAPHY (D.P.)</h3>
<p>Supervises all decisions regarding lighting, camera lenses, color and filters, camera angle set-ups, camera crew and film processing.</p>

<h3>DOLLY</h3>
<p>A piece of equipment that the camera sits on to allow mobility of the camera.</p>

<h3>DOLLY GRIP</h3>
<p>The crew member who moves the dolly.</p>

<h3>DOUBLE</h3>
<p>A performer who appears in place of another performer, i.e., as in a stunt.</p>

<h3>D.P.</h3>
<p>Director of Photography or Cinematographer.</p>

<h3>DRESS THE SET</h3>
<p>Add such items to the set as curtains, furniture, props, etc.</p>

<h3>DRIVE-ON PASS</h3>
<p>In Los Angeles, a pass to drive onto and park on a studio lot.</p>

<h3>DUPE</h3>
<p>A duplicate copy of a film or tape; also, called a "dub"

</div>

<div class="profile_content border_small resources_title"> E</div>
<div class="resources_content border_small">

<h3>8x10</h3>
<p>Commonly used size of a performer's photos, usually in black and white.</p>

<h3>18-TO-PLAY-YOUNGER</h3>
<p>A performer legally 18 years old, who can convincingly be cast as a younger age.</p>

<h3>ELECTRICIAN</h3>
<p>In film, crew members who place lighting instruments, focus, gel and maneuver the lights.</p>

<h3>EMPLOYER OF RECORD (EOR)</h3>
<p>The company responsible for employment taxes, unemployment benefits and workers compensation coverage.</p>

<h3>EQUITY</h3>
<p>Actors Equity Association (AEA) Union representing stage actors.</p>

<h3>EQUITY WAIVER</h3>
<p>In Los Angeles, 99-seat (or less) theatres, which were otherwise professional, over which Equity waived contract provisions under certain circumstances. Now officially called "Showcase code", the term "Equity waiver" is still used informally.</p>

<h3>EXECUTIVE PRODUCER</h3>
<p>Person responsible for funding the production.</p>

<h3>EXT. (Exterior)</h3>
<p>A scene shot outside.</p>

<h3>EXTRA</h3>
<p>Background talent, used only in non-principal roles.

</div>

<div class="profile_content border_small resources_title"> F</div>
<div class="resources_content border_small">

<h3>FICA</h3>
<p>Social Security taxes (Federal Insurance Corporation of America).</p>

<h3>FIELD REP.</h3>
<p>Union staff member who ensures contractual compliance on sets.</p>

<h3>FIRST A.D.</h3>
<p>First Assistant Director; person responsible for the running of the set. Gives instructions to crew and talent, including calling for "first team," "quiet," "rehearsal," and "take five."</p>

<h3>FIRST ASS'T. CAMERA OP.</h3>
<p>First Assistant Camera Operator is responsible for focusing the camera lens during the shooting of a scene; also known as the Focus Puller.</p>

<h3>FIRST TEAM</h3>
<p>The production term for the principal actors in a scene.</p>

<h3>4-A's</h3>
<p>Associated Actors and Artist's of America; umbrella organization for SAG, AFTRA, Equity and other performers' Unions.</p>

<h3>FORCED CALL</h3>
<p>A call to work less than 12 hours after dismissal on the previous day. See TURNAROUND.</p>

<h3>FOREGROUND CROSS</h3>
<p>Action in a scene in which an Extra Performer passes between the camera and the principal actors; sometimes called a "wipe/p>

<h3>FX (Effects)</h3>
<p>Special Effects.

</div>

<div class="profile_content border_small resources_title"> G</div>
<div class="resources_content border_small">

<h3>GAFFER</h3>
<p>The Chief Electrician.</p>

<h3>GOLDEN TIME</h3>
<p>Contractually called 16 Hour Rule Violation for Extra Performers, is overtime, after the 16th hour, paid in units of one full day per hour.</p>

<h3>GRIPS</h3>
<p>Members of the film crew who are responsible for moving set pieces, lighting equipment, dolly track and other physical movement of equipment.

</div>

<div class="profile_content border_small resources_title"> H</div>
<div class="resources_content border_small">

<h3>HAND MODEL</h3>
<p>A performer whose hands are used to double for others.</p>

<h3>HIATUS</h3>
<p>Time during which a TV series is not in production.</p>

<h3>HOLDING</h3>
<p>The designated area to which the Extra Performers report and stay while waiting to go on set.</p>

<h3>HONEY WAGON</h3>
<p>A towed vehicle containing one or more dressing rooms, as well as crew bathrooms.

</div>

<div class="profile_content border_small resources_title"> I</div>
<div class="resources_content border_small">

<h3>IATSE</h3>
<p>International Alliance of Theatrical Stage Employees; the union which represents most off-camera crew members.</p>

<h3>INDUSTRIAL</h3>
<p>Non-broadcast film or video, usually of an educational nature.</p>

<h3>INSERTS</h3>
<p>Shots, usually close-ups of hands or close business, inserted into previously shot footage.</p>

<h3>INT. (Interior)</h3>
<p>A scene shot indoors.</p>

<h3>"IN" TIME</h3>
<p>The actual call time or start time; also, return time from a break.

</div>

<div class="profile_content border_small resources_title"> J</div>
<div class="resources_content border_small">

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> K</div>
<div class="resources_content border_small">

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> L</div>
<div class="resources_content border_small">

<h3>LINE PRODUCER</h3>
<p>The producer responsible for keeping the director on time and budget; generally the most visable producer on the set.</p>

<h3>LONG SHOT (LS)</h3>
<p>A camera shot which captures the performer's full body.</p>

<h3>LOOPING</h3>
<p>An in-studio technique used to fix dialogue already performed during principal photography by matching voice to picture.


</div>

<div class="profile_content border_small resources_title"> M</div>
<div class="resources_content border_small">

<h3>MARK</h3>
<p>The exact position(s) given to an actor on a set to insure that he/she is in the proper light and camera angle; generally marked on the ground with tape or chalk.</p>

<h3>MARKER!</h3>
<p>A verbal cue that the take has been identified on camera both verbally and with the slate board.</p>

<h3>MARTINI SHOT</h3>
<p>The last shot of the day.</p>

<h3>MASTER SHOT</h3>
<p>A camera shot that includes the principal actors and relevant background activity; generally used as a reference shot to record the scene from beginning to end before shooting close-ups, over-the-shoulders, etc.</p>

<h3>MATCHING ACTIONS</h3>
<p>The requirement that the actor match the same physical movements in a scene from take to take in order to preserve the visual continuity.</p>

<h3>MEAL PENALTY</h3>
<p>A fee paid by the producer for the failure to provide meals or meal breaks as specified by the contract.</p>

<h3>MIXER</h3>
<p>Chief of the sound crew; responsible for the quality of the sound recording on a shoot.</p>

<h3>MOS (Mit Out Sound/Motion Only Shot)</h3>
<p>Any shot without dialogue or sound recording.</p>

<h3>M.O.W.</h3>
<p>Movie of the week


</div>

<div class="profile_content border_small resources_title"> N</div>
<div class="resources_content border_small">

<h3>ND MEAL (NON DEDUCTABLE MEAL)</h3>
<p>A 15 minute meal break provided to actors by the production company to bring actors in sync with crew break time. It must be completed within 2 hours of performers call time.</p>

<h3>NIGHT PREMIUM</h3>
<p>A surcharge for certain work performed after 8 p.m.


</div>

<div class="profile_content border_small resources_title"> O</div>
<div class="resources_content border_small">

<h3>OFF-CAMERA (OC or OS)</h3>
<p>Dialogue delivered without being on screen.</p>

<h3>OUT OF FRAME</h3>
<p>An actor outside the camera range.</p>

<h3>"OUT" TIME</h3>
<p>The actual time when you are released after you have changed out of wardrobe and make-up.</p>

<h3>OVER-THE-SHOULDER</h3>
<p>A shot over the shoulder of one actor, focusing entirely on the face and upper torso of the other actor in a scene; generally shot in pairs so both actors expressions can later be edited together.</p>

<h3>OVERDUBBING</h3>
<p>In studio singing or voice work, the process of laying one soundtrack over another.</p>

<h3>OVERTIME (OT)</h3>
<p>Work extending beyond the contractual work day.


</div>

<div class="profile_content border_small resources_title"> P</div>
<div class="resources_content border_small">

<h3>P.A.</h3>
<p>Production Assistant.</p>

<h3>PAN</h3>
<p>A camera shot which sweeps from side-to-side.</p>

<h3>PAYMASTER</h3>
<p>An independent talent payment service acting as the employer of record.</p>

<h3>PENSION &amp; HEALTH PAYMENT</h3>
<p>An additional amount of money paid by the employer to cover employee benefits under union contract.</p>

<h3>PER DIEM</h3>
<p>Fee paid by producer on location shoots to compensate performer for expenditures for meals not provided by the producer.</p>

<h3>PHOTO DOUBLE</h3>
<p>An actor cast to perform on camera in place of another.</p>

<h3>PICK UP</h3>
<p>Starting a scene from a place other than the beginning.</p>

<h3>PICTURE'S UP!</h3>
<p>Warning that the sequence of cues to shoot a scene is about to begin.</p>

<h3>POV SHOT</h3>
<p>Point-of-View shot; camera angle from the perspective of one actor.</p>

<h3>POST-PRODUCTION</h3>
<p>The phase of filmmaking that begins after the film has been shot. Includes scoring, sound and picture editing, titling, dubbing, and releasing.</p>

<h3>PRE-PRODUCTION</h3>
<p>The phase of filmmaking before shooting begins; includes writing, scouting locations, budgeting, casting, hiring crews, ordering equipment and creating a shooting schedule.</p>

<h3>PRINCIPAL</h3>
<p>A performer with lines.</p>

<h3>"PRINT!"</h3>
<p>A call from the director at the end of a take that that particular take is good enough to be printed.</p>

<h3>PRODUCER</h3>
<p>Often called the Line Producer; the person responsible for the day-to-day decision-making on a production.</p>

<h3>PRODUCTION COMPANY</h3>
<p>The company actually making the film or television show.</p>

<h3>PROPS</h3>
<p>Any objects used by actors in a scene.</p>

<h3>PSA</h3>
<p>Public Service Announcement.


</div>

<div class="profile_content border_small resources_title"> Q</div>
<div class="resources_content border_small">

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> R</div>
<div class="resources_content border_small">
<h3>RESIDUAL</h3>
<p>The fee paid to performers for rebroadcast of a commercial, film or TV program.</p>

<h3>RESUME</h3>
<p>List of credits, usually attached to an 8x10 or composite.</p>

<h3>REWRITE</h3>
<p>Changes in the script, often using color-coded pages to indicate the most current version.</p>

<h3>RIGHT-TO-WORK-STATES</h3>
<p>Those states which do not honor certain union provisions.</p>

<h3>ROLLING!</h3>
<p>The verbal cue for the camera film and audio tape to start rolling.</p>

<h3>ROOM TONE</h3>
<p>A sound recording (sometimes made upon completion of a scene) to record existing noise at the location. Also called "wild track".


</div>

<div class="profile_content border_small resources_title"> S</div>
<div class="resources_content border_small">

<h3>SAG</h3>
<p>Screen Actors Guild.</p>

<h3>SCALE</h3>
<p>Minimum payment for services under union contracts.</p>

<h3>SCRIPT</h3>
<p>The written form of a screenplay, teleplay, radio or stage play.</p>

<h3>SCRIPT SUPERVISOR</h3>
<p>The crew member assigned to record all changes or actions as the production proceeds.</p>

<h3>SDI</h3>
<p>State Disability Insurance.</p>

<h3>SECOND ASSISTANT DIRECTOR</h3>
<p>Often two or three on a set, they handle checking in the talent, insuring proper paperwork is filed, and distribute script revisions. Actors check in with the 2nd A.D. upon arrival on the set.</p>

<h3>SECOND TEAM!</h3>
<p>The verbal cue for the stand-ins to come to the set and be ready to stand in.</p>

<h3>SEGUE</h3>
<p>In film or tape editing, a transition from one shot to another.</p>

<h3>SET</h3>
<p>The immediate location where the scene is being filmed.</p>

<h3>SET-UP</h3>
<p>Each time the camera changes position.</p>

<h3>SFX</h3>
<p>Sound effects.</p>

<h3>SIDES</h3>
<p>Pages or scenes from a script, used in auditions or (if on a film set) those scenes being shot that day.</p>

<h3>SIGNATORY</h3>
<p>An employer who has agreed to produce under the terms of a union contract.</p>

<h3>SLATE</h3>
<p>A small chalkboard and clapper device, often electronic, used to mark and identify shots on film for editing; also the process of verbal identification by a performer in a taped audition (e.g., "Slate your name!").</p>

<h3>SPEED!</h3>
<p>A verbal cue that the audio tape is up to speed for recording.</p>

<h3>SPIKING THE LENS</h3>
<p>Looking directly into the lens during a scene; since it destroys the illusion of realism, actors should never spike the lens unless specifically directed to do so for specific effect.</p>

<h3>STAGE RIGHT</h3>
<p>To the performer's right side, to the audience's left side. Likewise, STAGE LEFT is to the performer's left, the audience's right. Stage directions are for actors, not audiences, therefore they are always given from the actor's point of view to the audience.</p>

<h3>STANDARD UNION CONTRACT</h3>
<p>The standard format/contract approved by the Unions and offered to performers prior to the job.</p>

<h3>STANDARDS &amp; PRACTICES</h3>
<p>The network TV censorship departments.</p>

<h3>STAND-INS</h3>
<p>Extra Performers used as substitutes for featured players, for the purpose of setting lights and rehearsing camera moves; also known as the second team.</p>

<h3>"STICKS"</h3>
<p>Slate or clapboard.</p>

<h3>STUDIO</h3>
<p>A building, recording room or sound stage which accommodates film or TV production.</p>

<h3>STUNT COORDINATOR</h3>
<p>The person in charge of designing and supervising the performance of stunts and hazardous activities.</p>

<h3>STUNT DOUBLE</h3>
<p>A stuntperson who performs stunts for a principal.</p>

<h3>STUNTPERSON</h3>
<p>A specially trained performer who actually performs stunts.</p>

<h3>SUBMISSION</h3>
<p>An agent's suggestion to a casting director for a role in a certain production.</p>

<h3>SW</h3>
<p>A notation on a call sheet that an actor is starting on that day and working on that day.</p>

<h3>SWF</h3>
<p>A notation on a call sheet that an actor is starting, working, and finished on that day.</p>

<h3>SWEETENING</h3>
<p>In singing/recording, the process of adding additional voices to previously recorded work.</p>

<h3>SYNDICATION</h3>
<p>Selling TV programs to individual stations rather than to networks.

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> T</div>
<div class="resources_content border_small">

<h3>TAFT-HARTLEY</h3>
<p>A federal statute which allows 30 days after first employment before being required to join a Union.</p>

<h3>TAKE</h3>
<p>The clapboard indication of a shot "taken" or printed.</p>

<h3>"TAKE 5"</h3>
<p>The announcement of periodic five minute breaks.</p>

<h3>TELEPROMPTER</h3>
<p>The brand name of a device which enables a broadcaster to read a script while looking into the camera lens.</p>

<h3>THEATRICAL</h3>
<p>TV shows or feature film work, as opposed to commercials.</p>

<h3>THREE BELLS!</h3>
<p>An audible warning for QUIET because a scene is about to be filmed.</p>

<h3>TIGHT SHOT (Go in Tight)</h3>
<p>Framing of a shot with little or no space around the central figure(s) of feature(s); usually a close-up.</p>

<h3>TILT</h3>
<p>The up and down movement of a camera.</p>

<h3>TIME-AND-A-HALF</h3>
<p>Overtime payment of 1 1/2 times the hourly rate.</p>

<h3>TRACKING SHOT</h3>
<p>A shot taken while the camera is moving, either on a dolly or mounted on a moving vehicle.</p>

<h3>TRADES</h3>
<p>Short for "trade papers" - The newspapers and periodicals such as the Hollywood Reporter and Variety that specifically feature information on the entertainment industry.</p>

<h3>TURNAROUND</h3>
<p>(a) The number of hours between dismissal one day and call time the next day. (b) To shoot a scene from another direction.</p>

<h3>TWO-SHOT</h3>
<p>A camera framing two persons.

</div>

<div class="profile_content border_small resources_title"> U</div>
<div class="resources_content border_small">

<h3>UNDERSTUDY</h3>
<p>A performer hired to do a role only if the featured player is unable to perform; used primarily in live theatre.</p>

<h3>UPGRADE</h3>
<p>The promotion of an extra performer in a scene to the category of principal performer.</p>

<h3>UPM</h3>
<p>Unit Production Manager - Oversees the crews and handles the scheduling of all the technical responsibilities of the production.</p>

<h3>UP STAGE</h3>
<p>(a) The area located at the back of the stage. Down Stage is the area in front of the performer. (b) To draw attention to oneself at the expense of a fellow performer.

</div>

<div class="profile_content border_small resources_title"> V</div>
<div class="resources_content border_small">

<h3>V.O.</h3>
<p>Voice over. An off-camera voice coming either from an actor not in the frame, or from a secondary source such as a speakerphone or answering machine.</p>

<h3>VOUCHER</h3>
<p>Time slip with all pertinent information needed for getting paid properly.

</div>

<div class="profile_content border_small resources_title"> W</div>
<div class="resources_content border_small">

<h3>W</h3>
<p>A notation on the call sheet indicating that an actor is working that day.</p>

<h3>WAIVERS</h3>
<p>Union-approved permission for deviation from the terms of a contract.</p>

<h3>WALKAWAY</h3>
<p>A meal break in which all cast and crew are on their own to get lunch.</p>

<h3>WARDROBE</h3>
<p>The clothing a performer wears on camera.</p>

<h3>WARDROBE ALLOWANCE</h3>
<p>A maintenance fee paid to on-camera talent for the use (and dry cleaning) of talent's own clothing.</p>

<h3>WARDROBE FITTING</h3>
<p>A session held prior to production to prepare a performer's costumes.</p>

<h3>WEATHER PERMIT CALL</h3>
<p>Due to weather conditions, the production company has the option to release an actor four hours after the call time (if the camera has not started to roll) with a reduced rate of pay for the day.</p>

<h3>WILD TRACK</h3>
<p>A recording of dialog or sound effects on the set of a film but without the camera running.</p>

<h3>W/N</h3>
<p>Will Notify. A notation on a call sheet that tells the actor that he/she will probably work that day but the specific time has not yet been decided.</p>

<h3>WRAP</h3>
<p>The completion of a day's filming or of an entire production.

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> X</div>
<div class="resources_content border_small">

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> Y</div>
<div class="resources_content border_small">

</div>
<div class="resources_content border_small">

</div>

<div class="profile_content border_small resources_title"> Z</div>
<div class="resources_content border_small">

<h3>ZOOM</h3>
	<p>A camera technique with a special lens to adjust the depth of a shot, accomplished without moving the camera.</p>
</div>

<div class="profile_content border_small resources_title">One of many success stories <a href="/testimonials">Click here for more</a></div>
<div class="resources_content border_small">
	<div class="scam_video">
		<div class="scam_one">
			<img src="<?php echo CDN_IMAGES; ?>/media234/0002341629/th0002341629_PM_1233457981.jpg" />
			<div>
				<a href="/profile/social/social-info/id/2341629">View My Website</a>
			</div>
		</div>
		<p>Book 2 jobs in such a short time</p>
		<p>Explore Talent is the leader in obtaining quality auditions. I have been on over 10 auditions and landed a T.V. Pilot, a commercial, a feature indie film and offered to be represented by a talent agency for modeling and acting. Explore Talent has been beneficial in my success and I will continue to utilize their services.</p>
		<p>Larry A. Peterman</p>
	</div>
</div>