<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Jamie Foxx</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/Al3naELlVVE?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/jamiefox_pic.jpg" alt="Jamie Foxx" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('JamieFoxxxxx').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Jamie Foxx</div>
			</div>
			<div class="content_paragraph">
		<p><a href="/industry/jamie-foxx" title="Jamie Foxx">Jamie Foxx</a> is often described as a triple threat for his versatility as an actor, musician and comedian. He was born Eric Bishop and raised by his grandparents in Terrell, Texas. It was his 'Granny' who recognized his gift to perform and introduced him to the piano. When he became 15, Foxx was serving as musical director and choir leader at Terrell's New Hope Baptist Church. Not only was he a gifted musician, but also a star athlete at Terrell High school setting records in football and track. It was music that took Foxx to California when he received a classical piano scholarship to U.S. International University in San Diego.</p>
		<p>Foxx first came to fame as a comedian. Still as Eric Bishop, he got his start in showbiz in 1989 when he tried his hand at standup on a dare at an open microphone night. After realizing that the women who signed up for open mike nights were always selected, he used different unisex names with hopes of getting stage time. After bringing down the house as 'Foxx', the name Eric Bishop was relegated to the past. After spending time on the comedy circuit, he joined Keenan Ivory Wayans, Jim Carrey, Damon Wayans and Tommy Davidson in the landmark Fox sketch comedy series 'In Living Color,' creating some of the show's funniest and most memorable moments.</p>
		<p>In 1996, he launched his own series, 'The Jamie Foxx Show,' that became one of the top-rated programs on the WB Network.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Jamie Foxx</div>
			</div>
			<div class="content_paragraph">
		<p>During its five-year run. Foxx not only starred on the series but was also the co-creator, executive producer, and director of several episodes. He received critical acclaim for his riveting work in "Any Given Sunday" and as Bundini Brown in 'Ali.' These dramatic breakout roles led to 2004, the Year of the Foxx, when he delivered a trio of powerful performances in Ray, Collateral and Redemption.</p>
		<p>He won an Academy Award for his portrayal of the legendary Ray Charles as well as the Golden Globe, Screen Actors Guild (SAG), AFTRA and NAACP Image Awards. Foxx simultaneously garnered Oscar, Golden Globe, SAG Award, AFTRA Award, and Image Award nominations in the category of Best Supporting Actor for his work in Collateral. And he landed Golden Globe and SAG Award nominations and won an Image Award for his portrayal of condemned gang member-turned-Nobel Peace Prize nominee Stan 'Tookie' Williams in the television movie Redemption.</p>
		<p>That amazing feat marked the first time that a single actor has received three Golden Globe nominations and four SAG Award nominations in the same year. Some of his other films include: Dreamgirls, Miami Vice, Jarhead, The Kingdom, The Soloist, Law Abiding Citizen, and Valentine's Day. </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Jamie Foxx? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/JamieFoxx1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/JamieFoxx2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/JamieFoxx3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/JamieFoxx4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/JamieFoxx5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/gabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


