<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Jennia Fredrique</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/RWvewJOUgLE?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/jennia2.JPG" width="210" height="295" alt="Jennia Fredrique" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('JenniaFredrique').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">Beyond The Talent</div>
			</div>
			<div class="content_paragraph">
				<p>Go behind the scenes with <a href="/industry/jennia-fredrique">Jennia Fredrique</a> as she catches up to your favorite musical artists. Tune in to Beyond the Talent, for exclusive interviews that will provide you with insight and inspiration from some of the biggest names in the music and entertainment industries. Go Beyond the Talent only on <a href="http://www.exploretalent.com">ExploreTalent.com</a>. </p>
				<p>Movie actress and stand-up comedian Jennia Fredrique was born in Gary, Indiana and moved to Los Angeles to pursue her dream of becoming famous.  She has starred in movies such as 'City Guys','Half and Half' and on the series 'One on One'.   In addition to her acting and comedy career, Jennia Fredrique has become famous as a painter, a published poet, and a professional dancer.</p>
				<p>She studied at Columbia College, ETA Creative Arts Theatre, and Jane Brody's Center for the Arts.  She has performed in several plays and television commercials, including tv spots for products and services</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">About Jennia Fredrique</div>
			</div>
			<div class="content_paragraph">
				<p>She recently starred in the role of Brandy on "Noah's Arc", the popular cable television show about the gay lifestyle. As with all actors, Jennia has some major differences and similarities to her character. Like Brandy, Jennia is an "aggressive go-getter." However, unlike Brandy she isn't competitive. "I admit Brandy can be a little harsh." She admits her favorite parts of the show are the office scenes when she's giving Noah a hard time. "I loved the threesome, I loved the scene with Rockmund Dunbar, it was all fun! It was amazing to walk in Patrik's head." Beyond her love for the show, Jennia feels that Noah's ARC is revolutionary. "I love this show! It shows successful gay men thriving and love is love. At the end of the day, that's what it's about. You can't help who you love and no one should be punished for that." Presently, Jennia has a lot of work under her belt.
				<p>She is working on a horror film, "Marco Polo," scheduled for release later this year, and is on a straight to DVD film, "Who Made The Potato Salad?," writing, producing, and filming a show for the Travel Channel, and is in talks with the Fashion and Beauty Channel to create a show. </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Journalist like Jennia Fredrique? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
			</div>
		</td>
	</tr>
</table>


