<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Karina Smirnoff</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/eLkhJ2-0950?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-205x295.jpg" alt="Karina Smirnoff" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
					 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('karina_smirnoff').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Karina Smirnoff</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/karina-smirnoff">Karina Smirnoff</a> has made many candid appearances on real life shows like Dancing with the Stars, and Chelsea Recently, featuring Chelsea Handler. Early in Smirnoff's dancing career, she and Roman Nabatov competed as a newbie couple for USA.  They finished their dance partnership in Jan 1997 Smirnoff shortly after started dancing with Paul Killick in October 1998 as a pro couple for Britain; this partnership finished in July 1999.  Straight away, Louis truck Amstel and Karina Smirnoff, in July 1999, entered a pro dance partnership, representing the U.S.A; the partnership finished in December two thousand.  From Jan 2001 to Sep  2005, Smirnoff was in a dance collaboration with Slavik Kryklyvyy and they represented the U.S.A; this partnership this far is her most successful one. </p>
				<p> Kryklyvyy and Smirnoff earned many top titles and high ratings together.  Her last pro partner recorded in contests was Dmitri Timokhin representing Russia in October 2005.  They won 1st place at the 2006 Grand-Prix Dynamo in Moscow.  They finished dancing together in June 2006.  Smirnoff was the project chief / director of a dancing event titled "Day &amp; Night", held on  Nov  eighteen, 2006 at the Hollywood &amp; Highlands Grand    Dancehall .  Smirnoff was a performer on the 3rd season of the ABC series Dancing with the Stars with celebrity partner Mario Lopez. </p>
				<p> They completed in 2nd place, losing to the team of Emmitt Smith and Cheryl Burke.  Smirnoff returned to the show on March 19, 2007 for Season four, this time partnered with Billy Ray Cyrus, country vocalist and Hannah Montana star.  The pair was the eighth to be dumped from the competitors on May eight, 2007.  Her partner for Season five of the show was current five-division world champ fighter, Floyd Mayweather Jr.  On October sixteen, 2007, Karina and Floyd were the 4th couple eliminated from competition and came in 9th place.  She returned for Season six, partnered with frontman Mario and completed in fifth place.  In Season seven, she was partnered with cook Rocco DiSpirito and they were the 4th pair to be thrown out with a finish of 9th place for the second time.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Karina Smirnoff</div>
			</div>
			<div class="content_paragraph">
				<p>For the eighth season, Smirnoff's partner was Apple Inc. Founder Steve Wozniak.  They were eliminated in the 4th round on March 31, 2009, together with Holly Madison and her partner Dmitry Chaplin.  For the ninth season, she was partnered with frontman Aaron Carter.  They were eliminated on  November10th, 2009 and placed 5th. </p>
				<p> In the eleventh season, she's partnered with Mike "The Situation" Sorrentino, from MTV's Real-life TV show Jersey Shore.  Smirnoff spoofed her role on Dancing in Hannah Montana, playing a psychic who foresees to a disbelieving Cyrus about his appearance in a dancing competition. </p>
				<p> Smirnoff dated actor Mario Lopez after having been partnered with him in the autumn 2006 for the 3rd season of Dancing with the Stars. Their relationship lasted from fall 2006 till June 2008.  She commenced going out with a fellow Ukrainian and fellow Dancing With the Stars dancer, Maksim   Chmerkovskiy, in the summertime of 2008. </p>
				<p>Just half a year later on they exclaimed their engagement on December 31, 2008.  Smirnoff and Chmerkovskiy had performed together professionally at the 2007 ALMA Awards.  Their engagement climaxed in Sep 2009 after 9 months. </p>
				<p>In   October 2009, Smirnoff began dating MLB pitcher Brad Penny.  The couple became engaged on October fourth, 2010. </p>
				<p>Karina Smirnoff is a Ukrainian American professional ball room dancer. Karina is a five-time U.S. National Champion, World Trophy Champion, and Asian Open Champion. Karina has won the title at the UK Open, is a three-time champion at the US Open, two-time champion at the Asian Open, five-time champion at the Dutch Open, and five-time US National Professional Champion. She has been ranked second in the world, and took second at the British Open Blackpool Dance Festival. She is &quot;the first woman to ever make the British Professional Final with three different partners.&quot;</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Dancer like Karina Smirnoff? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-1-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-2-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-3-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-4-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/karina_smirnoff-5-123x164.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/trey-songz">Trey Songz</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
			</div>
		</td>
	</tr>
</table>


