<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Keri Hilson</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/Xa_sFEBcQI0?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson6.jpg" alt="Keri Hilson" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
                 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('KeriHilson').start();
                 </script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Keri Hilson</div>
			</div>
			<div class="content_paragraph">
      <p>Keri Lynn Hilson is an American RB recording artist and songwriter. Born in Decatur, Georgia, Hilson made herself a name as a songwriter, penning tracks for one or two artists in the mid-2000s as a part of the five-person production / songwriting team called the Clutch.</p>
      <p>In 2006, she agreed to a recording contract with Timbaland's label, Mosley Music. Hilson released her debut studio album, In an ideal World... In March 2009, which topped in the top 5 of the Billboard 200 albums chart and featured the hit singles "Knock You Down" and "Turnin Me On". The album reached number one on the US Top RB / Hiphop Albums chart and was ultimately licensed gold. Hilson earned 2 Grammy Award proposals for the album including Best Rap / Sung Collusion for "Knock You Down", which features Kanye West and Ne-Yo. A reissue of the album, included formerly unreleased songs like "I Like/p>
      <p>The track became Hilson's first number one hit in Germany and licensed platinum there. As an outstanding guest vocalist in both the recent RB and hiphop genres, Hilson has been featured on over 12 singles by other artists, including the number-one hit single "The way that I Are" with Timbaland.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">More on Keri Hilson</div>
			</div>
			<div class="content_paragraph">
      <p><a href="/industry/keri-hilson">Keri Hilson</a> has 2 idols and neither one of them takes or took there sexy to a higher level to sell albums. She had the opportunity to musical icon, Lauryn Hill, and it appears that this was everything she'd have imagined it to be and more. She took to Twitter to share her moment with her proponents:</p>
      <p>"Nobody understandsI will never be the same. Maximum respect four Lauryn Hill. So gorgeous. Terribly level-headed. Anyone that knows me knows she is a massive inspiration to meI told her 2nite."</p>
      <p>"Stated that she loves Pretty Girl Rock ( SCREAAAM ) &amp; her daughter loves me! Related my music embodies a certain confidence ladies need. I am so galvanized. Just two ppl I ever actually needed to meet are Lauryn Hill &amp; M.J. One down. But the other will never occur."<br>-Keri Hilson</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Keri Hilson? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/KeriHilson5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/trey-songz">Trey Songz</a></div>
			</div>
		</td>
	</tr>
</table>


