<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Matt Damon</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/a-Jd4bkdM3o?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon_main.jpg" alt="Matt Damon" name="profile_pic"
			     id="profile_pic"/>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Matt Damon</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/matt-damon">Matt Damon</a> movies are the type of movie everyone loves to watch. Matt Damon movies like Saving Private Ryan, the Ocean's trilogy, and the Bourne series are the type of action packed movies that mass audiences love to watch. You might wonder, how did Matt Damon Movies first start? How can I become a famous actor like Matt Damon? While Matt Damon Movies are all the rage now, it took Matt Damon many years of hard work to get to his current level of fame. </p>
				<p>Matt Damon's first movie was a single line in Mystic Pizza when he was 18, but Matt Damon's movie career started even earlier when he took part in theatre productions in high school. Matt Damon attended high school with Ben Affleck and began theatre performances prior to 1988 and continued to perform in theatre while at college in Cambridge. </p>
				<p>He eventually dropped out of Caimbridge to pursue his acting career. Matt Damon was in several movies with small roles between 1988 and 1997, but did not get his first major movie role until 1997, more than 10 years after he first began his movie career. </p>
				<p>Check out the Exclusive Matt Damon Video interview above.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">How To Become Famous Like Matt Damon</div>
			</div>
			<div class="content_paragraph">
				<p>What was his secret on how to become famous? Persistance, Networking, and willingness to try different avenues. Matt Damon tried to make it in Hollywood as an actor between 1988 and 1992 but was essentially a failure with only a few small parts to his credit. He became frustrated with his falure, and contacted his friend and high school playmate, Ben Affleck, and the two of them finished writing a screenplay Damon had started writing when he was still in college at Harvard. In 1997 (5 years later) his screen play, Good Will Hunting, was released as a major motion picture. </p>
				<p>Note that, even after Matt Damon and Ben Affleck finished writing the screenplay, it took them 4-5 years of hard work to get the movie onto the big screen. Matt Damon's secret to success for how to become famous in Hollywood could be summarized by a quote from his Good Will Hunting Screenplay, "You'll never have that kind of relationship in a world where you're afraid to take the first step because all you see is every negative thing 10 miles down the road./p>
				<p>What does it mean to you? If Acting is what you want to do, take the first step and start trying to get auditions! </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV Personality like Matt Damon? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/Matt_Damon5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/usher-raymond">Usher Raymond</a></div>
				<div><a href="/industry/gabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


