<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Piers Morgan</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/Rxg24VOLslw?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-205x295.jpg" alt="Piers Morgan" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('piersmorgan').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Piers Morgan</div>
			</div>
			<div class="content_paragraph">
				<p>As editor of the Mirror, in 1996 <a href="/industry/piers-morgan">Piers Morgan</a> was criticized and compelled
					to apologize for the strap line "Achtung! Surrender" a day before Britain met Germany in a semi final of
					the Euro dollar '96 soccer championships. </p>

				<p>In two thousand, he was the topic of an inquiry after Suzy Jagger wrote a tale in The Daily Telegraph
					disclosing he had acquired &pound;20,000 worth of stocks in the PC company Viglen shortly before the
					Mirror's 'City Slickers' column tipped Viglen as a superb buy.</p>

				<p>Morgan was discovered by the Press Beefs Commission to have breached the code of behavior on financial
					journalism, but kept his job. The 'City Slickers' reporters, Anil Bhoyrul and James Hipwell, were both
					discovered to possess committed further breaches of the Code, and were sacked before the investigation.
					In 2004, further enquiry by the Dept of Trade and Industry cleared Morgan from any charges. On seven
					December 2005 Bhoyrul and Hipwell were convicted of conspiracy to break the Finance Services Act
				</p>

				<p>In the trial it appeared that Morgan had acquired &pound;67,000 worth of Viglen shares, emptying his
					deposit account and investing under his wife's name too.</p>

				<p>In 2002, the Mirror attempted to move mid-market, claiming to eschew the more unimportant stories of
					show-business and gossip. Morgan rehired John Pilger, who had been sacked during Robert Maxwell's
					possession of the Mirror titles. Notwithstanding such changes, Morgan was not able to stop the
					paper's
					decline in circulation, a decline shared by its direct tabloid rivals The Sun and the Daily Star.
					Morgan
					was fired from the Mirror on fourteen May 2004 after authorizing the newspaper's publication of
					footage
					purportedly showing Iraqi captives being abused by UK military squaddies from the Queen's Lancashire
					Regiment.</p>

				<p>This possession was cited as "one" of the explanations many major newspapers boycotted the 2006 awards.
					Press Gazette entered executive receivership toward the end of 2006, then was sold to a trade buyer. On
					4 May 2006, Morgan launched First Reports , a regular paper directed at 7 to fourteen-year-olds. Inside
					a few days the photos were demonstrated to be crude fakes. Under the title "SORRY.. WE WERE HOAXED", the
					Mirror replied that it had become victim to a "figured out and antagonistic hoax" and apologized for the
					publication of the pictures. In May 2005, in cooperation with Matthew Freud, he gained possession of
					Press Gazette, in a deal worth &pound;1 million.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Piers Morgan</div>
			</div>
			<div class="content_paragraph">
				<p>On its launch Morgan claimed that the paper was to be "Britain's first nationwide newspaper for
					children", though this claim was without foundation: other papers directed at young audiences have
					included The Boy's Paper ( 18801882 ), The Children's Paper ( 19191965 ), and Early Times ( launched in
					the latter 1980s ). Morgan was editorial director initially Stories, answerable for bringing in
					celebrity participation. He referred to the job as "editorial overlord and frontman/p>

				<p>In 2007, Morgan was filmed falling off a Segway, breaking 3 ribs. Simon Cowell and others made much of
					Morgan's prior comment in 2003, in the Daily Mail, after U.S.</p>

				<p>President George W. Bush slid off a Segway, that "you would need to be a simpleton to fall off, would you
					not, Mr. President?" Morgan's career has diversified in recent times into TV show and proprietorship. In
					2003, he presented a three-part TV documentary series for the BBC titled the seriousness of Being
					Famous, about celebrity and the fashion in which celebs are covered by modern media. He has co-hosted
					his very own current affairs interview show on Channel four with Amanda Platell, Morgan &amp; Platell.
					Morgan and Platell were put together due to their opposing political angles. Platell would interrogate
					guests from the right-wing, Morgan from the left-wing.</p>

				<p>The show was dropped after 3 series reportedly due to poor viewing figures, though the manager of Channel
					four, Luke Johnson, was reported not to love the program. All though 2006 Morgan appeared as a judge on
					the North American TV show America's Got Talent alongside Brandy Norwood and David Hasselhoff on NBC.
					Morgan was selected by Simon Cowell as an alternative for himself due to the conditions of his American
					Idol contract. Morgan appeared as a celebrity contestant on Comic Relief Does The Apprentice in 2007, to
					raise money for Comic Relief. During filming, he and Alastair Campbell reduced fellow competitor Trinny
					Woodall to tears when they attempted to sabotage her team's event, and were concerned in a fight with
					her. On his team losing, Morgan was chosen by Sir Alan Sugar as the competitor to be fired. Also in
					2007, he appeared as a judge for the second season of America's Got Talent and also appeared as a judge
					on the Brit version of the show, Britain's Got Talent on ITV1, alongside Amanda Holden and Simon Cowell.
					He also presented you can not Fire Me, I am Famous on BBC One.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming Famous TV
				Personality like Piers Morgan? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-1-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-2-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-3-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-4-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/piers_morgan-5-123x164.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/black-eyed_peas">Black Eyed Peas</a></div>
				<div><a href="/industry/david-banner">David Banner</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>
