<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Raven Symone</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/giwkxcHykkY?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone5.jpg" alt="Raven Symone" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('missravensymone').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Raven Symone</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/raven-symone">Raven-Symon&eacute;</a> Christina Pearman (born December 10, 1985), known professionally as Raven-Symon&eacute;, or simply Raven, is an American actress, singer, songwriter, comedian, dancer, television producer and model. She is best known for her television roles as Olivia Kendall on The Cosby Show, Galleria Garibaldi in The Cheetah Girls and The Cheetah Girls 2, and as Raven Baxter in the Emmy Award nominated series, That's So Raven.</p>
				<p>Raven has also lent her voice to the animated series Kim Possible, for the character Monique and films such as Disney's Tinker Bell. Raven-Symon&eacute; also owns a &quot;how-to&quot; video website, Raven-Symon&eacute; Presents.</p>
				<p>Raven-Symon&eacute; was born in Atlanta, Georgia to Lydia (n&eacute;e Gaulden) and Christopher B. Pearman. At age three, her family moved to Ossining, New York where she attended Park School. As an infant, she worked for Atlanta's Young Faces Inc. Modeling Agency and was featured in local print advertisements. At age two, she worked with Ford Models in New York City and appeared in ads for Ritz crackers, Jell-O, Fisher-Price, and Cool Whip.</p>
				<p>In 1989, Raven-Symon&eacute; auditioned for a part in the Bill Cosby movie, Ghost Dad. At three years old she was considered too young for the role, but Bill Cosby liked her so much that he found a part for her on his show, The Cosby Show, as his granddaughter Olivia. Raven-Symon&eacute; played the part of Olivia until 1992. She then appeared as the younger version of Halle Berry's starring character, a headstrong biracial slave, in the TV movie Queen: The Story of an American Family, based on the book by Alex Haley.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Raven Symone</div>
			</div>
			<div class="content_paragraph">
			<p>Raven-Symon&eacute; began her singing career at the age of five, when she signed with MCA Records. She spent that year and the next taking vocal lessons from Missy Elliott. Her debut album, Here's to New Dreams, was released on June 22, 1993, which spawned two singles: &quot;That's What Little Girls Are Made Of&quot; and &quot;Raven Is the Flavor.&quot; &quot;That's What Little Girls Are Made Of&quot; reached #68 on the Billboard Hot 100. The album however was not successful, and due to low sales she was dropped from MCA Records in 1995.</p>
			<p>Within a year after The Cosby Show ended, she landed the role of Nicole Lee on the show Hangin' with Mr. Cooper. During her time on the show, she had her first big screen role in the movie The Little Rascals, playing Stymie's girlfriend.</p>
			<p>In 1996 Raven-Symon&eacute; and her father founded RayBlaze Records, in which she signed a distribution deal with Crash Records for her sophomore album Undeniable, which was released in May 1999. The album yielded one single: &quot;With a Child's Heart.&quot; Stevie Wonder made the original version of the tune, that became a remake by Michael Jackson.</p>
			<p>She was cast in the Eddie Murphy comedy Dr. Dolittle and then Dr. Dolittle 2 as Charisse Dolittle, the oldest daughter of Murphy's character. Meanwhile, she also appeared in Zenon: Girl of the 21st Century, her first production under Disney.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming an Actress like Raven Symone? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/RavenSymone5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/black-eyed-peas">Black Eyed Peas</a></div>
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


