<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Sean Kingston</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/eLkhJ2-0950?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-205x295.jpg" alt="Sean Kingston" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('SEANKINGSTON').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Sean Kingston</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/sean-kingston">Sean  Kingston</a> is a music sensation. Kingston's career took off after  Kingston moved back to Miami to follow a music career. Sean Kingston  was found thru MySpace by Tommy Rotem at Beluga Heights, and signed  to the label in a partnership handle with Sony. Beluga is a label  outstanding for its target discovering and developing artists. In an  interview with HitQuarters label head and producer J.R. Rotem  described this process with regards to Kingston : &quot;Sean Kingston  was a rapper when we found him which was a development process to get  him more melodic. At Beluga we essentially refine the talent in order  that it's more of a marketable product.&quot; In an enterprise  between Epic Records and Koch Records, Kingston recorded and released  the single &quot; Gorgeous Girls&quot; in May 2007. The single, based  totally on the bass line and lyrical &quot;organization&quot; of the  1961 hit &quot;Stand By Me&quot; by Ben E. </p>
				<p>King, reached number one on the US Poster advertisement hot hundred for 3  weeks and topped the United Kingdom Singles Chart with plenty of  other global charts. In a similar way , the track &quot;Me Love&quot;  samples the primary hook out Led Zeppelin's &quot;D'yer Mak'er,&quot;  from their 1973 album Homes of the Holy. </p>
				<p>The track also debuted at number one in Australia, where it knocked off  Fergie's &quot; Large Girls Don't Cry,&quot; which had been at number  one for 9 weeks. </p>
				<p>The track stayed on the Canadian hot hundred top spot for over 6 weeks  before getting knocked down to 3rd place by the Plain White T's.  &quot;Gorgeous Girls&quot; stayed at number one in Canada longer than  any other song in 2007. In 2007, Kingston was the opening act for  Gwen Stefani's The Sweet Escape Tour and for select dates on Beyonc's  The Beyonc Experience Tour. The album Tomorrow was released on Sep  twenty-two, 2009. Big-name producers concerned in the album included  previous Fugee Wyclef Jean; RedOne (of contemporary Woman GaGa  celebrity) ; and Sean's original mentor, J.R. </p>
				<p>Rotem.  So far, the singles &quot;Fire Burning,&quot; and &quot;Face Drop&quot;  have been released. In addition, 5 promotional digital singles were  released leading in to the album. Kingston co-wrote Jason Derlo's  &quot;Whatcha Say&quot;. Kingston also found the RB-reggae singer  Iyaz on MySpace and signed him to his record label. </p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Sean Kingston</div>
			</div>
			<div class="content_paragraph">
				<p>Kingston also recorded the  track &quot;Miss Everything&quot; for the United Kingdom girl-group  Sugababes studio album Sweet 7 which was released March fifteen, 2010  in the UK Kingston and DJ Khaled are being featured on Bow Wow's New  Single &quot;For My Hood&quot; From the imminent picture, The Lottery  Ticket 2010present: Dumb Love and other projects According to Sean  Kingston, Kingston's already working on his next album. The lead  single was confirmed to be &quot;Dumb Love&quot; featuring Lil Wayne  by Kingston himself, but Lil Wayne is serving a jail sentence and a  promo vid hasn't been filmed. It's still most likely a future single  to be released with a promo vid shot after Lil Wayne is freed from  jail. The tune is also featured in an episode of The Suite Life on  Deck which Kingston guest starred on. The album will also have  T-Pain, Nicki Minaj, Kanye West, Wyclef Jean, Akon and Dr. Dre. </p>
				<p>The  first single from the album is &quot;Eenie Meenie&quot; featuring  Justin Bieber, released on March twenty-three, 2010, which is also  included on Bieber's My World 2.0 album. This partnership with the  young star has been the source of much disapproval from the rap  community. The second single from the album &quot;Letting Go (Dutty  Love),&quot; which features a verse from Nicki Minaj. It was  released on iTunes Aug three, while the 3rd is &quot;Dumb Love&quot; and was released on iTunes September eight, the tune doesn't features Lil Wayne. Sean Kingston's new song &quot;She Moves&quot; samples  Irena Cara's &quot;What a Feeling&quot; from the film Flashdance. A  4th single &quot;Party All Night (Sleep All Day)&quot; was released on December twenty-one, 2010. The tune leaked online in December of 2010. The promo video has been shot. The video was released on  December twenty-three, 2010. Sean asserted this would be the track of  the new year. </p>
				<p>Kingston represented the continent of America to sing  the Official Theme Song of the Singapore 2010 Youth Olympic Games,  Everybody . Kingston cooperated with 4 other world artists  representing their continent, South African Jody Williams  representing Africa, Singaporean Tabitha Nauser (Asia), Brit Steve  Appleton (Europe), and Australian Jessica Mauboy representing  (Oceania) However, Kingston was not able to attend, the Singapore  Youth Olympic Games 2010 opening rite, due to passport mix ups  Kingston also released a single called &quot;Letting Go (Dutty Love)&quot; with Young Money's Nicki Minaj. And , close to the end of July 2010,  Kingston was invited and featured on Money Money Records / previous  So So Def member Bow Wow on his single &quot;For My Hood.&quot; </p>
				<p>Kingston performed it with him  with DJ Khaled on BET's TV programme 106 &amp; Park the day after  release. Sean Kingston will release a mixtape with pop star Justin  Bieber, called Our World.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Singer like Sean Kingston? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-1-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-2-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-3-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-4-123x164.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/sean_kingston-5-123x164.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/black-eyed-peas">Black Eyed Peas</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


