<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Shannon Elizabeth</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/s2OVUyJL7cc?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth_main.jpg" alt="Shannon Elizabeth" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('ShannonElizab').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Shannon Elizabeth</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/shannon-elizabeth" title="Shannon Elizabeth">Shannon Elizabeth</a> is an actress and former fashion model who is best known for her role in the popular 1999 comedy 'American Pie'. Elizabeth was a tennis star in high school and at one point even considered a professional tennis career. She worked as a model before she began a career in film</p>
				<p>Shannon Elizabeth appeared in several films, including the horror film Jack Frost and Dish Dogs, before she became famous for her nude bedroom scene in the movie 'American Pie.'</p>
				<p>Shannon Elizabeth subsequently appeared in several Hollywood films, including 'Scary Movie,' 'Jay and Silent Bob Strike Back,' and Tomcats. Elizabeth starred in the UPN series 'Cuts' until the show was canceled in May 2006. Cuts and its parent show, 'One on One,' were two of the many shows not to be picked up by The CW. Elizabeth appeared on 'That '70s Show' for a number of episodes.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">More About Shannon Elizabeth</div>
			</div>
			<div class="content_paragraph">
				<p>Shannon Elizabeth also became famous for being a sex symbol. In August 1999, she posed for a nude pictorial in Playboy Magazine. In 2000 and 2003, she was featured in Maxim In June 2008 she was Maxim's cover girl.</p>
				<p>Shannon Elizabeth was among the cast of the sixth season of 'Dancing with the Stars', where she partnered with Derek Hough. She was the seventh star eliminated from the competition. She was also the host of the comedy/burlesque series "Live Nude Comedy" in 2009.</p>
				<p>In addition to her modeling and acting career, Shannon Elizabeth is one of the leading celebrity poker players. She played in the Main Event of the 2005 World Series of Poker under the guidance of Daniel Negreanu, and won a special tournament celebrating the opening of a new poker room at Caesars Palace hotel in January 2006, beating out 83 celebrities and poker professionals to win $55,000. She has also cashed four times in the World Series of Poker in 2006 and 2007, but again busted out of the Main Event early. In 2007, she advanced to the semi-finals of the NBC National Heads-Up Poker Championship in a field consisting of the top poker professionals before losing to the eventual champion.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming an Actress like Shannon Elizabeth? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/shannon_elizabeth5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/usher-raymond">Usher Raymond</a></div>
				<div><a href="/industry/gabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


