<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Snoop Dogg</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/T2RGYrwiPoo?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/snoop_pic.jpg" alt="Snoop Dogg" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('SnoopDogg').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Snoop Dogg</div>
			</div>
			<div class="content_paragraph">
				<p> Cordozar Calvin Broadus (born October 20, 1971), is better known by his stage name <a href="/industry/snoop-dogg">Snoop Dogg</a>. Snoop Dogg's  hit debut album, Over the Counter, was released in 1991 and his second Doggystyle, was released in 1993 under Death Row Records. Doggystyle went quadruple platinum and spawned several Snoop Dogg hit singles, including "What's My Name" and "Gin & Juice./p>
				<p>As the embodiment of '90s gangsta rap, Snoop Dogg blurred the lines between reality and fiction. Introduced to the world through Dr. Dre's The Chronic, Snoop quickly became the most famous star in rap, partially because of his drawled, laconic rhyming and partially because the violence that his lyrics implied seemed real, especially after he was arrested on charges of being a murder accomplice. The arrest certainly strengthened his myth, and it helped his debut album, 1993's Doggystyle, become the first debut album to enter the charts at number one, but in the long run, it hurt his career. </p>
				<p>As the Creative Chairman of EMI's newly reintroduced Priority Records, Snoop oversees a huge catalog that is filled with gangsta rap anthems (NWA, Eazy E, Master P, Ice Cube) that launched from the streets and infiltrated even the highest suites. </p>
				<p>Snoop's first order of business in his new post is his upcoming 10th solo album, "Malice N Wonderland."  He is also releasing "Doggumentary," a full-length solo masterpiece and has three singles available on Itunes: "Gangbang Rookie," "Wet," and "New Year's Eve."
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">Quotes from Snoop</div>
			</div>
			<div class="content_paragraph">
				<p>"When I started to put together this record I had a lot of malice in my heart—just focusing on making hardcore gangsta music," explains Snoop. But what's become quite obvious to his adoring global fan base is that while Snoop stays steeped in the hood realities of his native Eastside Long Beach, he's continued to evolve. </p>
				<p>And after delving further into this opus, Snoop knew that he also wanted to make songs that embodied more than just his gangsta. "My mood lightened and I wanted to make some music that just felt good…to me and to the ladies."</p>
				<p>"Sometimes, if you`re lucky, someone comes into your life who`ll take up a place in your heart that no one else can fill, someone who`s tighter than a twin, more with you than your own shadow, who gets deeper under your skin than your own blood and bones." <br>-Snoop Dogg </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Rapper like Snoop Dogg? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/2pic1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/2pic2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/2pic3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/2pic4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/2pic5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/gabrielle-union">Gabrielle Union</a></div>
				<div><a href="/industry/tyler-perry">Tyler Perry</a></div>
			</div>
		</td>
	</tr>
</table>


