<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table width="auto" class="border_small">
	<tr>
		<td valign="top" align="left" class="vid-quest-head2"><h2>Sway, Exclusive Interview</h2></td>
	</tr>
	<tr>
		<td valign="top" align="center" style="padding-top:10px">
			<div id="outerdiv" align="center">
				<iframe title="YouTube video player" width="560" height="349"
						src="http://www.youtube.com/embed/p5Dk_TRCaro" frameborder="0" allowfullscreen></iframe>
			</div>
		</td>
	</tr>
	<tr>
		<td valign="top" align="left" style="padding:10px 40px"><p>Sway, the infamous Host from MTV News and &ldquo;Total
			Request Live,&rdquo; gives a shout out to Musician1.com!</p>
		</td>
	</tr>
	<tr>
		<td valign="top" ><a href="/industry/celebrities-exclusive-interviews" style="text-decoration:none"><span
				class="vid-head">More Celebrity Videos</span></a></td>
	</tr>
	<tr>
		<td valign="top" style="border:1px solid #009900; padding:2px"><br>
			<table width="auto" border="0" cellspacing="0" cellpadding="1">
				<tr>
					<td  valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/snoop-dogg"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-snoopdogg-150.jpg" width="150" height="131"
										border="0"
										alt="Snoop Dogg gives advice exclusively to Explore Talent members from his trailer on the set of his new variety show on MTV - Dogg After Dark"/></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Snoop Dogg</p>

									<p>Snoop Dogg on the set of MTV's &quot;Dogg After Dark&quot; Join ExploreTalent -
										&quot;Get
										hooked up&quot;</p></td>
							</tr>
						</table>
						<br/>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/beyedpinterview"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_bleypeas_150x131.jpg"
										alt="Black Eyed Peas Exclusive Interview" width="150" height="131" /></a>
								</td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Black Eyed Peas </p>

									<p>Polo Molina and Venus Brown talk with ExploreTalent. Watch this exclusive
										interview from the 81st Grammy Awards with Polo Molina of the Black Eyed Peas
										and Venus Brown.</p></td>
							</tr>
						</table>
						<br/>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/ericbenet"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb-ericbenet-150.jpg" width="150" height="131"
										border="0" alt="Eric Benet Exclusive Interview"/></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Eric Benet </p>

									<p>Hear Eric Benet&rsquo;s advice for upcoming musicians in this exclusive
										interview. His albums include &ldquo;Love and Life,&rdquo; &ldquo;Hurricane&rdquo;
										and his platinum selling album, &ldquo;A Day In The Life.&rdquo;</p></td>
							</tr>
						</table>
						<br/>
						<br/>
					</td>
					<td width="5">&nbsp;</td>
					<td  valign="top">
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/souljaboyinterview"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_souljaboy_150x131.jpg" width="150" height="131"
										border="0" alt="Soulja Boy Exclusive Interview"/></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Soulja Boy </p>

									<p>Soulja Boy interviews with ExploreTalent at the 2009 BET Awards, talking about
										making music while passing along some sound advice to up and coming
										musicians.</p></td>
							</tr>
						</table>
						<br/>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/rayjinterview"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_rayj_150x131.jpg" width="150" height="131"
										border="0" alt="Ray J Exclusive Interview"/></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Ray J </p>

									<p>Ray J&rsquo;s exclusive interview with ExploreTalent. Musician-Actor-Producer,
										Ray J, gives tips to musicians and actors about how to &ldquo;make it&rdquo; in
										the entertainment industry.</p></td>
							</tr>
						</table>
						<br/>
						<table width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="#eeeeee">
							<tr>
								<td valign="top" width="150"><a href="/industry/mariointerview"><img
										src="<?php echo CDN_JS_CSS; ?>/images/industry/thumb_mario_150x131.jpg" alt="Mario Exclusive Interview"
										width="150" height="131" /></a></td>
								<td valign="top" style="text-align:left; padding:3px 0 0 3px"><p
										style="font-size:16px; font-weight:bold">Mario</p>

									<p>Mario&rsquo;s exclusive interview with Musician1.com. Mario gives advice to new
										and up and coming musicians.</p></td>
							</tr>
						</table>
						<p align="right"><a href="/industry/hiphop-exclusive-interviews">See all Celebrity Hip Hop Interviews</a>
						</p></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
