<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Trey Songz</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/VAsRtIBgV54?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz5.jpg" alt="Trey Songz" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('treysongz').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Trey Songz</div>
			</div>
			<div class="content_paragraph">
        <p><a href="/industry/trey-songz">Trey Songz</a>...While recording his first album in 2004, Songz released multiple mix tapes under the name Prince of Virginia. One of the mix tapes featured an &quot;answer track&quot; to R. Kelly's &quot;Encircled in the Closet,&quot; titled &quot;Open the Closet.&quot; The tune gave Trey some great public exposure. His first album, I Gotta Make It was released on July twenty-six, 2005. </p>
        <p>It debuted at twenty on the Poster advertisement 200, selling forty thousand copies in its first week of sales. It has sold three hundred thousand records in the States, but wasn't guaranteed by the RIAA. Songz's debut single, Gotta Make It, featuring Twista, was released in March 2005 and reached 87 on the Poster advertisement hot hundred and twenty-one on the Hot R&amp;B / Hip hop Songs. It gathered pre-eminence in the R &amp; B / urban community but didn't make a mark in conventional music. </p>
        <p>The single, &quot;Girl Tonite,&quot; reached fourteen on the hot hundred and 3 on the Hot R &amp; B / Hiphop Songs chart, turning into a gigantic hit. In mid-2006, Songz commenced work on a follow-up album to his debut with longtime collaborator Troy Taylor and also employed hitmakers Bryan-Michael Cox, Danja, Stargate ( production team ) and R. Kelly to assist in the creation of the album. Trey targeted for the album to be more mainstream-oriented than his first album. </p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">More on Trey Songz</div>
			</div>
			<div class="content_paragraph">
        <p>Trey released his 3rd studio album, Prepared, on Aug 31, 2009.  The album reached number three on the Billboard 200, selling 131,000 copies in its first week.  These are his best first week sales to date and the album was his first to get to the Top ten on the Poster advertisement two hundred. </p>
        <p>The album has since then sold over 800,000 records in the States, earning a Gold validation from the RIAA in  Feb  2010, becoming his first album to be guaranteed by the RIAA.  The lead single from the album, "I Need a Girl", was released in Apr 2009 and reached five on the   Hot R &amp; B /  Hip hop songs chart and 59 on the hot hundred, becoming   an R &amp; B / urban hit though not a main line hit. </p>
        <p>A promotional single, "Successful", featuring rapper Drake, was released in June 2009 and reached seventeen on the hot hundred, becoming Songz's 3rd Top twenty hit.  The single also served as the second and last single from Drake's EP, So Far Gone.  Like the 1st 2 singles from the album, it achieved achievement in the R &amp; B / urban community but only some conventional success.  Charted in the Poster advertisement hot hundred, and topped the R &amp; B chart.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Rapper like Trey Songz? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz1.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/TreySongz5.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
			</div>
		</td>
	</tr>
</table>


