<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Tyler Perry</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/qD5Yf8kn3Wk?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/tylerperry.jpg" alt="Tyler Perry" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('tylerperry').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Tyler Perry</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/tyler-perry">Tyler Perry</a> is an American actor, director, playwright, screenwriter, producer, author and songwriter. Perry began to reach national celebrity status in 2005 with the release of his first movie, Diary of a Mad Black Woman. In 2009, Tyler Perry was ranked by Forbes magazine as the sixth highest paid man in Hollywood. As of July 2009, Perry's films have grossed nearly $400 million worldwide. </p>
				<p> Tyler Perry is a  writer, actor, producer and director. He was born Emmitt Perry Jr. on  September 13, 1969, in New Orleans, Louisiana. Tyler Perry has forged his own way in the entertainment industry, building an empire that  consists of successful films, plays, and even a best-selling book.  One of four children, he had a difficult childhood, suffering years  of abuse at the hands of his carpenter father. He once described his father as a man &quot;whose answer to everything was to beat it out  of you.&quot;</p>
				<p> Tyler Perry is always looking for new talent to audition for his movies and plays. If you are interested in Tyler Perry auditions, the first place you  should start is be researching reputable talent resource sites,</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Tyler Perry</div>
			</div>
			<div class="content_paragraph">
				<p> Most of Tyler Perry&rsquo;s movies or plays focus on the African-American community.   If you are an African-American actor, you have a better chance of  being cast in a Tyler Perry movie or play. That doesn&rsquo;t mean that  if you are Caucasian you cannot get cast in a Tyler Perry move or  play.  The best advice for actors looking for Tyler Perry auditions  is to constantly search reputable talent resource websites that list  upcoming auditions.</p>
				<p>&ldquo;I wanted to make a statement, not in any grand or boastful way, but to  let people know what God can do when you believe,&quot; he says. &quot;I don't care how low you go, there's an opposite of low, and as low as  I went I wanted to go that much higher. And if there was an opposite  of homelessness, I wanted to find it.</p>
				<p> I wanted to make a statement, not in any grand or boastful way, but to let people know what God can do when you believe," he says. "I don't care how low you go, there's an opposite of low, and as low as I went I wanted to go that much higher. And if there was an opposite of homelessness, I wanted to find it." <br/>
				-Tyler Perry </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Actor like Tyler Perry? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/profile_pic5.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/profile_pic2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/profile_pic3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/profile_pic4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/profile_pic6.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
			</div>
		</td>
	</tr>
</table>


