<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Usher Raymond</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/RWvewJOUgLE?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/u8er71gzs2j6j2g.jpg" width="205" height="295" alt="Usher Raymond" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('USHERRAYMONDIV').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Usher Raymond</div>
			</div>
			<div class="content_paragraph">
				<p>Usher became famous rose with the release of his second album My Way, which spawned his first Billboard Hot 100 number-one hit, "Nice and Slow". His follow-up album 8701 (2001) produced the Billboard Hot 100 number-one hits "U Remind Me" and "U Got It Bad". Both albums sold over 8 million copies worldwide, establishing Usher as one of the biggest selling R&B artists of the 1990s</p>
				<p><a href="/industry/usher-raymond" title="Usher Raymond">Usher Raymond</a>'s success continued with his 2004 album Confessions, which has sold over ten million copies in the United States, and been certified diamond by the RIAA. Confessions has the highest first week sales for an R&B artist in history, and sold over 20 million copies worldwide. It spawned a record breaking four consecutive Billboard Hot 100 number-one hits'"Yeah!", "Burn", "Confessions Part II", and "My Boo". Usher's 2008 album Here I Stand sold over 5 million copies worldwide, and its lead single "Love In This Club" peaked at number-one on the Billboard Hot 100.</p>
				<p>On March 30, 2010, Usher released his sixth studio album Raymond v. Raymond, which became his third consecutive album to debut at number one on the US Billboard 200 chart. It has been certified platinum and spawned another Billboard Hot 100 number-one hit "OMG". The song became his ninth number one in the United States, making him the first 2010s artist to collect number one singles in three consecutive decades, and only the fourth artist of all-time to achieve the feat. He later released an extended play and deluxe edition of "Raymond v. Raymond", entitled Versus, which debuted at number four on the Billboard 200 chart. Its lead single "DJ Got Us Fallin' In Love", achieved international success and has reached number-five on the Billboard Hot 100.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">More On Usher Raymond</div>
			</div>
			<div class="content_paragraph">
				<p>To date, Usher has certified sales of over 65 million records worldwide. He has won numerous awards including seven Grammy Awards,four World Music Awards, six American Music Awards, and nineteen Billboard Music Awards. In 2008, Usher was ranked as the 21st most successful Hot 100 Singles Artist of all-time by Billboard magazine. </p>
				<p>Usher is one of the best-selling artists in American music history, having sold over 23 million copies in the United States alone. Billboard Magazine ranked Usher the number one Hot 100 artist of the 2000s decade.</p>
				<p>They also named him the second most successful artist of the 2000s decade, and his 2004 album Confessions was ranked as the top solo album and second most successful overall album of the last decade. Usher has attained nine hot 100 number-one hits (all as a lead artist) and has attained sixteen hot 100 top-ten hits Aside from his musical career, he is regarded as a sex symbol. In 1998 People Magazine named him the sexiest R&B artist alive. In 2010, Glamour Magazine named him one of the 50 sexiest men alive.</p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming a Singer like Usher Raymond? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/usher2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/usher3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/usher4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/usher5.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/usher6.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/trey-songs">Trey Songz</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
			</div>
		</td>
	</tr>
</table>


