<h1>Exclusive Celebrity Interviews &amp; Advice</h1>
<table class="industry_title">
	<tr>
		<td class="name_title"><h2>Vanessa and Angela Simmons</h2></td>
		<td>
			<div class="joinbutton"><a href="/join/flash">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/button_join.png" width="436" height="61" alt="join">
			</div>
		</td>
	</tr>
</table>

<table class="industry_header">
	<tr>
		<td>
			<iframe title="YouTube video player" width="290" height="242"
			        src="http://www.youtube.com/embed/M5jPzkTdasQ?rel=0" frameborder="0" allowfullscreen></iframe>
		</td>
		<td>
			<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon1.jpg" alt="Vanessa and Angela Simmons" name="profile_pic"
			     id="profile_pic"/>
		</td>
		<td>
			<div id="twitter_container">
				 <script type="text/javascript" src="<?php echo CDN_JS_CSS; ?>/js/widgets.twimg.js"></script>
				 <script type="text/javascript">
					new TWTR.Widget({
						version:2, type:'profile', rpp:2, interval:6000, width:200, height:350,
						theme:{
							shell:{background:'#009dff', color:'#ffffff'},
							tweets:{background:'#ffffff', color:'#2e2e2e', links:'#009dff'}
						},
						features:{
							scrollbar:false, loop:false, live:false, hashtags:true, timestamp:true, avatars:true, behavior:'all'
						}
					}).render().setUser('V_SimmonsFans').start();
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_add">
	<tr>
		<td>
			<a href="/join/flash" target="_blank" class="join_link">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/join_now.jpg" width="234" height="30" />
			</a>
		</td>
		<td>
			<div class="celeb-ad">
				<script type="text/javascript">
					<!--
					google_ad_client = "pub-7367493847549945";
					/* 468x60, created 1/26/11 */
					google_ad_slot = "3706098432";
					google_ad_width = 468;
					google_ad_height = 60;
					//-->
				</script>
				<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
				</script>
			</div>
		</td>
	</tr>
</table>

<table class="industry_body">
	<tr>
		<td>
			<div class="content_title">
				<div class="title_text">About Vanessa and Angela Simmons</div>
			</div>
			<div class="content_paragraph">
				<p><a href="/industry/Vanessa-and-Angela-Simmons">Vanessa and Angela Simmons</a> (Vanessa Angela Simmons) are the daughters of Joseph &quot;Rev Run&quot; Simmons, a founding member of the iconic hip-hop group Run DMC. All three star on the MTV reality series &quot;Run's House&quot; with the rest of their family. Vanessa Angela Simmons has helped remake shoe styles and designs.</p>
				<p>In 2006, Vanessa and Angela Simmons came up with the idea for feminine but sporty footwear, Vanessa Angela Simmons called it Pastry and launched in spring 2007 with 4 shoes. The line was a runaway hit and Pastry did over $15 million in 2007 sales.  </p>
				<p>Clothing and handbags were added in spring 2008, and the line has been projected to bring over $50 million in total sales by year end.</p>
				<p>Vanessa Simmons is the oldest daughter and oldest child. She grew up in the family home in New Jersey and graduated from St. John's University in 2007 with a degree in Communications. Vanessa and Angela Simmons have brought their fashion sense and designs into the spotlight.</p>
				<p>Vanessa and Angela Simmons: &quot;Pastry is a lifestyle fashion brand designed by Vanessa and Angela Simmons of MTV's Run's House. Pastry offers colorful, fun footwear for &quot;stylish young ladies&quot; by &quot;stylish young ladies.&quot; Source:Pastry Kicks official site Vanessa and Angela Simmons ( Vanessa Angela Simmons ) are the daughters of Joseph &quot;Rev Run&quot; Simmons who was a founding member of the groundbreaking rap group Run DMC.</p>
				<p> He now heads up Run Athletics, an athleticwear company, along with his brother Russell Simmons. Angela and Vanessa Simmons came up with the idea for their footwear line on Run's House, a reality series on MTV. </p>
				<p>Vanessa and Angela Simmons ( Vanessa Angela Simmons ) Pastry Kicks was launched in spring 2007 as a lifestyle brand, and has a playfuldesserts and candy theme.</p>
			</div>
		</td>
		<td>
			<div class="content_title">
				<div class="title_text">A few words from Vanessa and Angela Simmons</div>
			</div>
			<div class="content_paragraph">
				<p>In addition to being a footwear entrepreneur, she is also a Ford model and aspiring actress. She was #82 in Maxim Magazine's &quot;Hot 100&quot; 2006 list. In March 2007, she was featured in a national Verizon commercial and later was cast in a limited role as Lola on the CBS soap opera &quot;Guiding Light.&quot;</p>
				<p>Vanessa Simmons  takes acting very seriously. She recently bowed out from the Miss California USA competition to begin production on &quot;Boogie Town,&quot; a modern day hiphop West Side Story flick which takes place in a New York City of the future. The movie is due out in summer 2009.</p>
				<p>Vanessa  Simmons  currently resides in Hollywood, CA with her sister Angela Simmons . Angela Simmons  is the second daughter and second oldest. She graduated from the High School of Fashion Industries and attended <br>
					the Fashion Institute of Technology. </p>
				<p>Angela  Simmons  is executive editor of Word Up! magazine's subsidiary publication &quot;Angela's Rundown&quot;. &quot;Angela's Rundown&quot; is a monthly magazine targeting youths age 14-18 and cover teen issues, style, music, and fashion while offering fashion tips and in-depth celebrity interviews.</p>
				<p>She  was also featured in Bow Wow's video &quot;Shorty Like Mine.&quot; Rev Run confirmed she was dating Bow Wow in 2007 in his book &quot;Take Back Your Family.&quot;</p>
				<p>In 2008, she and Vanessa Simmons were selected as one of BET's &quot;Top 25 under 25.&quot;</p>
				<p>The line also got a big boost when it was featured on Run's House, an MTV reality show that profiles Rev Run's family. &quot;You can't even pay for that! People got to see us develop Pastry from the beginning so that does even more to push our brand forward. We have so many viewers so that helped a lot,&quot;  Angela Simmons says. There is even talk that the girls may be getting their own spin-off show on MTV, but details are still pending. </p>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2" class="become_famous">
			<a href="/join/flash">Interested in Becoming TV Personalities like Vanessa and Angela Simmons? Click Here to Start Your Career!</a>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Photos</div>
			<div class="photo_container">
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon2.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon3.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon4.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon5.jpg" width="124" height="164" class="profile_pic"/>
				<img src="<?php echo CDN_JS_CSS; ?>/images/industry/VanessaandAngelaSimmon6.jpg" width="124" height="164" class="profile_pic"/>
			</div>
		</td>
	</tr>
	<tr>
		<td colspan="2">
			<div class="content_title">Other Celebrities</div>
			<div class="other_celebs">
				<div><a href="/industry/jamie-foxx">Jamie Foxx</a></div>
				<div><a href="/industry/piers-morgan">Piers Morgan</a></div>
				<div><a href="/industry/snoop-dogg">Snoop Dogg</a></div>
			</div>
		</td>
	</tr>
</table>


